Add username
ChainSafe/files-ui pull request #1133
Opened 2021-06-14 19:32 UTC by tanmoyAtb

closes #1091

2021-06-15 15:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/files-ui?pullRequest=1133) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/files-ui?pullRequest=1133) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: tanmoyAtb<br/>:x: actions-user<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/files-ui?pullRequest=1133) it.</sub>

2021-06-16 11:32 UTC, Tbaut requested changes
Working well but I'm getting some 404 on `https://stage.imploy.site/api/v1/user/lookup` when typing something (although the lookup does work).

2021-06-16 11:32 UTC, Tbaut commented on packages/common-components/src/TextInput/FormikTextInput.tsx
> +        label={label ? label : hideLabel ? undefined : field.name}
This is convoluted. Would this make more sense?
```suggestion
        label={hideLabel ? undefined : label || field.name}
```

2021-06-16 11:32 UTC, Tbaut commented on packages/common-components/src/TextInput/TextInput.tsx
> +  onChange?: (value: string | number | undefined) => void
with ?
```suggestion
  onChange?: (value?: string | number) => void
```

2021-06-16 11:32 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/Profile.tsx
> +  const onLookupUsername = async (username: string) => {
We're not catching errors here. Also with 1 await, a promise.then.catch may work just as well.

2021-06-16 11:32 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/Profile.tsx
> +  const onUsernameChange = async (value: any) => {
no need for async, need for useCallback. And we can avoid the `any` here.

2021-06-16 11:32 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/Profile.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
Something wrong here, shouldn't need to silence it. I played with it and removing the useCallback by a `useMemo(() => debounce(onLookupUsername, 200), [onLookupUsername])` and adding a useCallback to `onLookupUsername` let it work pretty well, but pelase don't take my word for it and double-check that it's debouncing well

2021-06-16 11:32 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/Profile.tsx
> +  const onSubmitUsername = (e: any) => {
`(e: React.FormEvent<HTMLFormElement>)`

2021-06-16 11:32 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/Profile.tsx
> +      addToastMessage({ message: t`Username added` })
set successfully ?
```suggestion
      addToastMessage({ message: t`Username set successfully` })
```

2021-06-16 11:32 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/Profile.tsx
> +                : null}
the ternary should be replaced by `question && <Component>` instead of `question ? <Component> : null`

2021-06-16 11:32 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/Profile.tsx
> +                : null}
Same here, the `: null` should be removed and use a && instead.

2021-06-16 11:32 UTC, Tbaut commented on packages/files-ui/src/Contexts/UserContext.tsx
> +  lookupOnUsername: (username: string) => Promise<boolean | undefined>
undefined not needed (see next comment)
```suggestion
  lookupOnUsername: (username: string) => Promise<boolean>
```

2021-06-16 11:32 UTC, Tbaut commented on packages/files-ui/src/Contexts/UserContext.tsx
> +    if (!profile) return
return false
```suggestion
    if (!profile) return false
```

2021-06-16 11:32 UTC, Tbaut commented on packages/files-ui/src/Contexts/UserContext.tsx
> +          : "There was an error setting username."
translation
```suggestion
          : t`There was an error setting username.`
```

2021-06-16 11:32 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/Profile.tsx
> +                Profile settings
Trans
```suggestion
                <Trans>Profile settings</Trans>
```

2021-06-16 11:32 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/Profile.tsx
> +                      hideLabel={true}
Didn't check deeper but can't we have empty label rather?

2021-06-16 11:32 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/Profile.tsx
> +      color: palette.primary.main,
black please, see my comment int he issue. There's no such buttonLink anywhere else in the UI. We need to be consistent :)

2021-06-16 11:32 UTC, Tbaut commented on packages/files-ui/src/Contexts/UserContext.tsx
> +    } catch (error) {
```suggestion
    } catch (error) {
      console.error(error)
```

2021-06-16 11:32 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/Profile.tsx
> +  })
```suggestion
  const [usernameData, setUsernameData] = useState({error: "", loading: false})
```

2021-06-16 18:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/files-ui?pullRequest=1133) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/files-ui?pullRequest=1133) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/files-ui?pullRequest=1133) it.</sub>

2021-06-16 18:31 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/Settings/Profile.tsx
> +                      hideLabel={true}
the `label` is actually optional, but the `FormikTextInput` passes the `field.name` and I had no way of removing that since its being used else where in code.

2021-06-16 18:43 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/Settings/Profile.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
This works just as perfect! thanks!

2021-06-16 18:59 UTC, tanmoyAtb commented
> Working well but I'm getting some 404 on `https://stage.imploy.site/api/v1/user/lookup` when typing something (although the lookup does work).

Yes, the `lookup` api responds with 404 when it doesn't find a username we are sending,
not sure if thats a standard behaviour but it works.

2021-06-16 20:47 UTC, FSM1 approved these changes

2021-06-17 09:23 UTC, Tbaut commented
> api responds with 404 when it doesn't find a username we are sending,
not sure if thats a standard behaviour but it works.

ok a 404 is definitely not a standard for an expected answer, this is showing red things all over (network and console tab), it is an error. I guess it should be a 200 with `{"message": false}` or something. I'll check with the api team

2021-06-17 12:35 UTC, Tbaut approved these changes
:+1: nice one! Just the cla signing is missing :man_shrugging:

2021-06-17 13:43 UTC, tanmoyAtb commented
> > api responds with 404 when it doesn't find a username we are sending,
> > not sure if thats a standard behaviour but it works.
> 
> ok a 404 is definitely not a standard for an expected answer, this is showing red things all over (network and console tab), it is handled as an error in the code and in the browser. I guess it should be a 200 with `null` or something. I'll check with the api team

Yes a 200 with null, sounds right!

2021-06-17 13:47 UTC, merged