Storage buckets overview
ChainSafe/files-ui pull request #1140
Opened 2021-06-15 15:32 UTC by FSM1

Closes #1104

2021-06-16 10:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/files-ui?pullRequest=1140) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/files-ui?pullRequest=1140) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/files-ui?pullRequest=1140) it.</sub>

2021-06-17 12:30 UTC, Tbaut reviewed
Wow this is a huge one! Couple things I noticed while playing with it:
Styling for root is missing here: 
![image](https://user-images.githubusercontent.com/33178835/122396620-74f26580-cf78-11eb-9905-6dd6e4de5430.png)

On a File/pin, there's no menu, is that expected for now?
![image](https://user-images.githubusercontent.com/33178835/122396677-850a4500-cf78-11eb-9514-cd7f974930ff.png)

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/CreateFolderModal/CreateFolderModal.tsx
> +      .required("Folder name is required")
needs translation (no suggestion because `t` must be imported first)

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/CreateFolderModal/CreateFolderModal.tsx
> +        "Invalid name",
translation here too

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/CreateFolderModal/CreateFolderModal.tsx
> +              helpers.setFieldError("name", "Folder name is already in use")
translation :)

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemGridItem.tsx
> +import React, { useCallback, useEffect } from "react"
I thoughts we wouldn't implement grid items for Storage because there's no preview?

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
> +      (!desktop && items.length === 0 /*&& uploadsInProgress?.length === 0 */) ? (
With the rest commented out, this is equivalent to `items.length === 0`

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/MoveFileModal/MoveFileModal.tsx
> +import { createStyles, makeStyles, useMediaQuery } from "@chainsafe/common-theme"
This is not used afaics

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/UploadFileModal/UploadFileModal.tsx
> +        helpers.setFieldError("files", "File/Folder exists")
translation
```suggestion
        helpers.setFieldError("files", t`File/Folder already exists`)
```

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/UploadProgressModals/index.tsx
> +  const WIDTH = 400
Not sure why we're using a const that's only reused once here.

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/BucketPage.tsx
> +  const moveItemsToBin = useCallback(async (
Should we remove it alltogether?

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/BucketPage.tsx
> +  const handleDownload = useCallback(async (
Should be removed?

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/BucketsPage.tsx
> +          <Button onClick={() => setCreateBucketOpen(true)}>Create Bucket</Button>
Trans missing
```suggestion
          <Button onClick={() => setCreateBucketOpen(true)}><Trans>Create Bucket</Trans></Button>
```

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/BucketsPage.tsx
> +        <Typography>Bucket Name</Typography>
Trans
```suggestion
        <Typography><Trans>Bucket Name</Trans></Typography>
```

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Contexts/StorageContext.tsx
> +        // TODO: Update this to include Share buckets where the current user is the owner
There's no such thing as a shared bucket for storage right?
```suggestion
```

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Contexts/StorageContext.tsx
> +              "We can't encrypt files larger than 2GB. Some items will not be uploaded",
But there's no ecnryption here rigth?
```suggestion
              "We can't upload files larger than 2GB. Some items will not be uploaded",
```
FMY why this restriction?
Also will this prevent the upload? There's no return here.

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Contexts/StorageContext.tsx
>    // const getPinContent = useCallback(async (
I think we can remove this all by now. Pins have a link to a public gateway.

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/CreateFolderModal/CreateFolderModal.tsx
> +                label="Folder Name"
translation for label and placeholder :)

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/DownloadProgressModals/DownloadBox.tsx
> +  )
Ternary starting the line and <Trans>
```suggestion
        {
          complete
            ? <div className={classes.contentContainer}>
              <CheckCircleIcon className={classes.marginRight} />
              <Typography
                variant="body1"
                component="p"
              >
                <Trans>Download complete</Trans>
              </Typography>
            </div>
            : error
              ? <div className={classes.contentContainer}>
                <CloseCircleIcon className={classes.marginRight} />
                <Typography
                  variant="body1"
                  component="p"
                >
                  {errorMessage}
                </Typography>
              </div>
              : <div>
                <Typography
                  variant="body2"
                  component="p"
                  className={classes.marginBottom}
                >
                  <Trans>Downloading {fileName}...</Trans>
                </Typography>
                <ProgressBar
                  progress={progress}
                  size="small"
                />
              </div>
        }
```

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/DownloadProgressModals/index.tsx
> +  const WIDTH = 400
Why using a const here?

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
> +  // Previews
Should we remove it?

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
> +        "delete",
Should we remove download, move, preview, share, recover?

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
> +      {/* {files && previewFileIndex !== undefined && bucket && (
Should this be removed?

2021-06-17 12:30 UTC, Tbaut commented on packages/storage-ui/src/Contexts/types.ts
> +  | "rename"
Should we adapt this to Storage now?

2021-06-17 14:06 UTC, Tbaut commented
Damn it, I pushed to the wrong branch.. reverting

2021-06-18 11:11 UTC, tanmoyAtb requested changes
This is lit!
The implementation with the file browser works very well! 
I think some of the `shared` overview code got into this PR, I avoided them checking them here.

2021-06-18 11:11 UTC, tanmoyAtb commented on packages/storage-ui/src/Components/Elements/BucketRow.tsx
> +            onClick: () => removeBucket(bucket.id)
Question!,
I tried removing a bucket I created,

I get this error ?
<img width="512" alt="Screenshot 2021-06-18 at 4 39 15 PM" src="https://user-images.githubusercontent.com/10713353/122549012-d76c6400-d053-11eb-95f0-cc746b8c34d3.png">

2021-06-18 11:11 UTC, tanmoyAtb commented on packages/storage-ui/src/Components/Modules/DownloadProgressModals/index.tsx
> +  const WIDTH = 400
These have been brought from the `files-ui` package,
So we defined particular variables at the start  of CSS, so that we can easily find them later and change (not have to look through the CSS),
for example the modal width, table cell sizes etc.

2021-06-18 11:11 UTC, tanmoyAtb commented on packages/storage-ui/src/Components/Pages/BucketPage.tsx
> +  )
nit
```suggestion
  const currentPath = useMemo(() => {
    return extractFileBrowserPathFromURL(pathname, ROUTE_LINKS.Bucket(bucketId, "/"))
  }, [pathname, bucketId])
```

2021-06-18 11:11 UTC, tanmoyAtb commented on packages/storage-ui/src/Components/StorageRoutes.tsx
> +  Bucket: (id: string, bucketPath: string) => `/bucket/${id}${bucketPath}`
I always get scared when I see these expressions `${id}${bucketPath}`,
if the starting `/` will bee there always

2021-06-18 11:11 UTC, tanmoyAtb commented on packages/storage-ui/src/Components/Elements/BucketRow.tsx
> +import React from "react"
I'd like thee BucketRow to have a `pointer` cursor,
since its a single click implementation.

2021-06-18 12:14 UTC, Tbaut commented on packages/storage-ui/src/Components/Elements/BucketRow.tsx
> +            onClick: () => removeBucket(bucket.id)
yes this is expected, it's work in progress on the api side.

2021-06-18 12:17 UTC, Tbaut commented
@tanmoyAtb 
> I think some of the shared overview code got into this PR, I avoided checking them here.

that's my fault, my branch has almost the same name (overview) and the same number (1014 or something) which was enough for me to mix them. let me check and revert those commits.

2021-06-18 15:15 UTC, FSM1 commented on packages/storage-ui/src/Contexts/StorageContext.tsx
> +              "We can't encrypt files larger than 2GB. Some items will not be uploaded",
That's correct, the upload will still happen, but any files larger than 2GB will be excluded.

At the moment, this limit is in place to prevent devices from burning through too much RAM and CPU trying to encrypt large files.

2021-06-18 16:18 UTC, Tbaut approved these changes

2021-06-18 18:33 UTC, tanmoyAtb approved these changes
🚀

2021-06-18 18:52 UTC, merged