rename shared folder
ChainSafe/files-ui pull request #1197
Opened 2021-06-28 16:45 UTC by tanmoyAtb

closes #1130

2021-06-29 10:39 UTC, Tbaut requested changes
Found a bug when renaming a second time without refreshing, the old name is showing up in the field:

https://user-images.githubusercontent.com/33178835/123783651-e4e8e000-d8d6-11eb-8997-7b636c6adc15.mp4

2021-06-29 10:40 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
> +  editing: boolean
can we call it `isEditing`?

2021-06-29 10:44 UTC, Tbaut commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +    if (showLoading) setIsLoadingBuckets(true)
Maybe `showLoading && setIsLoadingBuckets(true)`

2021-06-29 14:38 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
> +  editing: boolean
sure thing

2021-06-29 14:38 UTC, tanmoyAtb commented
> Found a bug when renaming a second time without refreshing, the old name is showing up in the field:
> 
>  rename.mp4

good catch! looking into it

2021-06-29 15:16 UTC, tanmoyAtb commented
> Found a bug when renaming a second time without refreshing, the old name is showing up in the field:
> 
>  rename.mp4

Cool, had to add `reinitializeOnProps` for this formik, its working now!

2021-06-29 16:06 UTC, Tbaut approved these changes
Awesome stuff

2021-06-30 10:46 UTC, FSM1 requested changes
Works perfectly for those buckets where the user is an owner.

Just need to add a check on the menu items to ensure that the current user is an owner of the bucket. I think that for other users, the menu dropdown can just be disabled, as I don't think there are currently any actions a reader/writer can perform on a bucket level.

2021-06-30 18:02 UTC, tanmoyAtb commented
> Works perfectly for those buckets where the user is an owner.
> 
> Just need to add a check on the menu items to ensure that the current user is an owner of the bucket. I think that for other users, the menu dropdown can just be disabled, as I don't think there are currently any actions a reader/writer can perform on a bucket level.
> 
> Also found that renaming a shared bucket currently resets the list of readers and writers to empty arrays

I added the owner check to show menu,
also commented out delete bucket for now

2021-07-01 11:47 UTC, RyRy79261 approved these changes

2021-07-02 10:43 UTC, FSM1 approved these changes

2021-07-02 12:41 UTC, FSM1 approved these changes

2021-07-02 12:50 UTC, merged