Owner column in shared folder overview
ChainSafe/files-ui pull request #1225
Opened 2021-07-02 12:30 UTC by tanmoyAtb

closes #1129

2021-07-02 14:25 UTC, Tbaut requested changes
We should show the actual owner when it's not us.

2021-07-02 14:25 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
> +          {isOwner && t`me`}
We should show here who's the owner when it's not us. This info can be found on the `bucket.owners` afaik

2021-07-02 16:21 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
> +          {isOwner && t`me`}
sounds good!

2021-07-06 09:55 UTC, RyRy79261 commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
> +            ? t`me`
Shouldn't this be in a bubble as well? Seems a bit awkward just the left aligned word there

2021-07-06 11:09 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
> +            ? t`me`
Problem with a bubble is that you need an additional action (mouse over) to know if you're the owner. The original issue is about knowing right away https://github.com/ChainSafe/files-ui/issues/1129 and it contains the design which Cindy spent quite some time on. If we have issues with the original design, I think it'd be better to discuss it there. I don't think the "me" is awesome, but I personally prefer this than a bubble that needs an action

2021-07-06 11:28 UTC, Tbaut approved these changes

2021-07-06 13:25 UTC, FSM1 approved these changes

2021-07-06 13:25 UTC, merged