Share existing (non shared) file
ChainSafe/files-ui pull request #1255
Opened 2021-07-09 14:22 UTC by Tbaut

closes #1161

2021-07-14 09:13 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/ShareFileModal.tsx
> +    // todo extract in helper for isOwner, isWritr, isReader
FYI I'll do that in a separate PR for easier review

2021-07-14 09:42 UTC, FSM1 requested changes
This is amazing work Thibaut.

The button layout on the Share modal needs to be fixed: 
![image](https://user-images.githubusercontent.com/12774278/125600020-fac6d16f-a53a-4ab1-a13d-7a7f1ce6e7b9.png)

Additionally, The `ShareBucket` API call should be made once the upload to the shared folder has been made. This will remove the original file from the user's file system and create the "symlink" to the shared bucket in the users file system

2021-07-14 10:00 UTC, Tbaut commented
> The button layout on the Share modal needs to be fixed

:see_no_evil: I've seen this for so long now that I didn't even think about it any more!

> The ApiClient.ShareBucket(...) API call should be made once the upload to the shared folder has been made. This will remove the original file from the user's file system and create the "symlink"

Ah, I didn't think about that one, this would mean that someone with write access would actually be able to delete that file, I'm not sure what would be the implications. I'll ask in the chat to discuss about this.

2021-07-14 14:27 UTC, RyRy79261 reviewed
An awesome clean up and implementation, just testing render quick

2021-07-14 14:33 UTC, RyRy79261 commented
Just some minor styling points: 
Some spacing between the bottom two elements:
![image](https://user-images.githubusercontent.com/10461622/125639852-4b045b94-9174-4035-b52d-0da85e801721.png)

Not sure about the view folder link here, maybe some spacing: 
![image](https://user-images.githubusercontent.com/10461622/125640020-5bedb053-1f45-4c63-a426-1baf765abc8c.png)

2021-07-14 14:38 UTC, FSM1 approved these changes
Really amazing work @Tbaut 🥇 Since the "Move to shared folder" can be added later I think we can merge this, and figure out which way we are going to tackle the rest in another issue

2021-07-15 09:18 UTC, Tbaut commented
Here we go @RyRy79261 , should be better now

![image](https://user-images.githubusercontent.com/33178835/125763371-5db44bf2-bda4-4d0e-bb24-78d33d0c6e38.png)
![image](https://user-images.githubusercontent.com/33178835/125763386-08b9f9ca-6efb-465e-a200-671148b38bca.png)

2021-07-15 09:25 UTC, RyRy79261 approved these changes

2021-07-15 09:25 UTC, merged