Create bucket modal changes
ChainSafe/files-ui pull request #1258
Opened 2021-07-12 17:01 UTC by tanmoyAtb

Closes #1237 

Added formik, focus and loaders as well

2021-07-13 09:39 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/BucketsPage.tsx
> +    if (createBucketModalOpen) {
This is a dirty hack. we should use the `autoFocus` props on the Formik field

2021-07-13 09:39 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/BucketsPage.tsx
> +  const folderNameValidator = yup.object().shape({
I think this can be defined outside of the component because it has no dependency. This way it doesn't get computed for each render.

2021-07-13 09:39 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/BucketsPage.tsx
> +  const [createBucketModalOpen, setCreateBucketModalOpen] = useState(false)
Could we have a `isCreateBucketModalOpen` ? for consistency, any boolean state should be is*

2021-07-13 09:39 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/BucketsPage.tsx
> +            onSubmit={async (values) => {
Let's use Promise.then.catch. so that we log thing and don't need this try/catch + async

2021-07-13 09:39 UTC, Tbaut commented on packages/storage-ui/src/Contexts/StorageContext.tsx
> -    storageApiClient.createBucket({
Instead of changing this all to try/catch, we can just return the promise I think, `return storageApiClient.createBucket(...`

2021-07-13 11:14 UTC, tanmoyAtb commented on packages/storage-ui/src/Components/Pages/BucketsPage.tsx
> +    if (createBucketModalOpen) {
great suggestion! thanks!

2021-07-13 11:30 UTC, tanmoyAtb commented on packages/storage-ui/src/Contexts/StorageContext.tsx
> -    storageApiClient.createBucket({
I wanted to do that, but I also had to call `refreshBuckets` after the `createBucket`, and I didn't want refreshBucket in the BucketsPage

2021-07-13 11:31 UTC, tanmoyAtb commented on packages/storage-ui/src/Components/Pages/BucketsPage.tsx
> +            onSubmit={async (values) => {
using `useFormik` now with `then catch`

2021-07-13 14:37 UTC, Tbaut commented on packages/storage-ui/src/Contexts/StorageContext.tsx
> -    storageApiClient.createBucket({
I'm not sure I understand what you mean. From what I understand you want to make sure the `createBucket` returns a `Promise<void>` so that you can chain some other logic (in the `BucketsPage`).

What I would suggest is to keep the whole .then.catch, and just return the whole promise, so that you can chain things in the same way. This should do the trick

```diff
  const createBucket = useCallback((name: string) => {
-    storageApiClient.createBucket({
+    return storageApiClient.createBucket({
      name,
      type: "fps",
      public: "read",
      encryption_key:""
    }).then(() =>
      refreshBuckets()
    ).catch(console.error)
  }, [storageApiClient, refreshBuckets])

```

2021-07-13 17:50 UTC, tanmoyAtb commented on packages/storage-ui/src/Contexts/StorageContext.tsx
> -    storageApiClient.createBucket({
Sorry, I was thinking of importing the refreshBuckets as well,
Anyways I updated it to your suggestions,
good to go!

2021-07-13 18:36 UTC, asnaith commented
Hey @tanmoyAtb, I checked this out on Render and I was still able to reproduce the problem by following the repro steps mentioned on #1237

2021-07-13 18:51 UTC, tanmoyAtb commented
> Hey @tanmoyAtb, I checked this out on Render and I was still able to reproduce the problem by following the repro steps mentioned on #1237

Thanks for checking in on this, I pushed a change which should fix this!

2021-07-13 19:54 UTC, FSM1 requested changes
Just a few minor comments, but otherwise, works really well.

2021-07-13 19:54 UTC, FSM1 commented on packages/storage-ui/src/Components/Pages/BucketsPage.tsx
> +    .required(t`Folder name is required`)
```suggestion
    .required(t`Bucket name is required`)
```

2021-07-13 19:54 UTC, FSM1 commented on packages/storage-ui/src/Components/Pages/BucketsPage.tsx
> +      t`Folder name cannot contain '/' character`,
```suggestion
      t`Bucket name cannot contain '/' character`,
```

2021-07-13 19:54 UTC, FSM1 commented on packages/storage-ui/src/Components/Pages/BucketsPage.tsx
> +      (val: string | null | undefined) => !!val && !val.includes("/")
Not sure if this rule is valid for bucket names

2021-07-13 21:11 UTC, Tbaut commented on packages/storage-ui/src/Contexts/StorageContext.tsx
> +    }).then(refreshBuckets).catch(console.error)
```suggestion
    })
    .then(refreshBuckets)
    .catch(console.error)
```

2021-07-13 21:11 UTC, Tbaut approved these changes
Good to go after the suggestions

2021-07-14 05:42 UTC, tanmoyAtb commented on packages/storage-ui/src/Components/Pages/BucketsPage.tsx
> +      (val: string | null | undefined) => !!val && !val.includes("/")
Nevertheless, its a good rule to have I feel, not allowing '/'

2021-07-14 08:13 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/BucketsPage.tsx
> +      (val: string | null | undefined) => !!val && !val.includes("/")
I'd say so too, the / would only bring mess. I would reconsider only if that's something annoying some users.

2021-07-14 08:46 UTC, FSM1 approved these changes

2021-07-14 08:56 UTC, merged