Fix to prevent from moving folders in sub-folders
ChainSafe/files-ui pull request #1277
Opened 2021-07-15 12:17 UTC by Tbaut

closes #1267 

My helper function involves some JS tricks that I commented, let me know if it's not clear.

2021-07-15 12:18 UTC, Tbaut commented on packages/files-ui/src/Utils/pathUtils.ts
> +      //break out of the every look
```suggestion
      //break out of the loop
```

2021-07-15 12:18 UTC, Tbaut commented on packages/storage-ui/src/Utils/pathUtils.ts
> +      //break out of the every look
```suggestion
      //break out of the loop
```

2021-07-15 14:06 UTC, FSM1 requested changes
It seems like there is something going wrong with the logic here:
![image](https://user-images.githubusercontent.com/12774278/125801271-6eec7113-974f-4a75-bea1-a231de9e5f8e.png)

See the screenshot above where I am trying to move `/another parent` into `/parent` but not being allowed to even though there is nothing that should be preventing the move. i.e. after the move the path should be 

```
|-parent
|--another parent
|--Other parent content
```

2021-07-15 14:18 UTC, Tbaut commented
Ah right, I don't allow to move the folder into any subfolder of the current path. I'll adapt.

2021-07-15 15:13 UTC, Tbaut commented
Ok this is turning into some dark magic.. I will probably not understand half of it any more in 2 weeks, hence the comments.
I tested the weirdest things and it look all right to me now.

2021-07-15 15:16 UTC, Tbaut commented on packages/files-ui/src/Utils/pathUtils.ts
> +    // if paths1 is longer than paths2
```suggestion
    // if we reach the end of paths2, then it's a subfolder
```

2021-07-15 15:17 UTC, Tbaut commented on packages/storage-ui/src/Utils/pathUtils.ts
> +    // if paths1 is longer than paths2
```suggestion
    // if we reach the end of paths2, then paths1 is a subfolder of paths2
```

2021-07-15 16:43 UTC, asnaith commented
I just tested out the fix on Render (for Storage). It looks good for subfolders now, it's not possible to move a parent into a subfolder. 

However, on a related note I just noticed you can move the parent into itself, "Folder1" to "Folder1", and loose access in the UI. Do you want to address in this PR or should I create a separate issue? 

*Video:*

https://user-images.githubusercontent.com/3982665/125825458-17b5cccf-dd78-4040-a14f-b4cba6dca4e3.mov

2021-07-15 17:47 UTC, tanmoyAtb commented on packages/storage-ui/src/Components/Modules/MoveFileModal/MoveFileModal.tsx
> +              folders.length
The error coming up wrong,
```suggestion
              movePath !== currentPath
```

2021-07-15 17:55 UTC, tanmoyAtb requested changes
Amazing, 
A few comments to resolve some of the problems.

2021-07-15 17:55 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/MoveFileModal.tsx
> +              folders.length
The right error comes up this way
```suggestion
              movePath !== currentPath
```

2021-07-15 17:55 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/MoveFileModal.tsx
> +      const currentPathWithFolder = `${currentPath}/${folder.name}`
This should also solve the problem of moving into itself that @asnaith reported
Don't forget to add the import of `getPathWithFile`
```suggestion
      const currentPathWithFolder = getPathWithFile(currentPath, folder.name)
```

2021-07-15 17:55 UTC, tanmoyAtb commented on packages/storage-ui/src/Components/Modules/MoveFileModal/MoveFileModal.tsx
> +      const currentPathWithFolder = `${currentPath}/${folder.name}`
same here
```suggestion
      const currentPathWithFolder = getPathWithFile(currentPath, folder.name)
```

2021-07-15 20:41 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/MoveFileModal.tsx
> +              folders.length
I don't think the error is wrong, in which case do you have it wrong? To have better error, we should check whether we are talking about folders, files, or mixed. In that case, I'm checking whether there's at least one folder selected, in which case I talk about folders, otherwise about files. I think the error are half wrong then.

2021-07-15 20:50 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/MoveFileModal.tsx
> +      const currentPathWithFolder = `${currentPath}/${folder.name}`
Thanks a lot, it's def. the way to go and solves Andres's problem from what I can see.

2021-07-15 23:00 UTC, asnaith commented
Top level seems good now, I cannot move a parent into a child folder or itself. 

I've found a couple more issues related to this still with child folders. You can cause a child folder to become unreachable in two scenarios

- When moving it into the parent folder that it is already in 
- When when moving it to itself

Can we show the same error when trying to move child folders in this way too?

2021-07-16 08:32 UTC, Tbaut commented
>    When moving it into the parent folder that it is already in
    When when moving it to itself

I can't reproduce this, it's not allowed for me. Can you do another round of check @tanmoyAtb and @FSM1 when you have the chance? I'd love to get to the bottom of it today :)

Here's what I'm testing, at the root, and in a subfolders, and it looks good.

https://user-images.githubusercontent.com/33178835/125917900-add45f06-d037-48ab-88af-2569583f2adc.mp4

2021-07-16 09:46 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/MoveFileModal.tsx
> +              folders.length
You're right, this change is not needed as I think about it now,
I was going for `The files are already in this folder`, when you have folders selected,
but `You can't move into this folder` works for me.

2021-07-16 10:06 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/MoveFileModal.tsx
> +              folders.length
Now i feel whats going on here, And the change is not needed.
I was going for `The files are already in this folder` even for folder,
but `You can't move into this folder` works just fine!

2021-07-16 10:08 UTC, tanmoyAtb commented
For me both of these cases are working as expected,
I'm not allowed to,
- move into one's parent folder
- move onto itself

2021-07-16 10:09 UTC, tanmoyAtb approved these changes
Tested out all the cases I could think of,
working for me 💯

2021-07-16 10:56 UTC, FSM1 approved these changes
Also tested all the scenarios I could think of and seem unable to break it 🎉

2021-07-16 10:56 UTC, merged