create and edit shared folder modals merge
ChainSafe/files-ui pull request #1353
Opened 2021-07-27 15:03 UTC by tanmoyAtb

closes #1279

2021-07-27 15:43 UTC, Tbaut requested changes
I started reviewing but quickly realized that we're duplicating here a lot of logic that was extracted in `useCreateSharedFolder` and `useLookupUser` explicitly for this purpose. We should reuse them. edit: take a look at the file that got deleted here, `CreateSharedFolderModal` was using them.

Also while I tested the functionality to create a shared folder, I found out about the following
- type in a user "abc" as reader
- type in a user "abc" as writer
- the "reader" is automatically removed and a text appear.
- I didn't realize it wasn't added at all

We should not make choices for our users. Instead we should have the "create" button disabled, and the error text say `User "abc" (maybe truncated) cannot be added both as reader and writer`. And let our user chose where this one should go.

2021-07-27 15:43 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
>          bucket={bucketToEdit}
Could we name it "bucketToEdit"?

2021-07-27 15:43 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
>              <Button variant='outline'
new line

2021-07-27 15:43 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx
> +  mode?: "create" | "edit"
100% bonus to prevent duplication, we could have some fancy typescript, without going too crazy.
```
// exported in SharedFoldersOverview.tsx
export type = SharedFolderModalMode = "create" | "edit" | undefined

// imported here and used on this line
mode: Exclude<SharedFolderModalMode, undefined>
```

2021-07-27 15:44 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
>              <Button variant='outline'
variant should be on a new line (I can't suggest because it's not an edited line)

2021-07-28 10:21 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx
> +  mode?: "create" | "edit"
Placed the types in the types file!

2021-07-28 13:39 UTC, FSM1 approved these changes
works great 💯

2021-07-28 13:43 UTC, tanmoyAtb commented
> I started reviewing but quickly realized that we're duplicating here a lot of logic that was extracted in `useCreateSharedFolder` and `useLookupUser` explicitly for this purpose. We should reuse them. edit: take a look at the file that got deleted here, `CreateSharedFolderModal.tsx` was using them.
> 
> Also while I tested the functionality to create a shared folder, I found out about the following
> 
> * type in a user "abc" as reader
> * type in a user "abc" as writer
> * the "reader" is automatically removed and a text appears.
> * I didn't realize this user was removed right away
> 
> We should not make choices for our users. Instead we should have the "create" button disabled, and the error text say `User "abc" (maybe truncated) cannot be added both as reader and writer`. And let our user chose where this one should go.

Okay, so we have updates on checking the error on intersecting users. 
I made a number of changes to reuse `useLookupUser` and `useCreateOrEditSharedFolder`. 

So this PR would effect creating shared folder, update permissions and copy to shared folder.

2021-07-29 14:58 UTC, Tbaut requested changes
There a lot of serioulsy good things in there, the mix of `.filter` and `.some` is :exploding_head: 
Found a couple nits while looking at the code, will play with it now.

2021-07-29 14:58 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useLookupUser.tsx
> +      if (!result) return []
duplicate
```suggestion
```

2021-07-29 14:58 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useLookupUser.tsx
> +} from "@chainsafe/common-components"
nit
```suggestion
import { ITagOption, ITagValueType } from "@chainsafe/common-components"
```

2021-07-29 14:58 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useLookupUser.tsx
> +      const currentUsers = Array.isArray(usersList) ? usersList.map(su => su.value) : []
No need to check if it's an array, the type indicated that it must be.
```suggestion
      const currentUsers = usersList.map((su) => su.value)
```

2021-07-29 14:58 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useLookupUser.tsx
> +      if (currentUsers.includes(result.uuid) || result.uuid === profile?.userId) return []
Also duplicated
```suggestion
```

2021-07-29 14:58 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useLookupUser.tsx
> +  const [hasPermissionsChanged, setHasPermissionsChanged] = useState(false)
I wonder if this needs to be here. This seems to be related to a form that should be checked with dirtiness.
edit: After a check, unless I'm mistaken, it's only used in the `CreateOrEdit..Modal.tsx`, and should be added to the `TagsInput` onChange props..

2021-07-29 14:58 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useLookupUser.tsx
> +  const onNewReaders = (val: ITagValueType<ITagOption, true>) => {
onNewReaders and onNewWriters are super similar, what do you think about unifying them and have an additional `permission` parameter, just like the handleLookUp?

2021-07-29 14:58 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx
>        .then(handleClose)
```suggestion
      .catch(console.error)
      .finally(handleClose)
```

2021-07-29 14:58 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx
> +      .then(handleClose)
```suggestion
      .catch(console.error)
      .finally(handleClose)
```

2021-07-29 15:24 UTC, Tbaut commented
We should check with https://github.com/ChainSafe/ui-monorepo/pull/1356 this is going to conflict (I checked the dark mode and it doesn't adapt well indeed)

2021-07-31 18:03 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useLookupUser.tsx
> +  const [hasPermissionsChanged, setHasPermissionsChanged] = useState(false)
Yeap, moved the logic back into `createOrEdit..` file!

2021-07-31 18:04 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useLookupUser.tsx
> +  const onNewReaders = (val: ITagValueType<ITagOption, true>) => {
Yes! merged the functions into one!

2021-07-31 18:09 UTC, tanmoyAtb commented
> We should check with #1356 this is going to conflict (I checked the dark mode and it doesn't adapt well indeed)

going to wait till the dark mode comes through! going to be quite some conflicts !

2021-07-31 18:33 UTC, tanmoyAtb commented
So looks like we're good to go with the merge with dark mode components!
Removed a couple of warnings in the PR!

2021-08-02 10:27 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useLookupUser.tsx
> +      const currentUsers = Array.isArray(usersList) ? usersList.map(su => su.value) : []
you forgot about this one, committing it now.

2021-08-02 11:34 UTC, Tbaut approved these changes
I've removed the external `setSharedFolderWriters` and writers because these were redundant with the `setNewUsers`. Moved the logic to check for errors in a `useEffect` and added a `useCallback` to avoid infinite loop. 

I've tested it as much as I could and it looked good.

2021-08-02 11:34 UTC, merged