Added filtering for filesystem type
ChainSafe/files-ui pull request #1360
Opened 2021-07-27 19:44 UTC by RyRy79261

closes #1354

2021-07-28 10:17 UTC, Tbaut requested changes
We're doing quite some props drilling. Could we get the file system type directly where we use it? I'm thinking about a small `useIsIPFSFileSystem` custom hook hat would get the current bucket, and return `fileSystemType === "ipfs"` (a boolean), and use this directly where it's needed. What do you think?

2021-07-28 13:53 UTC, FSM1 approved these changes
While the prop drilling isn't ideal, I dont feel that adding an extra hook is right here either. Could the value not be retrieved from the useFileBrowser `bucket` property?

Either case, I think given the mass of props already being passed down, one more in this case should not hurt too much.

2021-07-28 14:00 UTC, Tbaut commented
Absolutely, the context is there, let's use it and prevent those walls of props.
I am always a little afraid to see that we copy/paste and generally duplicate more than we should, but I agree that for this one a custom hook is more the sugar on the cake.

2021-07-28 15:17 UTC, RyRy79261 commented
Yeah the main idea avoiding using a hook since it felt like adding another method of getting variables in addition to the brick wall of props was more inconsistent. Can swap to the hook if preferred

2021-07-29 13:55 UTC, Tbaut commented on packages/storage-ui/src/Contexts/FileBrowserContext.tsx
> +  fileSystemType: FileSystemType | undefined
This can be removed
```suggestion
```

2021-07-29 13:56 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/BucketPage.tsx
> +      fileSystemType: bucket?.file_system_type
And this one too.
```suggestion
```

2021-07-29 13:59 UTC, Tbaut approved these changes
looks :100:

2021-07-29 13:59 UTC, merged