Using default cursors
ChainSafe/files-ui pull request #1411
Opened 2021-08-04 18:48 UTC by tanmoyAtb

closes #1408

2021-08-05 00:14 UTC, asnaith commented
Hey Tanmoy, this looks good in macOS Chrome & Firefox, can see that the cursor is an arrow now when hovering over a folder. It only changes to a pointer when hovering over a checkbox or kebab menu icon which makes sense 🙂

This should reduce some confusion but still might not appease the users who don't like the double click. 

A suggestion that might be out of the context of this PR (cc @sweetpea22) - perhaps we could consider adding a pointer when hovering over the folder name and making the folder name itself a single click to enter the folder? We can keep the double click if a user is hovering on the row. This is how OneDrive behaves.

2021-08-05 11:29 UTC, Tbaut commented
@asnaith and @sweetpea22 I agree, let's continue the conversation in #1415

2021-08-05 11:36 UTC, Tbaut requested changes
Working well but I think the implementation can be changed to solve the ground problem rather than overriding it.

2021-08-05 11:36 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
> +      cursor: "default",
Rather than overriding the cursor here, I'd make sure the original behavior is not to have a `cursor: pointer`, from what I could see, it's in `/packages/common-components/src/Table/TableRow.tsx`

2021-08-05 13:43 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
> +      cursor: "default",
Yeah I thought about this too! will update!

2021-08-05 14:10 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
> +      cursor: "default",
Looks like we already had a prop to handle the cursor! 🗡️

2021-08-05 14:12 UTC, tanmoyAtb commented
> Hey Tanmoy, this looks good in macOS Chrome & Firefox, can see that the cursor is an arrow now when hovering over a folder. It only changes to a pointer when hovering over a checkbox or kebab menu icon which makes sense 🙂
> 
> This should reduce some confusion but still might not appease the users who don't like the double click.
> 
> A suggestion that might be out of the context of this PR - perhaps we could consider adding a pointer when hovering over the folder name and making the folder name itself a single click to enter the folder? We can keep the double click if a user is hovering on the row. This is how folder navigation works in OneDrive but the current way is more similar to Google Drive. (cc @sweetpea22)

Yes makes sense! The UX you suggested is also used by dropbox. Will continue in #1415

2021-08-05 15:09 UTC, Tbaut approved these changes
:100:

2021-08-05 16:29 UTC, asnaith approved these changes

2021-08-05 18:51 UTC, RyRy79261 commented on packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
> -        rowSelectable={true}
Dont we still want the rows selectable just with different cursors?

2021-08-06 11:05 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
> -        rowSelectable={true}
The `selectable` prop from what I could see only changed the cursor and allows an "onClick" prop that we don't use anyway. So having it to false doesn't seem to change the behavior and actually just acts on the cursor for us, which is nice.

2021-08-06 11:09 UTC, merged