Expose decryption key
ChainSafe/files-ui pull request #1426
Opened 2021-08-06 14:29 UTC by RyRy79261

closes #1392

2021-08-09 11:47 UTC, Tbaut requested changes
Nice, works well. I left some comments to get a better readability.
Also idk if you saw but @FSM1 already added an eye icon for the api keys for storage in the past, it's not used any more but the eye (at least the open one) is still there.

2021-08-09 11:47 UTC, Tbaut commented on packages/common-components/src/ToggleHiddenText/ToggleHiddenText.tsx
> +const loop = (count: number) => {
We can replace this by placing `new Array(hiddenLength).fill("●")` inside the `ToggleHiddenText`
Maybe inside a useMemo to prevent re-render.

2021-08-09 11:47 UTC, Tbaut commented on packages/common-components/src/ToggleHiddenText/ToggleHiddenText.tsx
> +const ToggleHiddenText: React.FC<IToggleHiddenText> = ({
nit, redundant
```suggestion
const ToggleHiddenText = ({
```

2021-08-09 11:47 UTC, Tbaut commented on packages/common-components/src/ToggleHiddenText/ToggleHiddenText.tsx
> +          ? iconPosition === "left" ? (
This condition makes it very verbose and hard to read, what do you think about removing it?
```
        hidden
          ? (
            {iconPosition === "left" && <EyeComponent/>}
              <span>{ loop(hiddenLength) }</span>
            {iconPosition === "right" && <EyeComponent/>}
          )
```

2021-08-09 11:47 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/FileInfoModal.tsx
> +                      </span>
nit
```suggestion
                      <span>{ personalEncryptionKey }</span>
```

2021-08-09 11:47 UTC, Tbaut commented on packages/common-components/src/ToggleHiddenText/ToggleHiddenText.tsx
> +              }
```suggestion
              { children }
```

2021-08-09 11:47 UTC, Tbaut commented on packages/common-components/src/ToggleHiddenText/ToggleHiddenText.tsx
> +              }
```suggestion
              { children }
```

2021-08-09 17:12 UTC, asnaith commented on packages/files-ui/src/Components/Modules/FileBrowsers/FileInfoModal.tsx
> +                      <Trans>Decryption key:</Trans>
nit (none of the other subtitles have a colon on the modal)

```suggestion
                      <Trans>Decryption key</Trans>
```

2021-08-10 09:50 UTC, RyRy79261 commented on packages/common-components/src/ToggleHiddenText/ToggleHiddenText.tsx
> +const loop = (count: number) => {
Ahh knew there was a smoother way will update

Regarding the eye icon, I used an existing one however it did have fixed colors so I removed the hardcoded stroke prop

2021-08-10 09:51 UTC, RyRy79261 commented on packages/common-components/src/ToggleHiddenText/ToggleHiddenText.tsx
> +          ? iconPosition === "left" ? (
Yeah was grating me as well, thanks!

2021-08-10 09:52 UTC, Tbaut commented on packages/common-components/src/ToggleHiddenText/ToggleHiddenText.tsx
> +const loop = (count: number) => {
aaah you're right, that's great, I missed it

2021-08-10 11:33 UTC, Tbaut approved these changes
:+1:

2021-08-10 14:13 UTC, FSM1 approved these changes

2021-08-10 14:37 UTC, merged