Use material dropdown
ChainSafe/files-ui pull request #1432
Opened 2021-08-10 17:01 UTC by Tbaut

closes https://github.com/ChainSafe/ui-monorepo/issues/1285

As discussed in the UI meeting, here's a trial at integrating bit by bit some elements of material UI so that we don't have to re-invent the wheel for all we build. I didn't change all the dropdowns just yet because I wanted to submit this PR early on to get feedback.

https://user-images.githubusercontent.com/33178835/128902427-1edc01e4-9213-4300-be79-4a10c1bf72fc.mp4

2021-08-12 13:26 UTC, Tbaut commented
The `onBlur` on the rename input created problems again, so I decided to replace it by a transparent div component behind the edition field with a click handler to close it.

Tests are now passing and dark mode is handled.

2021-08-16 18:59 UTC, tanmoyAtb approved these changes
Not sure if we had any discussion about adding material into the mix,
but moving forward we should have a discussion around how we work with the component library!

2021-08-16 18:59 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
> +    clickOutSideArea : {
I see what its doing, 
but could we not use the `useOnClickOutside` ref system to catch the click outside ?

2021-08-16 19:00 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
> +    clickOutSideArea : {
we have a `useOnClickOutside` hook in the `common/theme`

2021-08-16 19:03 UTC, tanmoyAtb requested changes

2021-08-16 19:03 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
>        [breakpoints.down("md")]: {
The dropdown on the Grid items has not been worked on!

2021-08-17 08:52 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
>        [breakpoints.down("md")]: {
Thanks Tanmoy, I wanted to have feedback as early as possible and finish off the other (that's int he todo). I'll make sure to update this one.

2021-08-17 08:52 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
> +    clickOutSideArea : {
aah thanks, I didn't know about this one, will take a look.

2021-08-17 08:59 UTC, Tbaut commented
> Not sure if we had any discussion about adding material into the mix,
but moving forward we should have a discussion around how we work with the component library!

We had a discussion indeed. At the end of the day, we think we shouldn't re-invent the wheel and spend a ton of time building our own component library when there are so many good ones out there. We've already spent a lot of time doing these, so there's a bias in changing our path now, but the maintenance also takes some time. The good part is: we can do it step by step. This dropdown issue was a good one to start with and bit by bit change most of other components as we need them by slightly customizing the material ones to our look and feel.

I added a new UI-component folder in Files, maybe I should do this in the common component package, in a separate folder :man_shrugging:

2021-08-17 15:53 UTC, tanmoyAtb approved these changes
Looks good to go :)

2021-08-17 16:02 UTC, Tbaut commented
I still have the mobile menu to do, and I'll create a new issue for the proper dropdowns (or maybe not for now :shrug` ?) that are used in the header with the username and the settings>languages

2021-08-19 09:05 UTC, FSM1 approved these changes
working really nicely

2021-08-19 13:18 UTC, merged