Copy cid functionality added, overflow issue still present
ChainSafe/files-ui pull request #1437
Opened 2021-08-11 21:49 UTC by RyRy79261

closes #1431

The issue that was fixed in a previous PR that was reverted is still present: https://github.com/ChainSafe/ui-monorepo/pull/1424#issuecomment-896099344

![image](https://user-images.githubusercontent.com/10461622/129107787-87fcc3c8-c5e9-477f-a4bc-051bde107dd8.png)

2021-08-12 09:25 UTC, Tbaut requested changes
Nice, just there's no indication that clicking on the CID will copy it. Can we have a button (with the copy icon) right from the CID as suggested in the issue?

2021-08-16 19:11 UTC, tanmoyAtb commented
I feel something like what we have in the settings will look better here !

<img width="490" alt="Screenshot 2021-08-17 at 1 11 12 AM" src="https://user-images.githubusercontent.com/10713353/129617048-a140e870-a821-481a-ae3c-450a9a616a0d.png">

2021-08-16 19:26 UTC, RyRy79261 commented
@tanmoyAtb The ticket specified a button and we dont specifically know the space requirements so cant use the center ellipsis function, previous efforts to use overflow ellipsis weren't accepted so not sure about changing from the button at this point

2021-08-17 08:15 UTC, Tbaut commented
I think it's all a matter of how useful something is for users.
- A truncated cid that you can't copy is useless.
- A full cid that you can't select (hence can't copy) is almost useless.
^ we have had both in the past and were not happy about it.

Now in my opinion:
- A full cid that you can't select but you can copy certainly works
- A truncated cid that you can copy also works IMHO.

What Tanmoy suggests is what I had in mind too when reading the ticket. A column named "CID" with just a button looks super weird, we could have have menu entriy if copying the CID without seeing it was a requirement.

2021-08-17 08:33 UTC, RyRy79261 commented
Ok, so we have variants of all of these so far, what should I build?

2021-08-17 08:49 UTC, Tbaut commented
I think what Tanmoy suggested [here](https://github.com/ChainSafe/ui-monorepo/pull/1437#issuecomment-899753243) is what @FSM1 talked about. The cid and a small copy button. If there's not enough space for the full cid, we can add the ellipsis without issue as well since users can still copy it.

2021-08-17 10:12 UTC, RyRy79261 commented
@Tbaut @tanmoyAtb 

So I've set a 200px limit for this as I couldn't find a way around the `fr` unit behaviour in the grid without needing to calculate the percentage the table takes up of the screen for `vw` based sizing. One thing that has been on my mind is where the `name` column's text is, everything else is centered so this table looks a bit weird to me 

![image](https://user-images.githubusercontent.com/10461622/129707662-2afccb33-0395-4ecb-89b1-5fb176fee763.png)

2021-08-17 15:46 UTC, tanmoyAtb commented
> @Tbaut @tanmoyAtb
> 
> So I've set a 200px limit for this as I couldn't find a way around the `fr` unit behaviour in the grid without needing to calculate the percentage the table takes up of the screen for `vw` based sizing. One thing that has been on my mind is where the `name` column's text is, everything else is centered so this table looks a bit weird to me
> 
> ![image](https://user-images.githubusercontent.com/10461622/129707662-2afccb33-0395-4ecb-89b1-5fb176fee763.png)

I would suggest: 
Make the header `Name` left aligned as the contents are left aligned,
and make the CID column content `center` aligned like the header.

2021-08-19 09:20 UTC, Tbaut commented
Even on my small screen the CID is being cut although there's still plenty of space for it to grow. Should we have a higher limit maybe?
![image](https://user-images.githubusercontent.com/33178835/130043518-1fd293b6-b9ea-41b2-a184-b8d63f29bcba.png)

2021-08-19 09:21 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
> +    // }
stray comment
```suggestion
```

2021-08-19 09:21 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
> +                        Copied!
```suggestion
                          Copied!
```

2021-08-19 09:34 UTC, FSM1 commented
> @Tbaut @tanmoyAtb
> 
> So I've set a 200px limit for this as I couldn't find a way around the `fr` unit behaviour in the grid without needing to calculate the percentage the table takes up of the screen for `vw` based sizing. One thing that has been on my mind is where the `name` column's text is, everything else is centered so this table looks a bit weird to me
> 
> ![image](https://user-images.githubusercontent.com/10461622/129707662-2afccb33-0395-4ecb-89b1-5fb176fee763.png)

Since the content of the column is limited to 200px, would it not make sense to define it in the grid spec as a 200px column?

`export const desktopGridSettings = "50px 69px 3fr 200px 100px 45px !important"`

2021-08-24 10:13 UTC, Tbaut commented
I've played a bit with `minmax` and came up with values to achieve that, I'll commit directly, feel free to revert, but having the full cid visible when there's space for it looks nicer IMHO.

https://user-images.githubusercontent.com/33178835/130599264-4f413b7c-1233-4c87-9c31-84f826b91b92.mp4

2021-08-24 10:14 UTC, Tbaut approved these changes

2021-08-24 10:17 UTC, Tbaut requested changes
It looks like something went wrong with the merge, there are many changes related to billing in this PR now :see_no_evil:

2021-08-24 10:32 UTC, Tbaut commented
I checked quickly, the unrelated code comes from c42cec5

2021-08-25 10:07 UTC, Tbaut approved these changes

2021-08-25 10:07 UTC, Tbaut commented on packages/files-ui/src/locales/de/messages.po
> +msgstr ""
```suggestion
msgstr "Essentials - Kostenlos"
```

2021-08-25 10:07 UTC, Tbaut commented on packages/files-ui/src/locales/es/messages.po
> +msgstr ""
```suggestion
msgstr "Esenciales - Gratis"
```

2021-08-25 10:07 UTC, Tbaut commented on packages/files-ui/src/locales/fr/messages.po
> +msgstr ""
```suggestion
msgstr "Essentials - Gratuit"
```

2021-08-25 10:09 UTC, Tbaut commented
I've reverted the problematic commit, let's merge this PR :rocket:

2021-08-25 12:00 UTC, FSM1 approved these changes
aww yuss <3

2021-08-25 12:02 UTC, merged