Unblock UI while sharing
ChainSafe/files-ui pull request #1441
Opened 2021-08-12 21:49 UTC by FSM1

Closes #1377

2021-08-16 10:08 UTC, Tbaut reviewed
Working very well :tada: 

Playing with it made me feel that the UX is a bit too simple for now, we should create issues to:
- tell what files are being moved, where
- allow to cancel the download/upload

2021-08-16 10:08 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/ShareToSharedFolderModal.tsx
> +  const [keepOriginalFile, setKeepOriginalFile] = useState(false)
Shouldn't we keep this true by default, to be safe?
```suggestion
  const [keepOriginalFile, setKeepOriginalFile] = useState(true)
```

2021-08-16 10:08 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/ShareToSharedFolderModal.tsx
> -  const [error, setError] = useState("")
Can we bring back the errors? I think they'd help us debug if something happens in the wild and users don't open the console.

2021-08-16 10:08 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/TransferProgressToast/TransferToast.tsx
> +        {complete ? (
mixing completion and error in several ternary operations make the code pretty hard to review.
Could we change this for things like:
```
{ !!error && (< SomeErrorElement />) }
{ !complete && (< SomeProgressElement />) }
{ complete && !error && (< SomeCompleteElement />) }
```

2021-08-16 10:08 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/TransferProgressToast/index.tsx
> +        (desktop || transfersInProgress.complete || transfersInProgress.error) && (
On mobile we don't show anything?

If we really want to keep it that way, then the `desktop` check should probably be in an early `if (!desktop) return`

2021-08-16 10:08 UTC, Tbaut commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +  transferFileBetweenBuckets: (
~Should we set that up for several files right away or is that too complex for a first step?~
Scratch that, I'll do it in https://github.com/ChainSafe/ui-monorepo/issues/1363

2021-08-16 10:08 UTC, Tbaut commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +            errorMessage: "An error occured while downloading the file"
translation and typo
```suggestion
            errorMessage: t`An error occurred while downloading the file`
```

2021-08-16 10:08 UTC, Tbaut commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +          errorMessage: `An error occured: ${error}`
translation and typo
```suggestion
          errorMessage: t`An error occurred: ${error}`
```

2021-08-16 10:08 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useCreateOrEditSharedFolder.tsx
> +      }).catch((error) => {
nit for consistency, I think it was fine as it was.
```suggestion
      })
      .catch((error) => {
```

2021-08-16 10:08 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/TransferProgressToast/TransferToast.tsx
> +  const { transferInProgress } = props
nit
```suggestion
const TransferToast: React.FC<ITransferToast> = ({ transferInProgress }) => {
```

2021-08-16 10:08 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/TransferProgressToast/TransferToast.tsx
> +        data-cy="upload-status-toast-message" >
```suggestion
      <div
        className={clsx(classes.appearBox, classes.boxContainer)}
        data-cy="upload-status-toast-message"
      >
```

2021-08-16 10:08 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/TransferProgressToast/index.tsx
> +} from "@chainsafe/common-theme"
nit
```suggestion
import { createStyles, ITheme, makeStyles, useThemeSwitcher } from "@chainsafe/common-theme"
```

2021-08-16 10:08 UTC, Tbaut commented on packages/files-ui/src/Contexts/FilesReducers.tsx
> +          action.payload.errorMessage
```suggestion
      transfersInProgress[progressIndex].errorMessage = action.payload.errorMessage
```

2021-08-16 10:08 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/TransferProgressToast/TransferToast.tsx
> +                Transferring your file ({operation})
The operation is a non translated string, so it will always appear in english. I guess it's not a big deal for now

2021-08-16 10:08 UTC, Tbaut commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +    keepOriginal = false
We should default to something safe
```suggestion
    keepOriginal = true
```

2021-08-16 23:27 UTC, asnaith commented
Working really well on desktop with the toast notifications.

In my opinion it does seem like a downgraded experience on **mobile** though by not showing anything at all. If the user went to check a shared folder whilst in process of sharing a large file to it then might lead to confusion if it's not there yet, with the blocked UI everyone know's for certain something is still in progress.

2021-08-17 13:23 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/FileBrowsers/ShareToSharedFolderModal.tsx
> -  const [error, setError] = useState("")
By the time an error occurs, the modal would be closed already, so there isn't really anywhere for it to be displayed.

2021-08-17 14:50 UTC, FSM1 commented
> Working really well on desktop with the toast notifications.
> 
> In my opinion it does seem like a downgraded experience on **mobile** though by not showing anything at all. If the user went to check a shared folder whilst in process of sharing a large file to it then might lead to confusion if it's not there yet, with the blocked UI everyone know's for certain something is still in progress.

I have enabled the transfer toast on mobile as well now.

2021-08-17 15:59 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/ShareToSharedFolderModal.tsx
> -  const [error, setError] = useState("")
Fair enough, I guess there are very few issues that can happen with the shared folder creation, couldn't find any that will happen often.

2021-08-17 16:09 UTC, tanmoyAtb requested changes
This is working great!

On UX level: I got this view of error when I tried to share file to shared folder that had a file with the same name. Just need to work on showing the error
<img width="479" alt="Screenshot 2021-08-17 at 10 02 59 PM" src="https://user-images.githubusercontent.com/10713353/129761103-6a5fe034-2203-4ee5-9204-3a33ff98a924.png">

Also, The word `Transferring` caught me off guard, I thought this was moving the file.
Can we just use `Sharing your file`.
(I really like the downloading -> encrypt and uploading progress texts!)

On a separate note:
If you navigate to the `Shared` page, while you're sharing a file, the progresses go away. 
Can we move the progress states higher to have them in all browsers. This can be a separate ticket

2021-08-17 16:41 UTC, asnaith commented
> I have enabled the transfer toast on mobile as well now.

On the mobile view I'm seeing the toast when the transfer is complete (or if it fails) now but nothing whilst it is in progress

2021-08-17 21:28 UTC, FSM1 commented
> > I have enabled the transfer toast on mobile as well now.
> 
> On the mobile view I'm seeing the toast when the transfer is complete (or if it fails) now but nothing whilst it is in progress

Hmm, seems to be working...
![image](https://user-images.githubusercontent.com/12774278/129803071-ac45b9f9-a4aa-4b7e-a607-ba29e0e6a235.png)

2021-08-17 21:39 UTC, asnaith commented
> Hmm, seems to be working...

👍 Yep, all working great now, seeing the modal whilst it's in progress now. Perhaps it was because I was testing it before a89a136.

2021-08-18 11:08 UTC, FSM1 commented
> This is working great!
> 
> On UX level: I got this view of error when I tried to share file to shared folder that had a file with the same name. Just need to work on showing the error
> <img alt="Screenshot 2021-08-17 at 10 02 59 PM" width="479" src="https://user-images.githubusercontent.com/10713353/129761103-6a5fe034-2203-4ee5-9204-3a33ff98a924.png">
> 
> Also, The word `Transferring` caught me off guard, I thought this was moving the file.
> Can we just use `Sharing your file`.
> (I really like the downloading -> encrypt and uploading progress texts!)
> 
> On a separate note:
> If you navigate to the `Shared` page, while you're sharing a file, the progresses go away.
> Can we move the progress states higher to have them in all browsers. This can be a separate ticket

I fixed all the error messages, updated the copy on the toast, and also moved the toast rendering up to the FilesContext level.

2021-08-19 08:39 UTC, Tbaut approved these changes

2021-08-19 13:35 UTC, RyRy79261 approved these changes

2021-08-19 14:27 UTC, tanmoyAtb approved these changes
Amazing work !

2021-08-19 14:36 UTC, merged