Adding multi selects on mobile view with long press
ChainSafe/files-ui pull request #1470
Opened 2021-08-24 19:11 UTC by tanmoyAtb

closes #1466

2021-08-27 03:09 UTC, asnaith commented
Hey Tanmoy, 

I see this is still a draft but thought I'd mention a couple of things as I checked it out. The multi-select is working nicely on mobile, I just noticed a few very minor quirks. 

- On the mobile list view after selecting and de-selecting multiple items it does not return all the rows to the colour that they were before they were selected. This is best observed by watching the two folders in the video below but it is hard to see at first glance. 

https://user-images.githubusercontent.com/3982665/131065008-6ddd42bb-62c2-47f4-adb2-8e0097f22957.mov

- Also on mobile, the light theme there's a blue border around multiple selected items but there's no blue border on the dark theme, I'm not sure which one is correct.

2021-08-29 19:03 UTC, tanmoyAtb commented
> Hey Tanmoy,
> 
> I see this is still a draft but thought I'd mention a couple of things as I checked it out. The multi-select is working nicely on mobile, I just noticed a few very minor quirks.
> 
> * On the mobile list view after selecting and de-selecting multiple items it does not return all the rows to the colour that they were before they were selected. This is best observed by watching the two folders in the video below but it is hard to see at first glance.
> 
>  RPReplay_Final1630032439.2.mov 
> * Also on mobile, the light theme there's a blue border around multiple selected items but there's no blue border on the dark theme, I'm not sure which one is correct.

Hey @asnaith I looked into the feedbacks! I fixed the dark mode issues!
I looked into the folders or rows selection color problem, It looks like the browser is treating long press as a hover and placing color there, The color goes away if you click somewhere else. 
I put in a fix to disable hovers for tablee rows on mobile. Things looks to be in order now :D

2021-08-30 12:23 UTC, RyRy79261 commented
@tanmoyAtb Not sure how to test this on desktop, though I noticed that the first item in a subfolder has a weird amount of spacing 
![image](https://user-images.githubusercontent.com/10461622/131338265-c3e80781-2e14-4d18-b003-3d8120803b2f.png)

2021-08-30 12:46 UTC, Tbaut requested changes
Nice one! Have you tried on a real device? When I test it on Firefox and enable the "touch simulation", it actually doesn't register the long click.

Also I've spoted an annoying behavior:
- The preview opens even if you click slightly below the menu button.
- If you click on the menu, it's opening the preview, and once you click to go back, and click outside to close the menu, the preview opens again. Here's a demo.


https://user-images.githubusercontent.com/33178835/131340939-f124c9e4-ab59-4b24-80fb-ef4b6e2b6c2a.mp4

2021-08-30 12:46 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
>        } ${t`deleted successfully`}`
```suggestion
      const message = `${itemToDelete.isFolder ? t`Folder` : t`File`} ${t`deleted successfully`}`
```

2021-08-30 12:46 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
>        }`
```suggestion
      const message = `${t`There was an error deleting this`} ${itemToDelete.isFolder ? t`folder` : t`file`}`
```

2021-08-30 12:46 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
>            } ${t`recovered successfully`}`
```suggestion
          const message = `${itemToRestore.isFolder ? t`Folder` : t`File`} ${t`recovered successfully`}`
```

2021-08-30 12:46 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
>            }`
```suggestion
          const message = `${t`There was an error recovering this`} ${itemToRestore.isFolder ? t`folder` : t`file`}`
```

2021-08-30 12:46 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
> +
```suggestion
```

2021-08-30 12:46 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
> +
```suggestion
```

2021-08-30 12:46 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
> +    drop: (item: { ids: string[] }) => {
nice, it would be great to adjust eslint so that this is enforced and done automatically.

2021-08-30 12:46 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
> +    else {
```suggestion
    if (!desktop) {
      return null
    } else {
```

2021-08-30 12:46 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
> +        border: `1px solid ${constants.fileSystemItemRow.borderColor}`
Could we also add a transparent border when it's not highlighted, so that the row doesn't jump when selected?

2021-08-30 16:08 UTC, tanmoyAtb commented
> @tanmoyAtb Not sure how to test this on desktop, though I noticed that the first item in a subfolder has a weird amount of spacing
> ![image](https://user-images.githubusercontent.com/10461622/131338265-c3e80781-2e14-4d18-b003-3d8120803b2f.png)

So if you're talking about the spacing above, its there for buttons when you have an item selected, Without the spacing, the items would jump on selection!
We would pretty much have to test this PR on mobile size screens! It works on desktops on small widths

2021-08-30 16:09 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
> +        border: `1px solid ${constants.fileSystemItemRow.borderColor}`
Great idea! will look into it!

2021-08-31 08:17 UTC, RyRy79261 commented
Roger that, I tried the FF with touch simulation, will try it out on MM mobile

2021-08-31 14:33 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
> +    drop: (item: { ids: string[] }) => {
So I looked into the rules that does this, It comes from `object-curly-spacing`, there's also `typescript-eslint/object-curly spacing`. But for some reason, they are not working! 
Can you take a look when you have a moment!

2021-08-31 15:07 UTC, tanmoyAtb commented
> Nice one! Have you tried on a real device? When I test it on Firefox and enable the "touch simulation", it actually doesn't register the long click.
> 
> Also I've spoted an annoying behavior:
> 
> * The preview opens even if you click slightly below the menu button.
> * If you click on the menu, it's opening the preview, and once you click to go back, and click outside to close the menu, the preview opens again. Here's a demo.
> 
>  Menu-click.mp4

Hey, I've fixed the issue with the menu click!
I've tested the functionalities on real device and FF touch simulation, It works for me!

2021-08-31 16:55 UTC, Tbaut commented
Nice, I've tested it on a real device, and there's an issue with the drag and drop, I guess we need to deactivate it.
What I did is just long press on a file, and this brings the dad overview in the middle, and it stays there! I'm on Android 11 (latest) with Chrome. 
![image](https://user-images.githubusercontent.com/33178835/131544515-822f177d-cf14-40bf-bf94-665d6196440a.png)

2021-09-01 03:54 UTC, asnaith commented
Multi-select is working great for me on desktop and iPhone 12 Mini in both list and grid layout. 

On iOS I can't invoke drag and drop - but that's also the same on stage / prod as it's not possible to select a file at all without these changes.

2021-09-01 11:37 UTC, tanmoyAtb commented
> Nice, I've tested it on a real device, and there's an issue with the drag and drop, I guess we need to deactivate it.
> What I did is just long press on a file, and this brings the dad overview in the middle, and it stays there! I'm on Android 11 (latest) with Chrome.
> ![image](https://user-images.githubusercontent.com/33178835/131544515-822f177d-cf14-40bf-bf94-665d6196440a.png)

Hmm this is weird! Looking into it !

2021-09-02 10:41 UTC, Tbaut approved these changes
awesome work Tanmoy!

2021-09-02 16:33 UTC, asnaith approved these changes

2021-09-03 11:08 UTC, merged