Sharing feature explainer
ChainSafe/files-ui pull request #1477
Opened 2021-08-26 16:10 UTC by Tbaut

closes https://github.com/ChainSafe/ui-monorepo/issues/1361

2021-08-26 23:55 UTC, asnaith commented
This is working really well. Found a tiny micro issue with the username text not being very legible in the last card in dark mode. 

<img width="410" alt="Screen Shot 2021-08-26 at 4 46 10 PM" src="https://user-images.githubusercontent.com/3982665/131050128-d9c9889e-fd44-4639-941f-d2406201d99d.png">

There's a compilation issue in the CustomModal.tsx for storage-ui that is causing the storage test failures.

2021-08-27 03:12 UTC, asnaith commented
...and I only just noticed this was a draft 🤦‍♂️

2021-08-27 06:54 UTC, Tbaut commented
Hehe yeah I'm not done yet, I checked with Cindy to make this looks good on dark mode. Also I'll need to make it appear when clicking on "share" .

2021-08-31 15:40 UTC, Tbaut commented
oops need to fix storage too.

2021-09-01 03:13 UTC, asnaith approved these changes

2021-09-01 12:31 UTC, tanmoyAtb requested changes, later dismissed
This is dope!
The refactors are amazing too!

I left a couple of comments!
The modal on mobile screen needs to bee centered!

<img width="690" alt="Screenshot 2021-09-01 at 6 14 55 PM" src="https://user-images.githubusercontent.com/10713353/131671413-28fb883c-86d7-4b60-b72a-d3d6e48d7e1e.png">

2021-09-01 12:31 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useSharingExplainerModalFlag.tsx
> +  useEffect(() => {
we can combine these `useEffects` into one !

2021-09-01 12:31 UTC, tanmoyAtb commented on packages/files-ui/src/Components/SharingExplainerModal.tsx
> +export const DISMISSED_SHARING_EXPLAINER_KEY = "csf.dismissedSharingExplainer"
This should be imported from the `useSharingExplainerModalFlag`

2021-09-01 13:12 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useSharingExplainerModalFlag.tsx
> +  useEffect(() => {
absolutely, thanks.

2021-09-01 13:21 UTC, Tbaut commented on packages/files-ui/src/Components/SharingExplainerModal.tsx
> +export const DISMISSED_SHARING_EXPLAINER_KEY = "csf.dismissedSharingExplainer"
oh nice catch, refactor gone wrong.

2021-09-01 13:49 UTC, Tbaut commented
I had seen the modal being brought down on Mobile, but since I didn't introduce this, I closed my eyes and thoughts it's a feature or something. Checking it, I realized that it is indeed a feature, but only for some specific actions such as rename, moving etc. I adapted the modal I saw to not have this behavior (the Sharing modal for instance should be brought down etc..)

2021-09-02 13:37 UTC, FSM1 requested changes
Working great and looks fantastic.

Just need to remove the dependency on local storage for this, and leverage the API endpoints defined in https://github.com/ChainSafe/files-api-spec/pull/110/ to read and store this data.

I would also probably not use a separate hook for this, but rather keep this flag data on the user context that already exists.

2021-09-02 13:59 UTC, Tbaut commented
Given that the api PR is still open, https://github.com/ChainSafe/files-api/pull/1427
I thought we could go on with this and refactor later when the api is actually merged.

2021-09-02 14:28 UTC, FSM1 approved these changes

2021-09-02 14:45 UTC, merged