Billing history
ChainSafe/files-ui pull request #1492
Opened 2021-09-03 13:40 UTC by Tbaut

closes #1458

2021-10-26 17:51 UTC, tanmoyAtb requested changes
Some notes on UI - 

- I would like the loading to show up in the middle.
- When there are no invoices we should show "No invoices"
- Got this warning because the loading is under `tbody`
<img width="485" alt="Screenshot 2021-10-26 at 11 47 49 PM" src="https://user-images.githubusercontent.com/10713353/138933200-5d6c6979-cfcf-44ad-868b-9d776c97bda5.png">

I didn't get any invoices back with the `subscription_id` in the comment. maybe the API
does a mapping with user_id when returning invoices. !

2021-10-26 17:51 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Pages/BillingHistory.tsx
> +
```suggestion
```

2021-10-26 17:51 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Pages/BillingHistory.tsx
> +
```suggestion
```

2021-10-26 17:51 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Pages/BillingHistory.tsx
> +              <TableCell align="left">{paid_on ? dayjs.unix(paid_on as unknown as number).format("DD MMM YYYY") : "unknown"}</TableCell>
I see that the `paid_on` is Date type,
shouldn't this work ? 
`dayjs(paid_on)`

2021-10-27 17:28 UTC, Tbaut commented on packages/files-ui/src/Components/Pages/BillingHistory.tsx
> +              <TableCell align="left">{paid_on ? dayjs.unix(paid_on as unknown as number).format("DD MMM YYYY") : "unknown"}</TableCell>
nice catch, I didn't go over this code again, it used to be something else.

2021-10-27 17:31 UTC, Tbaut commented
> I didn't get any invoices back with the subscription_id in the comment. maybe the API
does a mapping with user_id when returning invoices. !

Ah that's annoying, could you check what subscription id you have and ask Arun to add some invoices to you?

The rest should be addresses.

2021-11-03 18:15 UTC, tanmoyAtb approved these changes
Looks good to go 👍 

The mobile view could get some adjustments, with the top padding and table cells.
<img width="414" alt="Screenshot 2021-11-04 at 12 14 22 AM" src="https://user-images.githubusercontent.com/10713353/140168699-750b5702-beef-4c03-94a2-263671eae830.png">

2021-11-04 10:00 UTC, Tbaut commented
good point @tanmoyAtb, I added some padding.

2021-11-04 10:34 UTC, FSM1 approved these changes

2021-11-04 10:41 UTC, merged