Feat/toasts refactor 1465
ChainSafe/files-ui pull request #1495
Opened 2021-09-03 19:50 UTC by tanmoyAtb

closes #1465 

Created #1494 for cancellation operations.

2021-09-03 19:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/ui-monorepo?pullRequest=1495) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/ui-monorepo?pullRequest=1495) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: tanmoyAtb<br/>:x: actions-user<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/ui-monorepo?pullRequest=1495) it.</sub>

2021-09-06 08:23 UTC, RyRy79261 approved these changes
Just want to confirm that the toast for File-ui is meant to be at the top right, otherwise left some comments for consideration

2021-09-06 08:23 UTC, RyRy79261 commented on packages/common-components/src/Toasts/ToastContent.tsx
> +      position: "relative",
@tanmoyAtb  We'll just need some theming override classes added to the common themes for these please :)

2021-09-06 08:23 UTC, RyRy79261 commented on packages/common-components/src/Toasts/ToastContent.tsx
> +      right: "-8px",
Just to consider, since this is half the size, you could set right n top to 0 and use `transform: translate(-50%,-50%)` and use `constants.generalUnit * 2` for the height n width, then for the svg `constants.generalUnit` 

This would make it shift with a standard value or alternatively a specific constant for the close icon settings

2021-09-06 08:23 UTC, RyRy79261 commented on packages/common-components/src/Toasts/ToastContext.tsx
> +      from: { transform: "translate(-100%)" },
Just a note on practice here, if you aren't making use of one of the short hand fields, you've effectively made it incompatible with animations that might need that property, so I'd recommend setting this to `translateY(-100%)` to prevent collisions

2021-09-06 08:23 UTC, RyRy79261 commented on packages/common-components/src/index.ts
> +// export * from "./Toaster"
```suggestion
```

2021-09-06 08:23 UTC, RyRy79261 commented on packages/common-components/src/index.ts
> +// export * from "./Toaster"
Assuming that the toaster is not gonna be used again, I'd removed it entirely, can retrieve from the commit prior to this PR if needed

2021-09-06 13:21 UTC, tanmoyAtb commented on packages/common-components/src/Toasts/ToastContent.tsx
> +      position: "relative",
Ahh yes, forgot about those !

2021-09-06 15:17 UTC, FSM1 commented
Something in the new theme file seems to be breaking the tests
![File management -- desktop -- can addremove multiple files and upload (failed)](https://user-images.githubusercontent.com/12774278/132237941-be3361dc-95b3-4428-9523-3c8339709dea.png)

2021-09-06 20:52 UTC, FSM1 approved these changes
Some minor Type improvements, that I left suggestions for, but otherwise stellar work 🥇

2021-09-06 20:52 UTC, FSM1 commented on packages/common-components/src/Toasts/types.ts
> +export type ToastPosition = "top-left" | "top-right" | "bottom-left" | "bottom-right"
```suggestion
export type ToastPosition = "topLeft" | "topRight" | "bottomLeft" | "bottomRight"
```

2021-09-06 20:52 UTC, FSM1 commented on packages/common-components/src/Toasts/ToastContext.tsx
> +  defaultPosition = "top-right",
```suggestion
  defaultPosition = "topRight",
```

2021-09-06 20:52 UTC, FSM1 commented on packages/common-components/src/Toasts/ToastContext.tsx
> +              >
Updates types, variable names
  
  ```suggestion
const positionedToasts: Record<ToastPosition, Array<Toast>> = useMemo(() => ({
    topRight: toasts.filter((toast) => toast.toastPosition === "topRight"),
    topLeft: toasts.filter((toast) => toast.toastPosition === "topLeft"),
    bottomRight: toasts.filter((toast) => toast.toastPosition === "bottomRight"),
    bottomLeft: toasts.filter((toast) => toast.toastPosition === "bottomLeft"),
  }), [toasts])
  return (
    <ToastContext.Provider
      value={{
        addToast,
        updateToast,
        removeToast,
        toasts
      }}
    >
      {(Object.keys(positionedToasts) as ToastPosition[]).map((position) => (
        !!positionedToasts[position].length && (
          <div
            key={position}
            className={clsx(
              classes.toastWrapper,
              classes[`${position}Container`]
            )}
          >
            {positionedToasts[position].map((toast) => (
              <div
                key={toast.id}
                className={classes[`${position}AppearBox`]}
              >
```

2021-09-06 20:52 UTC, FSM1 commented on packages/common-components/src/stories/Toasts.stories.tsx
> +          toastPosition: select("position", ["top-left", "top-right", "bottom-left", "bottom-right"], "top-right"),
```suggestion
          toastPosition: select("position", ["topLeft", "topRight", "bottomLeft", "bottomRight"], "topRight"),
```

2021-09-06 20:52 UTC, FSM1 commented on packages/common-components/src/stories/Toasts.stories.tsx
> +          toastPosition: select("position", ["top-left", "top-right", "bottom-left", "bottom-right"], "top-right"),
```suggestion
          toastPosition: select("position", ["topLeft", "topRight", "bottomLeft", "bottomRight"], "topRight"),
```

2021-09-06 20:52 UTC, FSM1 commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +      toastPosition: "bottom-right"
```suggestion
      toastPosition: "bottomRight"
```

2021-09-06 20:52 UTC, FSM1 commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +          toastPosition: "bottom-right"
```suggestion
          toastPosition: "bottomRight"
```

2021-09-06 20:52 UTC, FSM1 commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +        toastPosition: "bottom-right"
```suggestion
        toastPosition: "bottomRight"
```

2021-09-06 20:52 UTC, FSM1 commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +      toastPosition: "bottom-right"
```suggestion
      toastPosition: "bottomRight"
```

2021-09-06 20:54 UTC, FSM1 requested changes
Improved the types a bit, left some suggestions

2021-09-07 13:51 UTC, tanmoyAtb commented
> Improved the types a bit, left some suggestions

Updated all the types and got things linted :)

2021-09-08 01:31 UTC, asnaith commented
Hi Tanmoy, I pushed an update for the toast identifier. The tests are passing again now.

<img width="480" alt="Screen Shot 2021-09-07 at 5 57 45 PM" src="https://user-images.githubusercontent.com/3982665/132430687-97619210-e556-4d06-aa83-c7cb698e70c8.png">

2021-09-08 10:42 UTC, Tbaut reviewed
Wow such a great amount of goodness, really like it!
Fund a couple nits, but pretty much nothing compared to the size of this PR!
Just a note for another PR, File deletion and recovery toasts (and possibly others) are still at the top, which feels inconsistent to me.

2021-09-08 10:42 UTC, Tbaut commented on packages/common-components/src/Toasts/ToastContent.tsx
> +  onClose(): void
```suggestion
  onClose: () => void
```

2021-09-08 10:42 UTC, Tbaut commented on packages/common-components/src/Toasts/ToastContent.tsx
> +        ? <div>
is there any reason for the additionnal div here?

2021-09-08 10:42 UTC, Tbaut commented on packages/common-components/src/Toasts/ToastContent.tsx
> +        : <div>
Same question here regarding the div. Also there's some code duplication here (the whole title container, would be good to have this stored in a variable)

2021-09-08 10:42 UTC, Tbaut commented on packages/common-components/src/Toasts/ToastContext.tsx
> +    const shouldDismiss = toastParams.autoDismiss !== undefined ? toastParams.autoDismiss : autoDismiss
can use `toastParams.autoDismiss || autodismiss`
```suggestion
    const shouldDismiss = toastParams.autoDismiss || autoDismiss
```

2021-09-08 10:42 UTC, Tbaut commented on packages/common-components/src/Toasts/ToastContext.tsx
> +        setToasts((toasts) => toasts.filter((toast) => toast.id !== toastId))
you can call `removeToast` here instead.
```suggestion
        removeToast(toast.id)
```

2021-09-08 10:42 UTC, Tbaut commented on packages/common-components/src/Toasts/types.ts
> +  onProgressCancel?(): void
use `() => void` notation
```suggestion
  onProgressCancel?: () => void
```

2021-09-08 10:42 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
> +        title: "Folder uploads are not supported currently",
translation
```suggestion
        title: t`Folder uploads are not supported currently`,
```

2021-09-08 10:42 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
> +        title: "Folder uploads are not supported currently",
translation
```suggestion
        title: t`Folder uploads are not supported currently`,
```

2021-09-08 10:42 UTC, Tbaut commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +        title: t`Download failed`,
I wonder if we should give more info right away here. Also we should console.error the error.

2021-09-08 10:42 UTC, Tbaut commented on packages/common-components/src/Toasts/ToastContext.tsx
> +  removeToast(toastId: string): void
```suggestion
  addToast: (toastParams: ToastParams) => string
  updateToast: (toastId: string, toastParams: ToastParams, startDismissal?: boolean) => void
  removeToast: (toastId: string) => void
```

2021-09-08 10:42 UTC, Tbaut commented on packages/common-components/src/Toasts/ToastContext.tsx
> +)
nit
```suggestion
const ToastContext = React.createContext<ToastContext | undefined>(undefined)
```

2021-09-08 10:42 UTC, Tbaut commented on packages/common-components/src/stories/Toasts.stories.tsx
> +} from "../Toasts"
nit
```suggestion
import { ToastContent, ToastParams, ToastProvider, useToasts } from "../Toasts"
```

2021-09-08 10:42 UTC, Tbaut commented on packages/files-ui/cypress/support/page-objects/homePage.ts
> +  uploadStatusToast: () => cy.get("[data-testId=toast-upload-status]", { timeout: 10000 }),
I can't see this defined anywhere (I might have missed it). Ping me if you need any help on that, happy to give a hand.

2021-09-08 10:43 UTC, Tbaut commented on packages/files-ui/cypress/support/page-objects/homePage.ts
> +  uploadStatusToast: () => cy.get("[data-testId=toast-upload-status]", { timeout: 10000 }),
oh looks like Andrew got that sorted.

2021-09-08 12:01 UTC, FSM1 approved these changes

2021-09-08 17:26 UTC, tanmoyAtb commented
> Hi Tanmoy, I pushed an update for the toast identifier. The tests are passing again now.
> 
> <img alt="Screen Shot 2021-09-07 at 5 57 45 PM" width="480" src="https://user-images.githubusercontent.com/3982665/132430687-97619210-e556-4d06-aa83-c7cb698e70c8.png">

Thanks a lot for taking care of that @asnaith

2021-09-08 17:31 UTC, tanmoyAtb commented on packages/common-components/src/Toasts/ToastContent.tsx
> +        ? <div>
removed it !

2021-09-08 17:34 UTC, tanmoyAtb commented on packages/common-components/src/Toasts/ToastContent.tsx
> +        : <div>
Removed the extra div!
I did not get the part about titleContainer and duplication, can you elaborate ?

2021-09-08 17:42 UTC, tanmoyAtb commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +        title: t`Download failed`,
Added the console, and better info !

2021-09-08 17:46 UTC, tanmoyAtb commented on packages/common-components/src/Toasts/ToastContext.tsx
> +        setToasts((toasts) => toasts.filter((toast) => toast.id !== toastId))
Actually thats what I tried first!
But somehow the function keeps a reference of older toasts state from when it got initialized, and causes weird behaviour,
moved to this implementation later!

2021-09-08 17:47 UTC, tanmoyAtb commented
> Wow such a great amount of goodness, really like it!
> Found a couple nits, but pretty much nothing compared to the size of this PR!
> Just a note for another PR, File deletion and recovery toasts (and possibly others) are still at the top, which feels inconsistent to me.

Thanks for the amazing feedbacks!
I changed the default position to bottom right, All toasts in in place now.

2021-09-09 10:54 UTC, Tbaut commented on packages/common-components/src/Toasts/ToastContext.tsx
> +        setToasts((toasts) => toasts.filter((toast) => toast.id !== toastId))
ah ok interesting, the fact that `toast` is part of the dep array should prevent that. I'll take a closer look just for my information.

2021-09-09 11:08 UTC, Tbaut commented on packages/common-components/src/Toasts/ToastContext.tsx
> +        setToasts((toasts) => toasts.filter((toast) => toast.id !== toastId))
@tanmoyAtb, would you mind telling me in what case this happened?, I can't reproduce the problem you mentioned, I've monitored the call to `removeToast` for instance when I delete several files, or upload several files (not at the same time), and all the toasts get removed in the right order.

2021-09-09 11:09 UTC, Tbaut commented on packages/files-ui/src/App.tsx
> +            defaultPosition="bottomRight">
```suggestion
          <ToastProvider
            autoDismiss
            defaultPosition="bottomRight"
          >
```

2021-09-09 11:16 UTC, Tbaut commented on packages/common-components/src/Toasts/ToastContent.tsx
> +        : <div>
I thought there was some duplication with the `CheckCircleIcon` repeated for instance, and the `title` being common to both when there's a `progress` and when there isn't. But it's a nit and would maybe make the code more complex to read, so it's def. fine to leave it as is.

2021-09-09 15:53 UTC, tanmoyAtb commented on packages/common-components/src/Toasts/ToastContext.tsx
> +        setToasts((toasts) => toasts.filter((toast) => toast.id !== toastId))
hey @Tbaut, so try starting two uploads parallely, 
both toasts would get dismissed whenever the first toasts gets dismissed!

2021-09-09 16:12 UTC, Tbaut commented on packages/common-components/src/Toasts/ToastContext.tsx
> +        setToasts((toasts) => toasts.filter((toast) => toast.id !== toastId))
Yup that's what I did, and it's looking fine for me:

https://user-images.githubusercontent.com/33178835/132722698-7884b1e8-c5f2-4341-8c69-e341e1c830d5.mp4

2021-09-09 16:14 UTC, Tbaut commented on packages/common-components/src/Toasts/ToastContext.tsx
> +        setToasts((toasts) => toasts.filter((toast) => toast.id !== id))
I also replaced this one, and tested thoroughly, looking ok too. I'll check on brave.
```suggestion
        removeToast(id)
```

2021-09-09 16:19 UTC, Tbaut commented on packages/common-components/src/Toasts/ToastContext.tsx
> +        setToasts((toasts) => toasts.filter((toast) => toast.id !== id))
Tried with brave, and looks good.

2021-09-09 16:56 UTC, tanmoyAtb commented on packages/common-components/src/Toasts/ToastContext.tsx
> +        setToasts((toasts) => toasts.filter((toast) => toast.id !== toastId))
I think you might see the weird behaviour if you start uploads of similar size, where the startDismiss fires at close times!
In this recording, you can see toasts reappearing after uploads complete!

https://user-images.githubusercontent.com/10713353/132729395-a1c08678-6006-408c-868d-be178a3fad60.mov

2021-09-09 17:06 UTC, tanmoyAtb commented on packages/common-components/src/Toasts/ToastContext.tsx
> +        setToasts((toasts) => toasts.filter((toast) => toast.id !== id))
There is one more thing you can try to see the weird behaviour!
There is a `Toasts Demo` under toasts in storybook, try opening a number of toasts there

2021-09-10 09:11 UTC, Tbaut commented on packages/common-components/src/Toasts/ToastContext.tsx
> +        setToasts((toasts) => toasts.filter((toast) => toast.id !== toastId))
Thanks a lot, I got it, the sate that the `setTimeout` restores, is the one from a couple seconds ago, because of the closure. This is a very good example where we would actually need to have a `useRef` instead of `useState`. Allow me to hold this PR a couple more hours, for the sake of having behavior we 100% understand without duplication. I'll create a PR pointing to this one.

2021-09-10 09:26 UTC, Tbaut commented on packages/common-components/src/Toasts/ToastContext.tsx
> +        setToasts((toasts) => toasts.filter((toast) => toast.id !== toastId))
Ok here we go, I've submitted here: https://github.com/ChainSafe/ui-monorepo/pull/1513
Let me know what you think.
For more info about the closure thing, you can have a look here for instance https://github.com/facebook/react/issues/14010

2021-09-13 15:13 UTC, Tbaut commented
Please check https://github.com/ChainSafe/ui-monorepo/pull/1513 @tanmoyAtb it fixes my grumbles.

2021-09-13 15:32 UTC, tanmoyAtb commented
> Please check #1513 @tanmoyAtb it fixes my grumbles.

all on track now!

2021-09-13 15:34 UTC, Tbaut approved these changes
:tada: oh yeah, yet again an awesome one Tanmoy!

2021-09-13 15:36 UTC, merged