Don't track before opt-in
ChainSafe/files-ui pull request #1531
Opened 2021-09-16 11:14 UTC by Tbaut

2021-09-16 13:22 UTC, FSM1 requested changes

2021-09-16 13:22 UTC, FSM1 commented on packages/files-ui/src/Contexts/PosthogContext.tsx
> +    hasOptedIn && posthog.capture("$pageview")
I would still check that posthog is initialized here (were the ENV vars provided to this instance?) to prevent calling `.capture` on an uninitialized instance.

2021-09-16 13:22 UTC, FSM1 commented on packages/files-ui/src/Contexts/PosthogContext.tsx
> +  }, [pathname, hasOptedIn])
```suggestion
    posthogInitialized && hasOptedIn && posthog.capture("$pageview")
  }, [pathname, hasOptedIn, posthogInitialized ])
```

2021-09-16 13:40 UTC, FSM1 commented on packages/files-ui/src/Contexts/PosthogContext.tsx
> +  }, [pathname, hasOptedIn])
I would also hide the cookie banner if `posthogInitialized` is false

2021-09-16 13:47 UTC, Tbaut commented on packages/files-ui/src/Contexts/PosthogContext.tsx
> +  }, [pathname, hasOptedIn])
Agreed, I had to bring it back in the context value to be able to use it.

2021-09-16 21:00 UTC, FSM1 requested changes
Just the update to only show the cookie banner if posthog is initialized.

2021-09-16 21:00 UTC, FSM1 commented on packages/files-ui/src/Contexts/PosthogContext.tsx
> +  }, [hasTouchedCookieBanner, localStorageGet])
```suggestion
    if(posthogInitialized && !hasTouchedCookieBanner && localStorageGet(TOUCHED_COOKIE_BANNER_KEY) === "false"){
      setShowBanner(true)
    } else {
      setShowBanner(false)
    }
  }, [posthogInitialized, hasTouchedCookieBanner, localStorageGet])
```

2021-09-16 21:11 UTC, FSM1 approved these changes

2021-09-17 11:36 UTC, RyRy79261 approved these changes

2021-09-17 11:53 UTC, merged