Payments add card update with setup intent
ChainSafe/files-ui pull request #1584
Opened 2021-09-26 19:09 UTC by tanmoyAtb

closes #1524

2021-09-27 16:11 UTC, Tbaut commented
can you check @tanmoyAtb there are a couple conflicts with the last merge to the epic branch

2021-09-28 11:23 UTC, RyRy79261 reviewed
Looks rad! Is the `Current Card` section meant to display the cards yet?

2021-09-28 12:16 UTC, Tbaut reviewed
I found a couple nits, looks good otherwise

2021-09-28 12:16 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCardModal.tsx
> +    addToast({ title: "Failed to add payment method", type: "error" })
translation
```suggestion
    addToast({ title: t`Failed to add payment method`, type: "error" })
```

2021-09-28 12:16 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCardModal.tsx
> +  const handleSubmitPaymentMethod = async (event: any) => {
can we type this strictly?

2021-09-28 12:16 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCardModal.tsx
> +          borderColor: palette.primary.border
nit: 
can we change this border to be the "Files" blue?

2021-09-28 12:16 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCardModal.tsx
> +            onFocus={() => setFocusElement("number")}
this looks a little manual/hacky but I saw we're dealing with an iframe here, so not much else we can do I guess.

2021-09-28 12:16 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCardModal.tsx
> +              <Trans>Card inputs could not be validated</Trans>
Invalid card input
```suggestion
              <Trans>Card inputs invalid</Trans>
```

2021-09-28 12:16 UTC, Tbaut commented on packages/files-ui/src/Contexts/BillingContext.tsx
>        })
is that still needed? If yes this lacks error handling.

2021-09-28 12:16 UTC, Tbaut commented on packages/files-ui/src/Themes/DarkTheme.ts
> +          shadow: "0px 0px 4px rgba(24, 144, 255, 0.5)"
Could we use the File blue?

2021-09-28 12:16 UTC, Tbaut commented on packages/files-ui/src/Themes/LightTheme.ts
> +          shadow: "0px 0px 4px rgba(24, 144, 255, 0.5)"
same

2021-09-28 12:16 UTC, Tbaut commented on packages/files-ui/src/Contexts/BillingContext.tsx
> +  refreshDefaultCard(): void
```suggestion
  refreshDefaultCard: () => void
```

2021-09-28 14:01 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCardModal.tsx
>            data-cy="modal-create-folder"
```suggestion
          data-cy="modal-add-card"
```

2021-09-28 14:19 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCardModal.tsx
> +            onFocus={() => setFocusElement("number")}
yeah super weird that this is handled in this way, but this is exactly what is described in the stripe docs

2021-09-28 14:25 UTC, FSM1 requested changes
Seems like submitting with an incomplete form does not reset the `loadingPaymentMethodAdd` flag leading to the error being displayed but no possible actions the user can take

https://user-images.githubusercontent.com/12774278/135106094-4f0599a7-bba0-4bd6-962b-c9f94b560311.mp4

2021-09-28 15:56 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCardModal.tsx
> +            onFocus={() => setFocusElement("number")}
Yes exactly, no way of passing down CSS into the iFrame,
This is the only you can listen to the focus or blur changes !

2021-09-28 15:59 UTC, tanmoyAtb commented
> Looks rad! Is the `Current Card` section meant to display the cards yet?

With this approach, we can't set list of cards yet. The API side is working on finding how to do this !

2021-09-28 16:32 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCardModal.tsx
> +          borderColor: palette.primary.border
So the hover and shadow colors used here are in sync with the TextInput component we're using. 
The Files blue is a little different to these colors, and in a sense breaks overall consistency.

2021-09-28 18:22 UTC, tanmoyAtb commented
> Seems like submitting with an incomplete form does not reset the `loadingPaymentMethodAdd` flag leading to the error being displayed but no possible actions the user can take
> 
>  ChainSafe.Files.-.Brave.2021-09-28.16-15-45.mp4

Thanks for catch ! I pushed the fix.

2021-09-30 10:23 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCardModal.tsx
>      onClose()
This call to `onClose()` can be removed to prevent the modal from closing automatically, and allowing the user to fix their inputs and try again.
```suggestion

```

2021-09-30 11:21 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCardModal.tsx
> +    addToast({ title: t`Failed to add payment method`, type: "error" })
I think in this case it makes sense to display an error message in the modal instead of a toast.

2021-09-30 11:22 UTC, FSM1 requested changes
The modal should not close automatically if there is an error

2021-09-30 14:11 UTC, tanmoyAtb commented
> The modal should not close automatically if there is an error

Updated the overall error and modal handling system.

2021-10-03 22:27 UTC, FSM1 approved these changes

2021-10-04 10:09 UTC, Tbaut approved these changes
I added the card `4242 4242 ...` and got a "payment method added" toast. even if the date wasn't in the future, but I guess that's a stripe thing. Could test the 3d secure correctly :)

2021-10-04 14:01 UTC, FSM1 commented
> I added the card `4242 4242 ...` and got a "payment method added" toast. even if the date wasn't in the future, but I guess that's a stripe thing. Could test the 3d secure correctly :)

hmmm, thats super weird. I was not able to submit with a date in the past. It would throw an error.

2021-10-04 14:48 UTC, tanmoyAtb commented
> I added the card `4242 4242 ...` and got a "payment method added" toast. even if the date wasn't in the future, but I guess that's a stripe thing. Could test the 3d secure correctly :)

That should be a stripe thing, stripe doesn't block much with the test cards

2021-10-04 14:48 UTC, merged