Migrate to API local store cache
ChainSafe/files-ui pull request #1591
Opened 2021-09-28 13:10 UTC by RyRy79261

closes #1486

2021-10-04 09:44 UTC, FSM1 requested changes, later dismissed
I am unable to get the Survey banner and Sharing modal to appear. Tested with a new account, in a private browser session, and no luck.

2021-10-04 11:47 UTC, RyRy79261 commented
@FSM1 The survey only shows for users that are older than a week

2021-10-04 11:48 UTC, RyRy79261 commented
And the sharing dialog displayed the intro modal for me: 
![image](https://user-images.githubusercontent.com/10461622/135846255-6a29fa4e-993d-4455-816a-e992d9990169.png)

2021-10-04 14:15 UTC, FSM1 commented
> @FSM1 The survey only shows for users that are older than a week

ahhh gotcha, that makes sense... forgot about that rule 🙈

2021-10-04 16:36 UTC, tanmoyAtb commented on packages/files-ui/src/Contexts/UserContext.tsx
> +        } catch(error) {
```suggestion
        } catch(error) {
        console.error(error)
```

2021-10-04 16:47 UTC, tanmoyAtb approved these changes
Good to go !

2021-10-05 10:12 UTC, FSM1 approved these changes

2021-10-05 11:05 UTC, merged