Mv and rm batch calls
ChainSafe/files-ui pull request #1596
Opened 2021-09-29 09:54 UTC by FSM1

Closes #1556

2021-09-29 11:35 UTC, Tbaut requested changes

2021-09-29 11:35 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
> +      if (itemToDelete) {
Nit, for readability I find it easier when we earli return `if(!itemTodelete)` and then, in the normal case, return `getPathWithFile..`

2021-09-29 11:35 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
> +      const itemToRecover = pathContents.find((i) => i.cid === cid)
This logic looks duplicated many time in the PR, can we extract it to a function?

2021-09-29 12:53 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
> +      const itemToRecover = pathContents.find((i) => i.cid === cid)
As a sidenote on this!
Always felt we should pass path instead of CID in these functions, removes an extra step

2021-09-29 13:40 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
> +      const itemToRecover = pathContents.find((i) => i.cid === cid)
Using paths/names feels like "looser typing", though it does enable better consistency with the API 🤔 @Tbaut @RyRy79261 thoughts on updating all of these?

2021-09-29 14:44 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
> +      const itemToRecover = pathContents.find((i) => i.cid === cid)
I'm not sure what "looser typing" mean :laughing: 
If we don't need those cids.. then yeah giving the path right away would help I guess.

2021-09-29 15:46 UTC, Tbaut approved these changes
Wow nice the UX is so much better, it's snappy

2021-09-30 12:13 UTC, RyRy79261 approved these changes

2021-09-30 12:50 UTC, tanmoyAtb approved these changes
Good to go!

2021-09-30 13:13 UTC, merged