Create a link sharing from a shared folder manage access
ChainSafe/files-ui pull request #1619
Opened 2021-10-07 09:10 UTC by Tbaut

closes #1593 

I'll work on the tandem issue to join https://github.com/ChainSafe/ui-monorepo/issues/1474

https://user-images.githubusercontent.com/33178835/136355216-8545b2c4-7661-4165-b11d-b185d0d0a4cb.mp4

2021-10-07 09:16 UTC, Tbaut commented on packages/files-ui/src/Contexts/ThresholdKeyContext.tsx
> +  console.log("privateKey", privateKey)
```suggestion
```

2021-10-07 09:16 UTC, Tbaut commented on packages/files-ui/src/Contexts/ThresholdKeyContext.tsx
> +
```suggestion
    const header = { alg: "ES256", typ: "JWT" }
```

2021-10-07 09:16 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx
> +
```suggestion
```

2021-10-08 16:25 UTC, tanmoyAtb submitted a review, later dismissed
This is really beautiful work ! Sharing links is getting into shape.

- The LinkedList is getting duplicate keys somehow, if you create 3 or 4 links, you get the duplicate key warning on the console.
- Having the `Create new link` button load when deleting feels weird, we can have a separate loading state for deleting.
- This one is about preference, I would like to have the `Create new Link` button on the right side of `permissions` dropdown, feels more natural to me. (I haven't seen the designs though).

2021-10-08 16:25 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx
> +        padding: 10
```suggestion
        padding: constants.generalUnit * 1.25
```

2021-10-08 16:25 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/LinkList.tsx
> +
```suggestion
```

2021-10-08 16:25 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/LinkList.tsx
> +
```suggestion
```

2021-10-08 16:25 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/LinkList.tsx
> +        minWidth: 145
We can move this into the constants as well.

2021-10-08 16:25 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/LinkList.tsx
> +        padding: "6px 8px"
```suggestion
        padding: `${constants.generalUnit * 0.75}px ${constants.generalUnit}px`
```

2021-10-08 16:25 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/LinkList.tsx
> +
```suggestion
```

2021-10-08 16:25 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/SharingLink.tsx
> +    if(!nonce?.bucket_id || !nonce?.id) {
Could there be a case, where we don't set the `isLoading` to false, and it stays `true` within the component ?

2021-10-08 16:25 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/SharingLink.tsx
> +  useEffect(() => {
I feel like we can combine the `useEffects`

2021-10-08 16:25 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/SharingLink.tsx
> +
```suggestion
```

2021-10-08 16:25 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/SharingLink.tsx
> +        setIsLoading(true)
```suggestion
        setIsLoading(false)
```

2021-10-08 16:25 UTC, tanmoyAtb commented on packages/files-ui/src/Contexts/ThresholdKeyContext.tsx
> +      console.log("no private key found")
```suggestion
```

2021-10-11 12:45 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/LinkList.tsx
> +        minWidth: 145
yeah, I still think this constant doesn't make sense at this point.. we will never change it unless we want to see everything explode :shrug:

2021-10-11 12:47 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/SharingLink.tsx
> +    if(!nonce?.bucket_id || !nonce?.id) {
yup, Andrew found one, I'd say that if there's such a case, then we should fix it by setting a `setIsLoading(false)`. What do you think?

2021-10-11 12:49 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/SharingLink.tsx
> +  useEffect(() => {
Why is that? I'd prefer to let them separate. The dependencies arrays are different, any setter (like `setJWT`) are changing the state asynchronously.

2021-10-11 12:50 UTC, Tbaut commented on packages/files-ui/src/Contexts/ThresholdKeyContext.tsx
> +      console.log("no private key found")
I'd keep this one, or set it to a console.error
```suggestion
      console.error("no private key found")
```

2021-10-11 20:51 UTC, FSM1 requested changes
Some pretty strange happenings when trying to delete a number of nonces at once - The tab actually hangs brave quite badly

https://user-images.githubusercontent.com/12774278/136854460-9dd0ade2-b5b9-430c-a604-e857d17cc1fd.mp4

2021-10-11 20:51 UTC, FSM1 commented on packages/files-ui/src/Components/FilesRoutes.tsx
> +    `${window.location.origin}/sharing-link/${permissionPath(permission)}/${encodeURIComponent(jwt)}#${encodeURIComponent(bucketEncryptionKey)}`,
Do we need the permission in the path for any specific reason?

2021-10-12 13:21 UTC, Tbaut commented on packages/files-ui/src/Components/FilesRoutes.tsx
> +    `${window.location.origin}/sharing-link/${permissionPath(permission)}/${encodeURIComponent(jwt)}#${encodeURIComponent(bucketEncryptionKey)}`,
we don't, I really think this makes the UX better, we know right away if it's edit/read permission. Users don't see that unless they decode the jwt otherwise.

2021-10-12 14:29 UTC, Tbaut commented
I changed the implementation a little, which solves many issues. The api will not let one create more that 2 links (1 for edit, 1 for read). I now refresh the nonce list from the api (source of truth) which means there are more loading, but no more inconsistent state (like you've have @FSM1  or @tanmoyAtb).

> The LinkedList is getting duplicate keys somehow, if you create 3 or 4 links, you get the duplicate key warning on the console.

That's fixed with the last commit

>   Having the Create new link button load when deleting feels weird, we can have a separate loading state for deleting.

I'm not sure I get that. When you click on the delete button, it goes into a load state, which is expected. The "create new link" doesn't change, which I guess is expected as well. If you mean we should hide the "Create" button when deleting a link, I'm not sure I agree. This would mean more "flashing".

> This one is about preference, I would like to have the Create new Link button on the right side of permissions dropdown, feels more natural to me. (I haven't seen the designs though).

I 100% agree that my design isn't nice. Having the create button on the right side looked weird because we have too many buttons. I guess we just need @sweetpea22 and @serenaho to take a look at it :D

2021-10-12 18:54 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/SharingLink.tsx
> +    if(!nonce?.bucket_id || !nonce?.id) {
Absolutely 👍

2021-10-13 10:29 UTC, FSM1 approved these changes

2021-10-13 18:23 UTC, asnaith commented
Great feature @Tbaut

😎 Looking good on the below scenarios: 

🟢 User can generate a link for read access to a share
🟢 User can generate a link for edit access to a share
🟢 User can delete a share link that they have previously created
🟢 User can copy a generated link to their keyboard
🟢 User is informed that they need to be logged in / signed up to access share
🟢 User is informed of their access level on the "You were added" modal
🟢 User can navigate to the share via a browse button on the "You were added" modal
🟢 User joining a share via read rights link should have read only access
🟢 User joining a share via edit rights link should have edit access

The other two scenarios, as we know, are awaiting API changes: 
🟡 Existing read rights user should have their access rights upgraded after clicking an edit rights link
🟡 Existing edit rights user should have their access rights downgraded after clicking a
read rights link

Are we going to merge this to dev before or after the API is ready?

2021-10-14 11:42 UTC, RyRy79261 approved these changes

2021-10-14 11:42 UTC, RyRy79261 commented on packages/files-ui/src/Utils/pathUtils.ts
> +    console.error("JWT extractione error, unexpected path", pathname)
```suggestion
    console.error("JWT extraction error, unexpected path", pathname)
```

2021-10-14 12:36 UTC, Tbaut commented
@asnaith 
> Are we going to merge this to dev before or after the API is ready?

I'd say it'll depend on the api. I don't think it's really worked on right now, asking in our chat.

2021-10-14 12:40 UTC, merged