Link-sharing landing page
ChainSafe/files-ui pull request #1620
Opened 2021-10-07 15:21 UTC by Tbaut

closes #1474

2021-10-09 04:25 UTC, asnaith commented
Hey @Tbaut, the main flow is working really well for me. I tested this in conjunction with the link creation. 

small suggestions: 

- The terms "read access", "edit access" might be more universally understood than "rights", what do you think?

- Someone receiving the link may not know what kind of rights they have been given so maybe it would be good to display their access level in the "You were added to the shared folder" modal? 

quirks: 

- If a user joins a share via a link that gives them read access and they subsequently click another link granting edit access their access right level is not updated and they remain with read access.

- When a user tries to click on a link that has been deleted the modal will stay in this state indefintiely (screenshot below) and the user is never added. Perhaps we should inform the user that the link is no longer valid in this scenario. 

<img width="309" alt="Screen Shot 2021-10-08 at 8 20 53 PM" src="https://user-images.githubusercontent.com/3982665/136643764-998ed083-f286-4c31-9892-0484fe8f07a9.png">

- The "Create a Shared Folder" button is no longer responding to click and showing the modal for me (firefox and chrome)

<img width="407" alt="Screen Shot 2021-10-08 at 8 37 14 PM" src="https://user-images.githubusercontent.com/3982665/136643792-ad1c0d0d-5902-4a8b-8d3c-ba36b2bccd24.png">

- Edge case: If a user joins a share via a link and then subsequently clicks the link again they will see the same modal informing them that they were just added. Perhaps in this scenario, we could inform the user they already have access? 

- Edge case: Maybe we should put a cap on the amount of links that you can generate? 😅 It can become hard to navigate and it becomes unresponsive if you try to delete multiple links in quick succession. 

<img width="616" alt="Screen Shot 2021-10-08 at 8 08 41 PM" src="https://user-images.githubusercontent.com/3982665/136643684-0ec96bfa-f8ca-493c-b00c-8ef8b3becacd.png">

2021-10-11 10:04 UTC, tanmoyAtb requested changes
Working very well !

While testing I found on behaviour !
I created read and edit rights links. 

When another user opens the read rights link first  and then edit rights link, 
He does not receive edit rights, but remains as reader !

2021-10-11 10:04 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/LinkSharingModule.tsx
> +  const onBrowserBucker = useCallback(() => {
should this be `onBrowseBucket` ?

2021-10-11 10:04 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/LinkSharingModule.tsx
> +        setError(e.message)
not sure if we should just set the error from API, this would miss translations,
We can change this when error structure PR goes through !

2021-10-11 10:04 UTC, tanmoyAtb approved these changes

2021-10-11 11:09 UTC, Tbaut commented
> He does not receive edit rights, but remains as reader !

Thanks @asnaith and @tanmoyAtb for the review, the edit after read not being taken into account is an api issue, I'll ask them. Similarly for the link check, I think there's an issue to implement an endpoint to check whether or not a nonce is still active, but I think it hasn't been implemented yet.

2021-10-11 12:54 UTC, Tbaut commented
>    When a user tries to click on a link that has been deleted the modal will stay in this state indefintiely (screenshot below) and the user is never added. Perhaps we should inform the user that the link is no longer valid in this scenario.

I asked the api team about it. They handle 'nonce not found' as a 404, which I think is not super elegant. I've requested an api change for this.

>    The "Create a Shared Folder" button is no longer responding to click and showing the modal for me (firefox and chrome)

Ah, I had seen this and I fixed this in the branch above, but I didn't pull it. will do.

>    Edge case: If a user joins a share via a link and then subsequently clicks the link again they will see the same modal informing them that they were just added. Perhaps in this scenario, we could inform the user they already have access?

Indeed, I'll check this out.

> Edge case: Maybe we should put a cap on the amount of links that you can generate? sweat_smile It can become hard to navigate and it becomes unresponsive if you try to delete multiple links in quick succession.

I think this should be an api limitation if any. I guess that's a too edgy case for me to handle this client side.

2021-10-11 12:54 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/LinkSharingModule.tsx
> +  const onBrowserBucker = useCallback(() => {
yes!

2021-10-11 12:56 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/LinkSharingModule.tsx
> +        setError(e.message)
The thing is, we should handle common errors (when there's a revoked nonce or anything) but we can't catch and try to translate any possible error, this would never work. So We could always translate a "an error occured: [api error]" and leave the api error. This way of doing would be very useful for us to troubleshoot and support, rather than having a generic "oops something went wrong" and not give anything else.

2021-10-11 15:32 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/LinkSharingModule.tsx
> +        setError(e.message)
Agreed, and this is actually the exact approach I used with the Create Folder Modal - Handle a `409` with a custom message, and if it is some other error, display a generic message, with the original error following it

2021-10-11 20:15 UTC, FSM1 requested changes
Works really nicely. Great work Thibaut 🎉 

Left a couple of small comments on improvements that I can see.

2021-10-11 20:15 UTC, FSM1 commented on packages/files-ui/src/Utils/pathUtils.ts
> +    console.error("Bucket encryption key extractione error, unexpected hash", hash)
```suggestion
    console.error("Bucket encryption key extraction error, unexpected hash", hash)
```

2021-10-11 20:15 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/LinkSharingModule.tsx
> +  }, [newBucket])
I would remove this effect and handle the `setIsLoading` in the `finally()` below. That way if an error occurs, then the loader can at least be hidden.

2021-10-11 20:15 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/LinkSharingModule.tsx
> +      })
```suggestion
      .finally(() => {
        setIsLoading(false)
        refreshBuckets()
      })
```

2021-10-11 20:15 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/LinkSharingModule.tsx
> +  const bucketId = useMemo(() => jwt && jwtDecode<{bucket_id?: string}>(jwt)?.bucket_id, [jwt])
I would advise to wrap the jwtDecode in a `try ... catch` as I managed to crash the app when experimenting with malformed jwt's

2021-10-12 10:22 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/LinkSharingModule.tsx
> +  }, [newBucket])
```suggestion
```

2021-10-12 13:15 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/LinkSharingModule.tsx
> +        setError(e.message)
I'll address this as soon as the `api` is ready for it. (eventually in another PR)

2021-10-12 13:16 UTC, Tbaut commented
I addressed all the comments, added some more sugar on the cake (Showing the edit/read rights) and hopefully making it a bit more bullet proof with try/catch.

2021-10-12 13:33 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/LinkSharingModule.tsx
> +  console.log("!error && !newBucket && !permission", error, newBucket, permission)
```suggestion
```

2021-10-12 13:36 UTC, RyRy79261 approved these changes

2021-10-12 21:27 UTC, asnaith commented
Looking even better with the latest improvements. Love the extra sugar on top informing the user of the access right level too and I verified the create folder link is working again now 👍. 

- We will have to test access right updating via links once API support is in. 

- I didn't see any change to this behaviour yet:

>    Edge case: If a user joins a share via a link and then subsequently clicks the link again they will see the same modal informing them that they were just added. Perhaps in this scenario, we could inform the user they already have access?

- One minor colour change is needed for the icon on this modal 

<img width="571" alt="Screen Shot 2021-10-12 at 2 12 26 PM" src="https://user-images.githubusercontent.com/3982665/137031003-c8d66c45-8c7f-44d0-ab3d-376672822976.png">

2021-10-13 08:52 UTC, merged

2021-10-13 08:56 UTC, Tbaut commented
I clicked too quickly :see_no_evil: but the good new is, it's just got merged to the other branch :)

> I didn't see any change to this behaviour yet:

I meant to comment on this. So to check this, we'd need to go through all our buckets, if we find one, we'd need to check all the reader/writers/owner and see if what we're requesting is changing. This will quite complicate the code, for a pretty minor UX improvement. I thought it wasn't worth it. 

>    One minor colour change is needed for the icon on this modal

Thanks, will do the change in `tbaut-create-link-1473`