Update api error handling
ChainSafe/files-ui pull request #1626
Opened 2021-10-10 14:27 UTC by FSM1

Closes #1624

2021-10-11 08:02 UTC, Tbaut commented
Can you check the Lint @FSM1 ?

2021-10-11 10:30 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateFolderModal.tsx
> +          helpers.setFieldError("name", (error as ErrorDto).message || t`There was an error creating the folder`)
hmmm should the `error.message` stay ? that keeps untranslated strings in the code !

2021-10-11 10:31 UTC, tanmoyAtb commented
Am I the only one who's getting this ? couldn't get it compile in any way 
<img width="1180" alt="Screenshot 2021-10-11 at 4 27 57 PM" src="https://user-images.githubusercontent.com/10713353/136775952-082272eb-d1bc-48bf-8e3f-7a8a86c6698e.png">
!

2021-10-11 10:47 UTC, FSM1 commented
> Am I the only one who's getting this ? couldn't get it compile in any way <img alt="Screenshot 2021-10-11 at 4 27 57 PM" width="1180" src="https://user-images.githubusercontent.com/10713353/136775952-082272eb-d1bc-48bf-8e3f-7a8a86c6698e.png"> !

mmm, I was hoping this was something local. also still getting these errors... Once the dev server is running, it does actually work, but the TS checking just hangs... 🤔

2021-10-11 11:01 UTC, Tbaut commented on packages/storage-ui/package.json
> +    "@chainsafe/files-api-client": "1:18:15",
This is a weird version number, is that intended?

2021-10-11 11:01 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/UploadFileModal/UploadFileModal.tsx
> -        helpers.setFieldError("files", t`File/Folder already exists`)
I guess this error was good to catch and translate for the UI. Is there anything we can do to keep theses?

2021-10-11 11:41 UTC, FSM1 commented on packages/storage-ui/src/Components/Modules/UploadFileModal/UploadFileModal.tsx
> -        helpers.setFieldError("files", t`File/Folder already exists`)
This was a left-over from previous versions of the dialog, which stayed open after submission. The current approach is to look for `409 - conflict` error.code on the error response, and notify the user in a toast.

2021-10-11 11:43 UTC, FSM1 commented on packages/storage-ui/package.json
> +    "@chainsafe/files-api-client": "1:18:15",
Fixed, good spot

2021-10-11 11:44 UTC, FSM1 commented
> > Am I the only one who's getting this ? couldn't get it compile in any way <img alt="Screenshot 2021-10-11 at 4 27 57 PM" width="1180" src="https://user-images.githubusercontent.com/10713353/136775952-082272eb-d1bc-48bf-8e3f-7a8a86c6698e.png"> !
> 
> mmm, I was hoping this was something local. also still getting these errors... Once the dev server is running, it does actually work, but the TS checking just hangs... 🤔

Ok this is now fixed. Do not try and destructure in a `catch` 🤦🏼‍♂️

2021-10-11 12:21 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateFolderModal.tsx
> +          helpers.setFieldError("name", (error as ErrorDto).message || t`There was an error creating the folder`)
Fixed

2021-10-12 13:27 UTC, RyRy79261 approved these changes

2021-10-12 15:12 UTC, Tbaut requested changes
I just tested 2 types of error and it didn't work as expected.

2021-10-12 15:12 UTC, Tbaut commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +      if (error.error.code === 409) {
I got an `Unhandled Rejection (TypeError): error.error is undefined` here when uploading a file with the same name.

2021-10-12 15:12 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateFolderModal.tsx
> +        if ((error.error as ErrorDto).code === 409) {
This error never appeared for me in the interface.

2021-10-12 16:12 UTC, FSM1 commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +      if (error.error.code === 409) {
> I just tested 2 types of error and it didn't work as expected.

The changes have not been merged for the API - You can test by pointing at http://d627e992-default-imploy159-0b39-1311622473.us-east-2.elb.amazonaws.com/api/v1

API PR - https://github.com/ChainSafe/files-api/pull/1591

2021-10-13 03:34 UTC, asnaith commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateFolderModal.tsx
> +        if ((error.error as ErrorDto).code === 409) {
👍 I was able to see this once I switched the API in my .env file to http://d627e992-default-imploy159-0b39-1311622473.us-east-2.elb.amazonaws.com/api/v1

2021-10-13 03:34 UTC, asnaith commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +      if (error.error.code === 409) {
I re-configured my env file but was unable to test this because I was getting 500 errors when attempting the initial file upload. Is there perhaps something else I need to change?

2021-10-13 03:34 UTC, asnaith commented on packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
> +        errorMessage = t`Failed to validate signature.
I'm seeing an "Unhandled Rejection (TypeError): error.error is undefined" issue when canceling the sign request during a metamask login attempt

2021-10-13 03:34 UTC, asnaith commented on packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
> +      if (error.message === "user closed popup") {
I noticed the `error.error is undefined` issue when closing the metamask pop-up too

2021-10-13 03:34 UTC, asnaith commented on packages/files-ui/src/Contexts/UserContext.tsx
> +          : t`There was an error when setting username.`
I wasn't able to invoke this from the UI for testing. Do you have any recommendations on what the best approach would be to validate this?

2021-10-13 03:34 UTC, asnaith commented on packages/storage-ui/src/Components/Modules/CreateFolderModal/CreateFolderModal.tsx
> +              helpers.setFieldError("name", t`There was an error creating the folder ${(error as ErrorDto).message}`)
I wasn't able to invoke this from the UI for testing either

2021-10-13 09:24 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
> +        errorMessage = t`Failed to validate signature.
This error can be replicated by attempting to sign in using a contract wallet (eg argent) that has not yet been deployed.

2021-10-13 09:31 UTC, FSM1 commented on packages/storage-ui/src/Components/Modules/CreateFolderModal/CreateFolderModal.tsx
> +              helpers.setFieldError("name", t`There was an error creating the folder ${(error as ErrorDto).message}`)
Don't think there is really a way to invoke this from the UI. This would get hit if for instance the API threw a 500.

2021-10-13 09:38 UTC, FSM1 commented on packages/files-ui/src/Contexts/UserContext.tsx
> +          : t`There was an error when setting username.`
I don't think the First/Last name are validated at he API layer, since these are only used for display.

2021-10-13 09:39 UTC, FSM1 commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +      if (error.error.code === 409) {
~~Uploads on that instance were not working for me either, so I guess its best to test this when the API changes are deployed to staging.~~

Seems like that PR preview instance is down, so lets hold off on testing this out till the API changes are deployed to Stage

2021-10-14 21:15 UTC, asnaith commented on packages/files-ui/src/Contexts/UserContext.tsx
> +          : t`There was an error when setting username.`
I found a way to test this, by blocking requests to `https://stage.imploy.site/api/v1/user/lookup` in the firefox dev tools 

<img width="471" alt="Screen Shot 2021-10-14 at 2 11 28 PM" src="https://user-images.githubusercontent.com/3982665/137396307-7b886ddf-d950-452a-985b-3c3ed130623f.png">

2021-10-14 21:25 UTC, asnaith commented on packages/files-ui/src/Contexts/FilesContext.tsx
>          errorMessage = t`A file with the same name already exists`
<img width="428" alt="Screen Shot 2021-10-14 at 2 24 38 PM" src="https://user-images.githubusercontent.com/3982665/137397797-b4819e26-e9d8-4141-a851-74081f4f80c9.png">

👍

2021-10-14 21:26 UTC, asnaith commented on packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
>          errorMessage = t`Failed to get signature`
<img width="510" alt="Screen Shot 2021-10-14 at 2 21 31 PM" src="https://user-images.githubusercontent.com/3982665/137397365-dbe74325-8df3-4fd0-8727-ac9841a7090c.png">

2021-10-14 21:34 UTC, asnaith commented on packages/storage-ui/src/Components/Modules/CreateFolderModal/CreateFolderModal.tsx
> +              helpers.setFieldError("name", t`There was an error creating the folder ${(error as ErrorDto).message}`)
<img width="623" alt="Screen Shot 2021-10-14 at 2 18 57 PM" src="https://user-images.githubusercontent.com/3982665/137397214-5e40c4ea-f5ef-445f-9b13-429a11191b31.png">

Used request blocking for testing this too. Looks good 👍

2021-10-14 21:36 UTC, asnaith commented on packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
> +      if (error.message === "user closed popup") {
Working now 👍

2021-10-14 21:38 UTC, asnaith commented on packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
> +        errorMessage = t`Failed to validate signature.
I still couldn't work out how to invoke this with but every other error message was successfully tested so I think we're safe

2021-10-14 21:38 UTC, asnaith approved these changes

2021-10-15 11:01 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
> +        errorMessage = t`Failed to validate signature.
I've tested this flow quite extensively, and it is working well.

For future reference to test this flow:
1. Install either Authereum or Argent wallet on a device and create a new wallet. Do not activate/deploy this wallet.
2. Open the app and choose to log in with WalletConnect. 
3. Scan the QR code/open the link using the wallet created above.
4. Click on `Sign in with WalletConnect` and approve the signature request.
5. Observe the error message stating that contract wallets need to be deployed to be used to log in.

2021-10-15 13:15 UTC, FSM1 commented on packages/files-ui/src/Contexts/UserContext.tsx
> +          : t`There was an error when setting username.`
Yeah, it would be nice to actually test the branch on line 140, but that depends specifically on receiving an array of validation errors from the API.

2021-10-15 21:31 UTC, asnaith commented on packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
> +        errorMessage = t`Failed to validate signature.
Awesome @FSM1 thanks for the details 👍

2021-10-18 09:01 UTC, Tbaut approved these changes
Nice I could test and see many of these custom error handling!

Probably something for another issue: I'm getting an unhandled exception when changing wallet on Storage and Files, `Unhandled Rejection (Error): Missing or invalid topic field`.

Here is how:
- continue with web3 wallet
- connect a new wallet (was metamask originally)
- chose walletconnect
- closes 2 popups
- click to connect with another wallet to select metamask -> the error appears.

2021-10-18 09:01 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateFolderModal.tsx
> +        if (error?.error?.code === 409) {
:+1: tested this one

2021-10-18 09:01 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
>          errorMessage = t`The authentication popup was closed`
I could test this one :+1:

2021-10-18 09:01 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/LoginModule.tsx
>          errorMessage = t`Failed to get signature`
I didn''t test this one (no walletconnect handy).

2021-10-18 09:01 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/CreateFolderModal/CreateFolderModal.tsx
> +            if (error?.error?.code === 409) {
Weirdly enough, I didn't get an error here in Storage. I get a 200.. and that's it :man_shrugging:

2021-10-18 09:01 UTC, Tbaut commented on packages/storage-ui/src/Contexts/StorageContext.tsx
>          errorMessage = t`A file with the same name already exists`
Same here, I didn't get an error from the api, the upload gave me a `200`...

2021-10-18 10:35 UTC, FSM1 commented on packages/storage-ui/src/Components/Modules/LoginModule.tsx
>          errorMessage = t`Failed to get signature`
This message is not particular to wallet connect. This can be tested by rejecting the signature request in which ever wallet you are using.

2021-10-18 10:37 UTC, FSM1 commented on packages/storage-ui/src/Components/Modules/CreateFolderModal/CreateFolderModal.tsx
> +            if (error?.error?.code === 409) {
My understanding is that since the file systems used by CSF and Storage buckets are different, this could result in the strange behavior we are seeing.

2021-10-18 10:53 UTC, FSM1 commented
> Nice I could test and see many of these custom error handling!
> 
> Probably something for another issue: I'm getting an unhandled exception when changing wallet on Storage and Files, `Unhandled Rejection (Error): Missing or invalid topic field`.
> 
> Here is how:
> 
> * continue with web3 wallet
> * connect a new wallet (was metamask originally)
> * chose walletconnect
> * closes 2 popups
> * click to connect with another wallet to select metamask -> the error appears.

The error you're referring to has nothing to do with the changes implemented here, and is actually what seems like a bug in the web3-context package.

2021-10-18 10:55 UTC, merged