Change plan widget
ChainSafe/files-ui pull request #1649
Opened 2021-10-21 12:44 UTC by RyRy79261

closes #1455

2021-10-25 17:52 UTC, tanmoyAtb submitted a review, later dismissed
Overall looks good,
Although the API keeps throwing 500 at me, couldn't test everything. 

The loaders looks too big for my liking. could make them smaller.
The mobile view also looks cramped. Not sure if we have designs for them.

Left a few comments.

2021-10-25 17:52 UTC, tanmoyAtb commented on packages/common-components/src/stories/ToggleSwitch.stories.tsx
> +export const ToggleSwitchDemo = (): React.ReactNode => {
I tried testing out the toggle on storybooks, for some reason the toggle or size knobs aren't doing anything for me. 

The code looks right though? is it working on your side ?

2021-10-25 17:52 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/Settings/Products/ChangeProductViews/SelectPlan.tsx
> +          href="#"
Added an issue, or we may forget about adding the link.
https://github.com/ChainSafe/ui-monorepo/issues/1654

2021-10-25 17:52 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/Settings/Products/ChangeProductModal.tsx
> +  const [slide, setSlide] = useState<"select" | "confirm">("select")
Do we still need this state ?

2021-10-25 18:52 UTC, Tbaut reviewed
A couple comments on the UI, will dig in the code later.
![image](https://user-images.githubusercontent.com/33178835/138752770-7c07e722-01c2-4180-8516-2207097b3804.png)
- "current" is hard to read because of the contrast
- "not sure what to pick" font should prob. be bigger
- "Free" disappears when we toggle the annual plan
- button toggle doesn't tell whether or not it's activated. Should it be green then?
- when you select another plan than yours, you can't select the free plan any more, it's disabled. I'd let users actually select it (and disable the apply button)

2021-10-26 11:20 UTC, FSM1 requested changes
One flow that has not yet been catered for is if a user attempts to upgrade their subscription but does not have a card added to their account yet.

2021-10-26 13:27 UTC, RyRy79261 commented on packages/files-ui/src/Components/Modules/Settings/Products/ChangeProductModal.tsx
> +  const [slide, setSlide] = useState<"select" | "confirm">("select")
@tanmoyAtb So technically no but because I wasn't sure what the state of the other screens in the design are I've left it

CC: @FSM1

2021-10-26 13:45 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/Settings/Products/ChangeProductModal.tsx
> +  const [slide, setSlide] = useState<"select" | "confirm">("select")
Yeah given the future plans for this modal, might as well leave this in for now.
![image](https://user-images.githubusercontent.com/12774278/138891808-0b51c151-ed2d-4ce6-9bd4-4968bed021fa.png)

2021-10-26 13:57 UTC, RyRy79261 commented
@Tbaut 

- The current tag was improv, so not sure what would be preferred here
- Adjusted the font variant
- There isn't any price data for Free's annual variant so theres nothing to interpret or display 
- Potentially, I just used the design and single colors since it works in dark mode
- Sweet removed the click blocking, though now the user wont know why they cant select a plan until they choose it

2021-10-26 17:04 UTC, tanmoyAtb commented on packages/common-components/src/ToggleSwitch/ToggleSwitch.tsx
> +import { Typography } from ".."
This removes a circular dependency warrning.
```suggestion
import { Typography } from "../Typography"
```

2021-10-26 17:24 UTC, Tbaut reviewed
I went through the code, the "Free" flashing when we change the yearly/monthly toggle isn't a big deal I guess. Regarding the color, the "Current" plan is super hard to read in light mode with black on blue. We should have white on blue

2021-10-26 17:24 UTC, Tbaut commented on packages/common-components/src/ToggleSwitch/ToggleSwitch.tsx
> +  // name?: string
```suggestion
```

2021-10-26 17:24 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/Products/ChangeProductViews/SelectPlan.tsx
> +                      price.unit_amount === 0 ? t`Free` : <>{ price.unit_amount }&nbsp;{ price.currency }&nbsp;{ translatedPrice }</>
```suggestion
                      price.unit_amount === 0 ? t`Free` : `${price.unit_amount} ${price.currency} ${translatedPrice}`
```

2021-10-26 17:24 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/Products/ChangeProductModal.tsx
> +
```suggestion
```

2021-10-26 17:24 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/Products/ChangeProductModal.tsx
> +            changeSubscription(productId, priceId).then(() => close())
```suggestion
            changeSubscription(productId, priceId)
              .then(() => close())
              .catch(console.error)
```

2021-10-26 17:24 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/Products/ChangeProductViews/SelectPlan.tsx
> +        .then((plans) => setPlans(plans))
```suggestion
        .then((plans) => setPlans(plans))
        .catch(console.error)
```

2021-10-26 17:24 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/Products/ChangeProductViews/SelectPlan.tsx
> +                  }
```suggestion
                  variant="h5"
                >
                  {plan.name}
```

2021-10-26 17:24 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/Products/ChangeProductViews/SelectPlan.tsx
> +              plans?.find(plan => plan.id === selectedPlan)?.prices.find(price => price.recurring.interval === interval)?.id as string)}
This is quite involved, can we extract this to a separate `onSelecPlan` for instance?
Also the type casting will make the app crash if the `selectPlan` is undefined. we should rather add an early return like `if(!selectedPlan) return`

2021-10-26 17:24 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/Products/ChangeProductModal.tsx
> +
```suggestion
```

2021-10-26 17:24 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentProduct.tsx
> +  const [changeProductActive, setChangeProductActive] = useState(false)
Could we name this `isChangeProductModalVisible`?

2021-10-26 17:24 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentProduct.tsx
> +        <ChangeProductModal
For consistency with the other modals. Could we show this by default, and remove the `active` from the the props:
```js
  { isChangeProductModalVisible && (
    <ChangeProductModal close={() => setChangeProductActive(false)} />
  )}
```

2021-10-26 17:24 UTC, Tbaut commented on packages/files-ui/src/Contexts/BillingContext.tsx
> +      })
```suggestion
      .catch(console.error)
```

2021-10-27 10:38 UTC, RyRy79261 commented on packages/common-components/src/stories/ToggleSwitch.stories.tsx
> +export const ToggleSwitchDemo = (): React.ReactNode => {
Tbh I'm not sure it worked most of the time but not after a reload 

@FSM1 ?

2021-10-27 10:39 UTC, RyRy79261 commented on packages/common-components/src/ToggleSwitch/ToggleSwitch.tsx
> +  // name?: string
@Tbaut So this is there for a formik version that I didn't build out, not sure if we need a formik version though

2021-10-27 14:45 UTC, Tbaut commented on packages/common-components/src/ToggleSwitch/ToggleSwitch.tsx
> +  // name?: string
Ah OK. It's easy enough to add I think, I guess we don't need to keep comments.

2021-10-29 10:26 UTC, Tbaut commented
as per my previous comment https://github.com/ChainSafe/ui-monorepo/pull/1649#discussion_r736732845
> type casting will make the app crash if the `selectPlan` is undefined. we should rather add an early return like `if(!selectedPlan) return`

Type casting should be last resort, I'm pretty sure we can be safer than this.

2021-11-01 10:59 UTC, Tbaut requested changes
see previous comment

2021-11-03 11:43 UTC, RyRy79261 commented
@Tbaut The button can only be executed if the value is not undefined, I've added a redundant check to remove the casting

2021-11-03 14:07 UTC, FSM1 commented on packages/common-components/src/stories/ToggleSwitch.stories.tsx
> +export const ToggleSwitchDemo = (): React.ReactNode => {
there was a small typing error with the toggle switch overrides in the theme. I think I have gotten it fixed.

2021-11-04 10:42 UTC, Tbaut approved these changes
Looking great!

2021-11-04 11:11 UTC, FSM1 approved these changes

2021-11-04 12:13 UTC, merged