notifications for billing
ChainSafe/files-ui pull request #1656
Opened 2021-10-25 18:44 UTC by tanmoyAtb

closes #1646

Edit this in `AppHeader.tsx` to see some notifications.
```
<NotificationsDropdown
  notifications={[
     {
         title: "This is a title. Add as many lines as you can",
         createdAt: new Date()
     }
   ]}
/>
```

Note: Notifications button don't actually resemble the designs, the designs have the new design of buttons and UI elements which we have to work on.

2021-11-01 11:32 UTC, Tbaut requested changes
Look pretty good. Just a couple nits. Also we should have some max height and scroll bar

![image](https://user-images.githubusercontent.com/33178835/139663563-1ab0074e-5ab0-46bc-b9f9-1ba1d82056eb.png)

Also how should this look like on Mobile @serenaho and @sweetpea22

2021-11-01 11:32 UTC, Tbaut commented on packages/files-ui/src/Components/Elements/NotificationsDropdown.tsx
> +      background: palette.additional["red"][6],
We should double check with @sweetpea22 and @serenaho. This red is very loud compared to the one in the mock.

2021-11-01 11:32 UTC, Tbaut commented on packages/files-ui/src/Components/Elements/NotificationsDropdown.tsx
> +      lineHeight: "11px"
we can achieve the pill look with a width of `1rem` and height of `.8rem` for instance
![image](https://user-images.githubusercontent.com/33178835/139664317-8de0392d-f83c-4b74-b96a-b0cc7fc61972.png)


```suggestion
      lineHeight: "11px",
      height: "0.8rem",
      minWidth: "1rem"
```

2021-11-01 11:32 UTC, Tbaut commented on packages/files-ui/src/Components/Elements/NotificationsDropdown.tsx
> +      <Button variant="outline">
I know this will change but for now, could we make sure it's the same look and feel as the other buttons? I think they have the variant "tertiary afair"

2021-11-01 11:32 UTC, Tbaut commented on packages/common-components/src/MenuDropdown/MenuDropdown.tsx
> +        {children && children}
see the lgtm alert above.
```suggestion
        {children}
```

2021-11-01 13:00 UTC, sweetpea22 commented
The notification will replace the search icon let me pull up the design brb!

2021-11-01 18:07 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Elements/NotificationsDropdown.tsx
> +      background: palette.additional["red"][6],
I rechecked the designs, looks like it was `volcano-6`, made the updates

2021-11-01 18:09 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Elements/NotificationsDropdown.tsx
> +      <Button variant="outline">
Yes. using tertiary feels right here!

2021-11-01 18:15 UTC, tanmoyAtb commented
> Look pretty good. Just a couple nits. Also we should have some max height and scroll bar
> 
> ![image](https://user-images.githubusercontent.com/33178835/139663563-1ab0074e-5ab0-46bc-b9f9-1ba1d82056eb.png)
> 
> Also how should this look like on Mobile @serenaho and @sweetpea22

Thanks for the feedbacks, 
I made the updates and added a scrollbar, thats was a good point.

2021-11-02 16:52 UTC, Tbaut approved these changes
Looks good, let's just not push with those fixture notifications :)

2021-11-02 16:52 UTC, Tbaut commented on packages/files-ui/src/Components/Layouts/AppHeader.tsx
> +                  ]}
```suggestion
                  notifications={[]}
```

2021-11-03 11:53 UTC, RyRy79261 approved these changes

2021-11-03 13:21 UTC, merged