[Files] Verfy a sharing link asap and give nice error
ChainSafe/files-ui pull request #1674
Opened 2021-10-27 22:20 UTC by Tbaut

closes #1671

- verify the nonce asap if the user isn't logged-in
- if the user is already logged in, the redirect to the landing happens and a nice (translatable) error is displayed.

2021-10-28 03:10 UTC, asnaith commented
Hey Thibaut, I found an issue whilst testing this out. When a logged in user clicks an invalid link they see the new error message but also other elements that should be hidden: 

<img width="507" alt="Screen Shot 2021-10-27 at 7 41 35 PM" src="https://user-images.githubusercontent.com/3982665/139177506-180ff701-8e7a-4144-bae9-4d05bae3981e.png">

There's also a small discrepancy with the icon colour of the exclamation mark in dark mode when the user is signed out. 

<img width="495" alt="Screen Shot 2021-10-27 at 7 43 37 PM" src="https://user-images.githubusercontent.com/3982665/139179602-aa8fdb1f-c882-4de5-a280-b5c977aceadd.png">

2021-10-28 11:56 UTC, RyRy79261 reviewed
Looks streamlined though spotted a typo :)

2021-10-28 11:56 UTC, RyRy79261 commented on packages/files-ui/src/Components/Modules/LinkSharingModule.tsx
> +export interface DecodedNounceJwt {
```suggestion
export interface DecodedNonceJwt {
```

2021-10-28 11:56 UTC, RyRy79261 commented on packages/files-ui/src/Components/Modules/LinkSharingModule.tsx
> +      return (jwt && jwtDecode<DecodedNounceJwt>(jwt)) || {}
```suggestion
      return (jwt && jwtDecode<DecodedNonceJwt>(jwt)) || {}
```

2021-10-28 11:56 UTC, RyRy79261 commented on packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
> +import { DecodedNounceJwt } from "../LinkSharingModule"
```suggestion
import { DecodedNonceJwt } from "../LinkSharingModule"
```

2021-10-28 11:56 UTC, RyRy79261 commented on packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
> +      nonce = (jwt && jwtDecode<DecodedNounceJwt>(jwt).nonce_id) || ""
```suggestion
      nonce = (jwt && jwtDecode<DecodedNonceJwt>(jwt).nonce_id) || ""
```

2021-10-28 14:09 UTC, FSM1 requested changes
Works well for revoked links. Would probably make sense to allow the user some way to go back to the normal login page if they attempt to join using a revoked link:
![image](https://user-images.githubusercontent.com/12774278/139272104-6d2bd955-034f-454c-a8bb-501cd7c234e2.png)

Another flow that could be improved is if the user provides a malformed JWT in the join link. Since its not possible to extract the NONCE from this JWT, it never gets validated, and only throws an error after the user logs in.

2021-10-28 16:49 UTC, asnaith commented
Looking good now since the latest changes @Tbaut! 

Small observation with the new go back button - If I'm logged out, click a link, see invalid link message, then return to login screen I will see the "Sign in/up to access the shared folder" message and then if I sign in I see the invalid link message once more. Perhaps when a user clicks to go back we should direct them to the regular login URL to prevent this?

2021-10-28 16:50 UTC, Tbaut commented
Thanks for the thorough review y'all. I did a lot of code changes, please re-check as much as you can.
- no more loader + invalid link info at the same time
- no more typo
- no more wrong color on dark mode
- there's a button to go to normal login now (if the user isn't logged in)
- nice error instead of doing nothing if the JWT is malformed

2021-10-28 16:51 UTC, Tbaut commented
> Perhaps when a user clicks to go back we should direct them to the regular login URL to prevent this?

Arg that's annoying. Yeah, I'll redirect then.

edit: @asnaith should be sorted with 579f131

2021-10-28 23:08 UTC, asnaith commented
I've thoroughly reviewed the feature and updated the user scenarios doc. Everything is working great 😃

✅ User can generate a link for read access to a share
✅ User can generate a link for edit access to a share
✅ User can delete a share link that they have previously created
✅ User can copy a generated link to their keyboard
✅ User is informed that they need to be logged in / signed up to access share
✅ User is informed of their access level on the "You were added" modal
✅ User can navigate to the share via a browse button on the "You were added" modal
✅ User joining a share via read rights link should have read only access
✅ User joining a share via edit rights link should have edit access
✅ Existing read rights user should have their access rights upgraded after clicking an edit rights link
✅ Existing edit rights user should not have their access rights downgraded after clicking a read rights link
✅ Signed in user can see invalid link error if share link was deleted
✅ Signed out user can see invalid link error if share link was deleted
✅ Signed out user can return to the login screen after clicking an invalid share link
✅ User can see "Token Malformed" error when clicking an incorrect share link

2021-10-28 23:08 UTC, asnaith approved these changes

2021-11-02 11:55 UTC, FSM1 approved these changes

2021-11-02 11:58 UTC, merged