Resolved `error.error` error
ChainSafe/files-ui pull request #1716
Opened 2021-11-08 15:00 UTC by RyRy79261

closes #1707

2021-11-08 15:21 UTC, Tbaut commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +            ? error.error.message : ""}`
Would something like this work
```suggestion
      let errorMessage = `${t`An error occurred: `} ${error || error.message || error.error.message || ""}
```

This suggestion still looks awful to my eyes, but a little bit better than 3 ternaries.

2021-11-08 17:54 UTC, RyRy79261 commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +            ? error.error.message : ""}`
Yeah was just following the existing approach, this is much nicer

2021-11-08 18:09 UTC, Tbaut commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +      let errorMessage = `${t`An error occurred: `} ${error || error.message || error.error.message || ""}
suggestion gone wrong. BTW this should be tested, I did not test it :D
```suggestion
      let errorMessage = `${t`An error occurred: `} ${error || error.message || error.error.message || ""}`
```

2021-11-08 18:16 UTC, tanmoyAtb commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +      let errorMessage = `${t`An error occurred: `} ${error || error.message || error.error.message || ""}
Wouldn't this way create problems if `error` was an object and not a string ?

2021-11-08 20:28 UTC, FSM1 commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +      let errorMessage = `${t`An error occurred: `} ${error || error.message || error.error.message || ""}
My preference here would be to just use `let errorMessage = `${t`An error occurred: `} ${typeof(error) === "string" ? error : error?.error?.message ? error.error.message : ""}``

2021-11-08 23:18 UTC, Tbaut commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +      let errorMessage = `${t`An error occurred: `} ${error || error.message || error.error.message || ""}
We can leave the last one at least
```suggestion
      let errorMessage = `${t`An error occurred: `} ${typeof(error) === "string" ? error : error?.error?.message || ""}`
```

2021-11-09 09:38 UTC, RyRy79261 commented on packages/files-ui/src/Contexts/FilesContext.tsx
> +      let errorMessage = `${t`An error occurred: `} ${error || error.message || error.error.message || ""}
Oh lord 😂

2021-11-09 10:11 UTC, Tbaut requested changes
It's deleting a bunch of translation. I guess it's simpler to start from scratch :D

2021-11-09 10:11 UTC, Tbaut commented on packages/files-ui/src/locales/de/messages.po
> +msgstr ""
```suggestion
msgstr ""Es existiert bereits eine Datei mit demselben Namen""
```

2021-11-09 10:11 UTC, Tbaut commented on packages/files-ui/src/locales/de/messages.po
> +msgstr ""
```suggestion
msgstr "Es ist ein Fehler aufgetreten:"
```

2021-11-09 10:11 UTC, Tbaut commented on packages/files-ui/src/locales/de/messages.po
> +msgstr ""
```suggestion
msgstr "Es ist etwas schief gelaufen. Wir konnten Ihre Datei nicht hochladen"
```

2021-11-09 10:11 UTC, Tbaut commented on packages/files-ui/src/locales/de/messages.po
> +msgstr ""
```suggestion
 msgstr "{0, plural, one {{1} Datei wird heruntergeladen} other {{2} Dateien werden heruntergeladen}}"
```

2021-11-09 10:11 UTC, Tbaut commented on packages/files-ui/src/locales/de/messages.po
> +msgstr ""
```suggestion
 msgstr "{0, plural, one {{1} Datei wird verschlüsselt und hochgeladen} other {{2} Dateien werden verschlüsselt und hochgeladen}}"
```

2021-11-09 10:11 UTC, Tbaut commented on packages/files-ui/src/locales/es/messages.po
> +msgstr ""
```suggestion
 msgstr "Ya existe un archivo con el mismo nombre"
```

2021-11-09 10:11 UTC, Tbaut commented on packages/files-ui/src/locales/es/messages.po
> +msgstr ""
```suggestion
 msgstr "Algo salió mal. No pudimos subir tu archivo"
```

2021-11-09 10:11 UTC, Tbaut commented on packages/files-ui/src/locales/fr/messages.po
> +msgstr ""
```suggestion
 msgstr "Un fichier avec ce nom existe déjà"
```

2021-11-09 10:11 UTC, Tbaut commented on packages/files-ui/src/locales/fr/messages.po
> +msgstr ""
```suggestion
 msgstr "Une erreur s'est produite :"
```

2021-11-09 10:11 UTC, Tbaut commented on packages/files-ui/src/locales/fr/messages.po
> +msgstr ""
```suggestion
 msgstr "Copie de fichiers"
```

2021-11-09 10:11 UTC, Tbaut commented on packages/files-ui/src/locales/fr/messages.po
> +msgstr ""
```suggestion
 msgstr "Téléchargement terminé"
```

2021-11-10 12:26 UTC, Tbaut commented
done in https://github.com/ChainSafe/ui-monorepo/pull/1717

2021-11-10 12:26 UTC, closed without merging