Share files from browser support
ChainSafe/files-ui pull request #1736
Opened 2021-11-12 09:18 UTC by tanmoyAtb

closes #1631

2021-11-16 23:26 UTC, asnaith commented
Looking good for the most part on desktop and mobile. 

I found a small issue related to the refresh logic though and I think we need to trigger a refresh after a shared folder is deleted to ensure this correct modal is always displayed.

As demonstrated in the video below - after deleting all the shared folders the wrong modal was presented when trying to share again and it didn't update until the browser was refreshed. 

https://user-images.githubusercontent.com/3982665/142082112-b7f63f51-6c97-4575-bb74-b551c1683982.mov

2021-11-17 15:05 UTC, FSM1 commented
> I found a small issue related to the refresh logic though and I think we need to trigger a refresh after a shared folder is deleted to ensure this correct modal is always displayed.

This is caused by the bucket only being  marked as `status: deleting` after the request. We filter for these on the buckets overview, but not so in the `ShareModal.tsx` where `bucketOptions` is calculated. Just need to filter out any buckets with a `status: deleting` property.

2021-11-17 15:09 UTC, FSM1 requested changes
![image](https://user-images.githubusercontent.com/12774278/142226295-282d18a3-fd64-456a-99b3-f9136422093a.png)

Don't know if we want to deal with this in this ticket, but the modal covers the `cancel` button at the bottom of the screen now. We should also maybe consider renaming the button to `Close` as nothing is really being cancelled by closing the modal.

2021-11-17 15:09 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx
> +    width: bucketToUpload ? 600 : 500
Any particular reason for this difference in width?

2021-11-17 15:35 UTC, tanmoyAtb commented
> Looking good for the most part on desktop and mobile.
> 
> I found a small issue related to the refresh logic though and I think we need to trigger a refresh after a shared folder is deleted to ensure this correct modal is always displayed.
> 
> As demonstrated in the video below - after deleting all the shared folders the wrong modal was presented when trying to share again and it didn't update until the browser was refreshed.
> 
>  Screen.Recording.2021-11-16.at.3.17.26.PM.mov

@FSM1 thanks for the heads up, that status was it.
@asnaith should be good now. your observation is amazing !

2021-11-17 15:48 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx
> +    width: bucketToUpload ? 600 : 500
Yeah so, The designs have this screen around 500px, however the manage shared folder modal (from shares overview) had this screen a bit larger. I wanted to keep the consistency.

2021-11-17 15:50 UTC, tanmoyAtb commented
> ![image](https://user-images.githubusercontent.com/12774278/142226295-282d18a3-fd64-456a-99b3-f9136422093a.png)
> 
> Don't know if we want to deal with this in this ticket, but the modal covers the `cancel` button at the bottom of the screen now. We should also maybe consider renaming the button to `Close` as nothing is really being cancelled by closing the modal.

`Close` sounds more appropriate. 
As for the `close` button, I think we cover that in the modal redesign issue. #1729

2021-11-17 19:16 UTC, asnaith approved these changes
Nice fix @tanmoyAtb, looking good now after shared folder deletion, the right modal is shown.

2021-11-17 19:54 UTC, FSM1 approved these changes

2021-11-18 14:48 UTC, merged