Rename with slit extension
ChainSafe/files-ui pull request #1760
Opened 2021-11-18 11:55 UTC by RyRy79261

closes #1754

2021-11-18 15:48 UTC, tanmoyAtb submitted a review, later dismissed
Overall implementation is working great,

I found a caveat, if you upload a file without an extension, it treats the filename as extension,
This only occurred when I created a file using `touch`,

Not sure about this one, On hitting rename the rename input does not autofocus !

2021-11-18 22:49 UTC, asnaith commented
Looking good for the most part. 

In addition to what Tanmoy mentioned, I also noticed that when you rename a folder it appends an "." onto the end of the new folder name.

2021-11-19 14:48 UTC, RyRy79261 commented
@tanmoyAtb So autofocus I'm not sure about I did make a change to autofocus behaviour for Safari the other day though 

Will amend

2021-11-22 15:12 UTC, tanmoyAtb commented
I tried renaming a folder but it appended a `.` at the end. 
This also happens to files with no extension !

2021-11-24 12:59 UTC, FSM1 requested changes

2021-11-24 12:59 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
> +      fileName : name.replace(extension, ""),
This breaks for filenames containing the extension `file.pdf test.pdf`

2021-11-25 11:04 UTC, FSM1 approved these changes

2021-11-25 11:04 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
> +        fileName: name.slice(0, name.length - extension.length - 1),
Whoops, was not necessary for that `- 1` to be there, since the extension already includes the `.`
```suggestion
        fileName: name.slice(0, name.length - extension.length),
```

2021-11-25 11:04 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
> +      fileName: name.slice(0, name.length - extension.length - 1),
Whoops, was not necessary for that `- 1` to be there, since the extension already includes the `.`
```suggestion
      fileName: name.slice(0, name.length - extension.length),
```

2021-11-25 11:04 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
> +        fileName: name.slice(0, name.length - extension.length - 1),
Whoops, was not necessary for that `- 1` to be there, since the extension already includes the `.`
```suggestion
      fileName: name.slice(0, name.length - extension.length),
```

2021-11-25 20:35 UTC, FSM1 commented
@tanmoyAtb @asnaith please could you re-check this after all the fixes 🙏🏼

2021-11-25 21:33 UTC, asnaith approved these changes
Working well for me on desktop and iOS now. 

I tested folders, files, files without extensions, and files with "." in the name.

2021-11-25 22:11 UTC, merged