Improve credit card flow
ChainSafe/files-ui pull request #1828
Opened 2021-12-14 18:33 UTC by tanmoyAtb

closes #1825 

---
Submission checklist: 

   

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode 
- [x] Components / elements inspected in dark mode

2021-12-14 21:46 UTC, asnaith approved these changes

2021-12-15 13:00 UTC, Tbaut requested changes

2021-12-15 13:00 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
> +  const closeIcon = <CrossIcon
The modal has a built in close icon, Why not use this one?

2021-12-15 13:00 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ConfirmPlan.tsx
> +    crossIcon: {
Same here, this is duplicated isn't it?

2021-12-15 15:44 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
> +  const closeIcon = <CrossIcon
Yes, this is duplicated, 
I tried using the the default icon, But each page in this modal has different sizes and the cross icon was getting outside the modal screens, I tried making it work, but it was getting to too much refactoring.

2021-12-15 15:47 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
> +  const closeIcon = <CrossIcon
Hmm, If there's something broken elsewhere we should 100% fix it, eventually in another PR, but doing what we're doing here doesn't feel right. Happy to help there if you want.

2021-12-16 09:47 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
> +  const closeIcon = <CrossIcon
Alright, So managed to get the cross icon to work within the modal component !

2021-12-16 10:54 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
> +  const closeIcon = <CrossIcon
yes yes yes awesome! :raised_hands: checking it out

2021-12-16 11:04 UTC, Tbaut approved these changes
:100: tested mobile view on many modals, and looks great

2021-12-16 11:04 UTC, merged