readcrum refs and active colors
ChainSafe/files-ui pull request #1836
Opened 2021-12-25 09:09 UTC by tanmoyAtb

closes #1772 

---
Submission checklist: 

#### Layout
- [ ] Change looks good in the desktop web ui
- [ ] Change looks good in the mobile web ui

#### Theme
- [ ] Components / elements inspected in light mode 
- [ ] Components / elements inspected in dark mode

2022-01-03 13:18 UTC, Tbaut requested changes
I didn't check the code yet, but testing the functionality, I got an error from the `mv` from the api.
I have a file in `/some/folder` and drag it to move it to `/some`. The request fails with
> Object { code: 400, message: "paths is required" }
The request is as follow:
```
{"paths":[],"new_path":"/some/"}
```

2022-01-03 15:24 UTC, tanmoyAtb commented
> I didn't check the code yet, but testing the functionality, I got an error from the `mv` from the api. I have a file in `/some/folder` and drag it to move it to `/some`. The request fails with
> 
> > Object { code: 400, message: "paths is required" }
> > The request is as follow:
> 
> ```
> {"paths":[],"new_path":"/some/"}
> ```

Its working my side, I even tried with the same `/some/folder` tree. Can you check if the drag and drop on a folder in the file browser lists work instead of the breadcrumb ?

2022-01-03 18:31 UTC, Tbaut commented
There are some weirdnesses.. I moved my file to the `/some/folder` folder, then try to DnD with breadcrumb, it fails (not on the video), I try again (visible in the video), it works, I browse to `/some`, drag the file down to `/some/folder`, it works, then try to drag it up using the breadcrumb, it fails again..
https://user-images.githubusercontent.com/33178835/147966088-506a16d0-8d99-49b9-9e76-9130c926afcf.mp4

2022-01-04 15:38 UTC, tanmoyAtb commented
> There are some weirdnesses.. I moved my file to the `/some/folder` folder, then try to DnD with breadcrumb, it fails (not on the video), I try again (visible in the video), it works, I browse to `/some`, drag the file down to `/some/folder`, it works, then try to drag it up using the breadcrumb, it fails again..
> 
>  weirdness.mp4

So I think there's some sensitivity around the way we are dragging. If you check the clip, when the move failed, there was no drag preview. Somehow the drag event failed to grab the source. 

I'll spend some time to see if I can find the actual issue.

2022-01-05 18:23 UTC, tanmoyAtb commented
Found the issue, The useDrag wasn't re rendering when file contents changed by moving into a folder. It should be good to go now.

2022-01-05 20:25 UTC, asnaith commented
Hey Tanmoy, I'm seeing some strange behaviour but it's kind of difficult to describe some of them. I've captured them on video so hopefully that helps. 

- I noticed there's an issue with the appearance of the breadcrumb folders after a browser refresh 

https://user-images.githubusercontent.com/3982665/148283065-80d88f18-3285-4313-a118-1bef91c62e88.mov

- When you drag a file to the folder on the breadcrumb that it's already residing in it will append a (1) to the file name and also the modal is cut short 

https://user-images.githubusercontent.com/3982665/148283304-76a58ae9-30ab-4a50-a0fe-f62c1ad76961.mov

- When you try a regular drag and drop between folders (non breadcrumb) I've noticed the move success toast elongates to the full screen (but I think it's related to these changes as I can't reproduce this on stage). 

https://user-images.githubusercontent.com/3982665/148283513-beb2114c-e4e0-45fd-b5dc-d0cb39032756.mov

- I managed to somehow get the folder name to appear in the blue element that appeared at the bottom of the screen. 

https://user-images.githubusercontent.com/3982665/148283767-5b610c72-55de-46af-85be-2dbe252eb36e.mov

2022-01-06 11:00 UTC, Tbaut commented
There are weird CSS quirks indeed in the preview, but not when you build the branch locally (also there's no funky animation). I cleared the cache from render.com and redeployed. Should be live soon.

I can't reproduce the issue I had before, and from what Andrew saw, I can see the issue with moving to the folder it's already in, we should prevent this if possible

2022-01-06 16:45 UTC, Tbaut reviewed
I won't lie, the useDrop is pretty magical to me still as I've never played with it. My comments on the code are therefore on everything else :D

2022-01-06 16:45 UTC, Tbaut commented on packages/common-components/src/Breadcrumb/Breadcrumb.tsx
> +        {!crumb.component ?  <div
This logic is repeated 3 times in this component, and very much looks like the `FolderBreadCrumb` component to me beside some more logic. Any way we can reuse it?

Unrelated to the above comment, we don't particularly need the ternary here,  `crumb.component || <div>...</div>` would do the job, although it's maybe not as easy to read. Having the `?` at the beginning of a line is something I'm trying to enforce too :D

2022-01-06 16:45 UTC, Tbaut commented on packages/common-components/src/Breadcrumb/Breadcrumb.tsx
> +            onClick={() => (crumb.onClick ? crumb.onClick() : null)}
No need for the ternary here either
```suggestion
            onClick={() => crumb.onClick ? crumb.onClick()}
```

2022-01-06 16:45 UTC, Tbaut commented on packages/common-components/src/Breadcrumb/Breadcrumb.tsx
> +            !crumb.component ?  <div
This is one of the repetition

2022-01-06 16:45 UTC, Tbaut commented on packages/common-components/src/Breadcrumb/Breadcrumb.tsx
> +          {lastCrumb.component ? <div
and this is the 3rd one.

2022-01-06 16:45 UTC, Tbaut commented on packages/common-components/src/Breadcrumb/Breadcrumb.tsx
> +            onClick={() => (homeOnClick ? homeOnClick() : null)}
```suggestion
            onClick={() => homeOnClick && homeOnClick()}
```

2022-01-06 16:45 UTC, Tbaut commented on packages/files-ui/src/Utils/pathUtils.ts
> +// "/path/to/this" -> ["path", "to", "this"]
If I'm not mistaking, should update the example to something like
```suggestion
// [] -> "/"
// ["path", "to", "this"] => "/path/to/this"
```

2022-01-06 18:20 UTC, tanmoyAtb commented on packages/common-components/src/Breadcrumb/Breadcrumb.tsx
> +            !crumb.component ?  <div
Sorry about these, typing habits !
We'll need to find a way of formatting these with eslint.

2022-01-06 18:26 UTC, tanmoyAtb commented
Alright I've updated The current folder in breadcrumb to not accept drops!

But the breadcrumbs breaking up is a serious issue. Look at this one. This happens when you build it even locally.

<img width="1389" alt="Screenshot 2022-01-07 at 12 14 30 AM" src="https://user-images.githubusercontent.com/10713353/148431653-f19edcf1-35e8-441a-b58e-6b88c4b92962.png">
!

This is the first time we are trying to pass dynamic react components into the common-components as prop. And what happens is `JSS`  re initialises classnames to the dynamic component. 
The passed in breadcrumbs have `jss1` and `jss2` which are existing classnames which are injecting their styles !!!!!

I found this thread on the `jss` repo.
https://github.com/cssinjs/jss/issues/1458

A couple of hacky solutions in my mind but nothing concrete.

2022-01-07 10:50 UTC, Tbaut commented
Wow this is wild. One thing that crossed my mind and you prob thought about, what if we prevent the classes from having generated names, and actually go with our own naming like: `className={clsx{classes.duplicated, "unique-identifier"}}` and then
```
{
  duplicated: {
    "&.unique-identifier" : {
      ...
    }
  }
}
```

2022-01-08 16:57 UTC, tanmoyAtb commented
> Wow this is wild. One thing that crossed my mind and you prob thought about, what if we prevent the classes from having generated names, and actually go with our own naming like: `className={clsx(classes.duplicated, "unique-identifier")}` and then
> 
> ```
> {
>   duplicated: {
>     "&.unique-identifier" : {
>       ...
>     }
>   }
> }
> ```

This would have worked, Yes !
But I found the solution in the material docs:
https://mui.com/styles/api/
https://github.com/mui-org/material-ui/issues/11843

The PR seems to be in order now !

2022-01-10 14:14 UTC, Tbaut approved these changes
Played again with it, including moving and uploading files, and it worked like a charm :tada: 
The code looks neat too, just left a small comment for a nit.

2022-01-10 14:14 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
> +            }
Just a nit to have the ? and : at the beginning of the line, and closing all the } and ) on 1 line.
```suggestion
              component: (i < crumbs.length - 1)
                ? <FolderBreadcrumb
                  folderName={crumb.text}
                  onClick={crumb.onClick}
                  handleMove={(item) => {
                    moveItems && crumb.path && moveItems(item.ids, crumb.path)
                    setSelectedItems([])
                  }}
                  handleUpload={(item) => handleUploadOnDrop &&
                  crumb.path &&
                  handleUploadOnDrop(item.files, item.items, crumb.path)}
                />
                : null
            }))}
```

2022-01-10 21:34 UTC, asnaith commented
Awesome work Tanmoy, I can't see any of the previous weirdness and the feature is working great for me too

2022-01-10 21:34 UTC, asnaith approved these changes

2022-01-11 10:17 UTC, merged