Notifications context
ChainSafe/files-ui pull request #1839
Opened 2022-01-03 16:40 UTC by tanmoyAtb

closes #1818

---
Submission checklist: 

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode 
- [x] Components / elements inspected in dark mode

2022-01-04 11:55 UTC, Tbaut requested changes

2022-01-04 11:55 UTC, Tbaut commented on packages/files-ui/src/Components/Layouts/AppHeader.tsx
> +                  notifications={notifications}
This doesn't need to be passed as a prop, we could use the `notifications` from the context directly in the `NotificationDropdown` component and not have any prop on this component.

2022-01-04 11:55 UTC, Tbaut commented on packages/files-ui/src/Contexts/NotificationsContext.tsx
> +  const addNotification = (notification: Omit<Notification, "id">) => {
we should  use `useCallback` here to prevent useless re-rendering.

2022-01-04 11:55 UTC, Tbaut commented on packages/files-ui/src/Contexts/NotificationsContext.tsx
> +    throw new Error("useNotifications must be used within a BillingProvider")
```suggestion
    throw new Error("useNotifications must be used within a NotificationsProvider")
```

2022-01-04 11:55 UTC, Tbaut commented on packages/files-ui/src/Contexts/NotificationsContext.tsx
> +      id: (notifications.length + 1).toString(),
I think we shouldn't have the index as the id, for several reasons:
- this info is accessible easily, it's the index, no need to have an id for this
- we could have similar ids if we don't take care of this. E.g I just created a "create" and a "delete" button, with the logic that I delete the first notification in the array. If I create 2 notifications, remove 1, and create another, I end up with 2 notifications with the id `2`.

I'd go ahead and leave the `addNotification` accept a `Notification` as param, without the `Omit`, and let the logic about the `id` be handled by the notification creator. This has also the positive effect that the creator knows the notification id beforehand, and can have logic such as `onClick` removing the right notification, or marking it as read etc.

lmk if I'm not clear.

2022-01-04 15:40 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Layouts/AppHeader.tsx
> +                  notifications={notifications}
Pulling from contexts from inside the components in `elements` folder feels odd to me. Keeping these as separate makes for better reusability IMO.

2022-01-04 15:47 UTC, tanmoyAtb commented on packages/files-ui/src/Contexts/NotificationsContext.tsx
> +      id: (notifications.length + 1).toString(),
Ahh, thats a great example. I should have thought of this!!

So, About passing the `id`, I think it's better to create the `id` in the context. Making the notification creator worry about the `id` adds extra concern there. We can return the `id` from `addNotification` method. this is sth we're doing in `ToastsContext`.

To create the `id`s, we can either use `uuid` as we're doing with `toasts`, or 
we can increment the previous id.

What do you think ?

2022-01-04 20:25 UTC, Tbaut commented on packages/files-ui/src/Contexts/NotificationsContext.tsx
> +      id: (notifications.length + 1).toString(),
Agreed, then we can return the id upon creation, for things like "mark as read" or "delete" we'll need to keep this id in the state somewhere.

2022-01-06 04:44 UTC, tanmoyAtb commented on packages/files-ui/src/Contexts/NotificationsContext.tsx
> +      id: (notifications.length + 1).toString(),
Updated to work with uuid and return the id.

2022-01-06 10:35 UTC, Tbaut commented on packages/files-ui/src/Components/Layouts/AppHeader.tsx
> +                  notifications={notifications}
I won't fight it, but I'm not sure I agree with that. Contexts are specifically used to avoid props drilling. We have components in the `Elements` directory that pull some context state as well such as `InvoiceLines`, `MnemonicForm`. I get your point in that it eases re-usability, but I don't see the Notification dropdown being reused, it's very specific.

2022-01-06 10:36 UTC, Tbaut approved these changes

2022-01-06 15:05 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Layouts/AppHeader.tsx
> +                  notifications={notifications}
Cool, I realise we're already using from the contexts in elements. Made the updates 👍

2022-01-06 18:31 UTC, merged