Crypto Payment
ChainSafe/files-ui pull request #1844
Opened 2022-01-07 15:59 UTC by FSM1

closes #1782

---
Submission checklist: 

#### Layout
- [x] Change looks good in the desktop web ui
- [ ] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode 
- [ ] Components / elements inspected in dark mode

2022-01-10 14:26 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
new line

2022-01-10 15:17 UTC, Tbaut requested changes
Went through the code, and played a bit, looks great already! Left a couple comments.

2022-01-10 15:17 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ConfirmPlan.tsx
> +                USDC, BTC or ETH
no Dai?
```suggestion
                DAI, USDC, ETH or BTC
```

2022-01-10 15:17 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/CryptoPayment.tsx
> +  CopyIcon, DaiIcon,
```suggestion
  CopyIcon,
  DaiIcon,
```

2022-01-10 15:17 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/CryptoPayment.tsx
> +      navigator.clipboard.writeText(cryptoPayment.payment_methods.find(p => p.currency === selectedCurrency)?.address || "")
this line is repeated in onCopyAmount and in the rendered component, should we get this selectedPaymentMethod in a useMemo and re-used every time?

2022-01-10 15:17 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/CryptoPayment.tsx
> +  const iconMap: {[key: string]: React.FC<any>} = {
we can have these `iconMap` adn `symbolMap` outside of the component to prevent useless re-rendering.

2022-01-10 15:17 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/PaymentMethodSelector.tsx
> +  onSelectPaymentMethod: (paymentMethod: "creditCard" | "crypto") => void
We should use the `PaymentMethod` type here.

2022-01-10 15:17 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/PaymentMethodSelector.tsx
> +            <Trans>Go Back</Trans>
that's the only one with a big B otherwise, I'd say we should change them all or nothing.
```suggestion
            <Trans>Go back</Trans>
```

2022-01-10 15:17 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/CryptoPayment.tsx
> +  const isBalanceSufficient = useMemo(() => {
There's something missing, I changed the account midway, with an account that has enough ETH to pay, and it still shows "insufficient funds"

2022-01-10 15:17 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/CryptoPayment.tsx
> +}: ICryptoPayment) => {
```suggestion
const CryptoPayment = ({goBack,planPrice}: ICryptoPayment) => {
```

2022-01-11 15:56 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
>              setSlide("select")
any reason to go back to `slide` and not `planDetails` ?

2022-01-11 16:00 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ConfirmPlan.tsx
> +          </div>
```suggestion
          <div className={classes.pushRightBox} />
```

2022-01-11 16:06 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/CryptoPayment.tsx
> +    filesApiClient.updateSubscription(currentSubscription.id, {
I'd love to have a loader while the update request is going through.

2022-01-11 16:12 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/CryptoPayment.tsx
> +        // TODO Set loading state here
Might as well have this in !

2022-01-11 16:49 UTC, tanmoyAtb reviewed
Overall implementation looks great and well connected. 
Left some comments. It would be great to have the loaders in place. 

Some of the UI could some spacing in between,
between QR code and text,
<img width="328" alt="Screenshot 2022-01-11 at 10 23 34 PM" src="https://user-images.githubusercontent.com/10713353/148982356-77b28a27-521a-4925-b637-512b8b859c5b.png">

below the select cryptocurrency label,
<img width="467" alt="Screenshot 2022-01-11 at 10 29 58 PM" src="https://user-images.githubusercontent.com/10713353/148982530-e04104f9-a653-4c9b-b135-9f1162d6a12d.png">

The dark mode and mobile views need some tweaks. 

One thing that happens, 
Once I initialize a crypto payment, if I go through the select plan again, I get the `Failed to create a charge` error.  We should probably disable plan change while an invoice is pending. Ok to have this in scope of the previous invoices issue #1829

2022-01-12 11:47 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/CryptoPayment.tsx
> +  const isBalanceSufficient = useMemo(() => {
hmmm, I tested this exact flow with both ETH and DAI and these worked well. The ETH balance does depend on having an active Blocknative API key as this value is provided by their API. Will need to do some more digging to try and replicate this.

2022-01-12 14:54 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/CryptoPayment.tsx
> +        // TODO Set loading state here
also done

2022-01-13 15:06 UTC, tanmoyAtb approved these changes
Overall looks good to go ! 🎉

2022-01-13 17:25 UTC, Tbaut requested changes
I was on the Plan 2 out of 3 (monthy payment), and to test the crypto payment I click on the plan 3.
Now I never have the option to pay annually. Isn't that an issue?


https://user-images.githubusercontent.com/33178835/149379256-9b41a8bb-7fcd-4776-9d7e-d6beee6eda8c.mp4

2022-01-13 17:32 UTC, Tbaut commented
Yeah there's something very weird, the plan 3 doesn't allow the annual/monthly payment :shrug: The plan 2 does.

https://user-images.githubusercontent.com/33178835/149380015-e1ec36ba-77c0-431d-bec7-5a06f615064b.mp4

2022-01-13 17:43 UTC, Tbaut commented
> Once I initialize a crypto payment, if I go through the select plan again, I get the Failed to create a charge error. We should probably disable plan change while an invoice is pending. Ok to have this in scope of the previous invoices issue #1829

I ran into this too.

2022-01-13 17:54 UTC, Tbaut commented
The dark view looks good, but the mobile view modal is to wide and on iphone 11 pro, or Galaxy S20 (pretty recent phone I believe) it's not scaling well:
![image](https://user-images.githubusercontent.com/33178835/149383224-04d3d1be-d72d-430a-9406-09aba4ac1a90.png)
![image](https://user-images.githubusercontent.com/33178835/149383250-a66c1c0d-1881-4af4-8253-9c938e6abb65.png)

2022-01-13 18:01 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/CryptoPayment.tsx
> +  const isBalanceSufficient = useMemo(() => {
Can't reproduce :)

2022-01-13 18:12 UTC, Tbaut reviewed
A couple nits that the linter doesn't figure out :roll_eyes:

2022-01-13 18:12 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/CryptoPayment.tsx
> +                  size={128} />
```suggestion
                  size={128}
                />
```

2022-01-13 18:12 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/CryptoPayment.tsx
> +                  </Button>})}
```suggestion
                  </Button>
                })}
```

2022-01-13 18:12 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/CryptoPayment.tsx
> +                onClick={onCopyAmount}>
```suggestion
                onClick={onCopyAmount}
              >
```

2022-01-13 18:12 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/CryptoPayment.tsx
> +            variant="secondary" />
```suggestion
            variant="secondary"
          />
```

2022-01-13 18:12 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/CryptoPayment.tsx
> +                    className={classes.currencyButton}>
```suggestion
                    className={classes.currencyButton}
                  >
```

2022-01-13 18:12 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/CryptoPayment.tsx
> +        // TODO Set loading state here
```suggestion
```

2022-01-14 15:28 UTC, FSM1 commented
> The dark view looks good, but the mobile view modal is to wide and on iphone 11 pro, or Galaxy S20 (pretty recent phone I believe) it's not scaling well

I suspect this only happens when the viewport size changes during rendering. At least it seems like it is fine when the page is rendered with mobile emulation on from the start:
![image](https://user-images.githubusercontent.com/12774278/149540755-dff26711-6822-42e5-a9b3-0f35c7ae7ed8.png)

2022-01-14 15:29 UTC, FSM1 commented
> I was on the Plan 2 out of 3 (monthy payment), and to test the crypto payment I click on the plan 3. Now I never have the option to pay annually. Isn't that an issue?

This is merely a side-effect of the daily/annual selector, since the Premium plan does not have a daily price, which is what is being looked for by the code... Once we revert back to the annual period this should return to normal.

2022-01-14 15:46 UTC, Tbaut commented
>  suspect this only happens when the viewport size changes during rendering. At least it seems like it is fine when the page is rendered with mobile emulation on from the start:

I just tried, and it's the same, try wit the Galaxy S20 **non** ultra, you'll see

2022-01-14 15:54 UTC, FSM1 commented
> > suspect this only happens when the viewport size changes during rendering. At least it seems like it is fine when the page is rendered with mobile emulation on from the start:
> 
> I just tried, and it's the same, try with the Galaxy S20 **non** ultra, you'll see

Ahhh great, brave removed a bunch of devices from their emulation. Either case, I seem to have figured out what was causing these glitches and resolved...

2022-01-14 17:15 UTC, Tbaut commented
Oops the cross isn't happy with that last change
![image](https://user-images.githubusercontent.com/33178835/149556931-d6e1d3c6-6689-442d-b5f0-8eedf90d7f53.png)

2022-01-17 14:00 UTC, FSM1 commented
> Oops the cross isn't happy with that last change, and also the clock for the remaining time I think is messed up. ![image]

I think I have finally nailed down the styling weirdness... @Tbaut would appreciate your keen eye on this one 🙏🏼

2022-01-17 17:48 UTC, Tbaut approved these changes
Absolutely, you nailed it and I couldn't find any other issue!

2022-01-18 12:54 UTC, merged