Pay Invoice
ChainSafe/files-ui pull request #1866
Opened 2022-01-19 14:59 UTC by FSM1

closes #1829

---
Submission checklist: 

   

#### Layout
- [ ] Change looks good in the desktop web ui
- [ ] Change looks good in the mobile web ui

#### Theme
- [ ] Components / elements inspected in light mode 
- [ ] Components / elements inspected in dark mode

2022-01-25 14:04 UTC, tanmoyAtb approved these changes
Working great 💯 . just a couple of nits

2022-01-25 16:15 UTC, Tbaut requested changes

2022-01-25 16:15 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentPlan.tsx
> +    changePlanButton: {
That's an old thing that should go away isn't it?

2022-01-25 16:15 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/SelectPlan.tsx
> +                {isPendingInvoice && isCurrentPlan && <Button
Shouldn't we remove this all? This is some code I added and ended up removing.

2022-01-25 20:10 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentPlan.tsx
> +    changePlanButton: {
this class seems to still be in use

2022-01-25 20:11 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/SelectPlan.tsx
> +                {isPendingInvoice && isCurrentPlan && <Button
agreed, incorrectly merged this in...

2022-01-25 21:34 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentPlan.tsx
> +    changePlanButton: {
no, I added it in for the loader to have a margin with the button, but we removed that part.

2022-01-25 21:35 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentPlan.tsx
> +
```suggestion
```

2022-01-25 21:40 UTC, Tbaut reviewed
Sorry, my previously added then removed code causes a lot of headaches :D

2022-01-25 21:40 UTC, Tbaut commented on packages/files-ui/src/locales/fr/messages.po
> +msgstr ""
```suggestion
msgstr "Aucune facture trouvée"
```

2022-01-25 21:40 UTC, Tbaut commented on packages/files-ui/src/locales/fr/messages.po
> +msgstr ""
We can keep that in
```suggestion
msgstr "Montant total"
```

2022-01-25 21:40 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
> +          onShowCryptoOutstandingPayment={() => setSlide("cryptoPayment")}
I think this is also legacy stuff that should go.
```suggestion
```

2022-01-25 21:40 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/SelectPlan.tsx
> +const SelectPlan = ({ className, onSelectPlan, plans, onShowCryptoOutstandingPayment }: ISelectPlan) => {
and this
```suggestion
const SelectPlan = ({ className, onSelectPlan, plans }: ISelectPlan) => {
```

2022-01-25 21:40 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/SelectPlan.tsx
> +  onShowCryptoOutstandingPayment: () => void
and this
```suggestion
```

2022-01-26 09:46 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentPlan.tsx
> +    changePlanButton: {
ahhh ok that makes sense. nuking...

2022-01-26 10:33 UTC, Tbaut reviewed
A couple more nits, and we'll be good to go :)

2022-01-26 10:33 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx
> +        Please complete payment of the following outstanding invoices in order to avoid account suspension.
I think that Trans flew away somehow
```suggestion
        <Trans>Please complete payment of the following outstanding invoices in order to avoid account suspension</Trans>
```

2022-01-26 10:33 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx
> +        payInvoice={() => setPayInvoiceModalVisible(true)}/>
```suggestion
        payInvoice={() => setPayInvoiceModalVisible(true)}
      />
```

2022-01-26 10:33 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx
> +        />)
```suggestion
        isPayInvoiceModalVisible && <PayInvoiceModal
          onClose={() => setPayInvoiceModalVisible(false)}
        />
```

2022-01-27 10:38 UTC, Tbaut approved these changes
Let's merge and keep an eye on `isPendingInvoice` and `pendingCryptoInvoice` that are somewhat overlapping.

2022-01-27 10:38 UTC, merged