Proration and credit calculated amounts
ChainSafe/files-ui pull request #1878
Opened 2022-01-25 14:24 UTC by tanmoyAtb

closes #1869

---
Submission checklist: 

   

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode 
- [x] Components / elements inspected in dark mode

2022-01-27 10:36 UTC, Tbaut reviewed
I went briefly though the code, lgtm, I'll play with it now.

2022-01-27 10:36 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ConfirmPlan.tsx
> +    }).then(setCheckSubscriptionUpdate).catch(console.error)
some air
```suggestion
    if (!currentSubscription) return

    filesApiClient.checkSubscriptionUpdate(currentSubscription?.id, {
      payment_method: paymentMethod === "creditCard" ? "stripe" : "crypto",
      price_id: planPrice.id
    })
    .then(setCheckSubscriptionUpdate)
    .catch(console.error)
```

2022-01-27 11:46 UTC, Tbaut approved these changes
Looking good, it's simple and does the job well IMHO! Left some more nits.

2022-01-27 11:46 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ConfirmPlan.tsx
> +              (<Trans>Previous balance</Trans> : {planPrice.currency} {checkSubscriptionUpdate.amount_balance.toFixed(2)})
```suggestion
              (<Trans>Previous balance</Trans>: {planPrice.currency} {checkSubscriptionUpdate.amount_balance.toFixed(2)})
```

2022-01-27 11:46 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ConfirmPlan.tsx
> +
```suggestion
```

2022-01-27 11:46 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ConfirmPlan.tsx
>              loading={loadingChangeSubscription}
I'd add it here as well, wdyt?
```suggestion
            loading={loadingChangeSubscription || !checkSubscriptionUpdate}
```

2022-01-27 23:16 UTC, asnaith commented
This seems to remember only the last payment when performing the calculations. Is this how it should work? I'm finding it a bit confusing so I'm sure users will too. 

I'm not sure this is a genuine flow that someone would do but currently - 

If I purchase a premium plan for $199 then if I downgrade to a standard plan then I don't owe anything because I paid more for the premium. However, if I then try to upgrade the standard plan back to premium I will have to pay an additional $100 as the standard account was only $99...but really the account should still have another $100 associated with it and no cost to go back to premium because the initial payment was $199.  

Similarly, I purchase an annual standard plan for $99 and then I switch to a monthly premium plan the cost is $0.00 but it's not clear to me if the previously paid $99 will mean I don't get billed for the first 5 months when on the premium plan. 

Hope this makes sense!

2022-01-28 09:32 UTC, Tbaut commented
I had this thought too regarding the fact that we don't say anything about future invoices that might be impacted by the current account balance, but I figured this is something that the user intuitively understands, when telling them how much their account balance is.

I had a somewhat similar "issue" that my balance seemed to have been reset when switching to the free plan, but I guess this might be something to discuss with the api team.

2022-01-28 10:34 UTC, tanmoyAtb commented
@asnaith Thanks for bringing this up. I noticed the first flow mismatch as well. However the calculations are fully done on the API side. Can you post the two flows on the files channel and we can discuss it with the team. 

also we're only getting the next payment amounts from the API. IMO thats sufficient for the user to understand that the next few payments will be adjusted.

2022-01-31 12:56 UTC, FSM1 requested changes
Works great. The only thing I would change here is some of the labels - instead of 
![image](https://user-images.githubusercontent.com/12774278/151797163-4a202121-17ce-4f70-b8eb-1a61a578706e.png)

I would display the following:
```
Plan price: $ 19.99
Credit used: $9.99
Payment Due: $10.00
```

2022-01-31 15:12 UTC, tanmoyAtb commented
> Works great. The only thing I would change here is some of the labels - instead of ![image](https://user-images.githubusercontent.com/12774278/151797163-4a202121-17ce-4f70-b8eb-1a61a578706e.png)
> 
> I would display the following:
> 
> ```
> Plan price: $ 19.99
> Credit used: $9.99
> --------------------
> Payment Due: $10.00
> ```

@FSM1 do you mean `credit used` or `credit remaining` ?

2022-01-31 15:48 UTC, FSM1 commented
> > Works great. The only thing I would change here is some of the labels - instead of ![image](https://user-images.githubusercontent.com/12774278/151797163-4a202121-17ce-4f70-b8eb-1a61a578706e.png)
> > I would display the following:
> > ```
> > Plan price: $ 19.99
> > Credit used: $9.99
> > --------------------
> > Payment Due: $10.00
> > ```
> 
> @FSM1 do you mean `credit used` or `credit remaining` ?

I was just thinking of that... how about we go for something like the:

```
Plan price: $ 19.99
Credit used: $9.99
--------------------
Payment Due: $10.00
Credit remaining: $ 0 (Only display if there is still credit remaining - i.e. Payment Due === 0
```

2022-01-31 16:52 UTC, tanmoyAtb commented
> > > Works great. The only thing I would change here is some of the labels - instead of ![image](https://user-images.githubusercontent.com/12774278/151797163-4a202121-17ce-4f70-b8eb-1a61a578706e.png)
> > > I would display the following:
> > > ```
> > > Plan price: $ 19.99
> > > Credit used: $9.99
> > > --------------------
> > > Payment Due: $10.00
> > > ```
> > 
> > 
> > @FSM1 do you mean `credit used` or `credit remaining` ?
> 
> I was just thinking of that... how about we go for something like the:
> 
> ```
> Plan price: $ 19.99
> Credit used: $9.99
> --------------------
> Payment Due: $10.00
> Credit remaining: $ 0 (Only display if there is still credit remaining - i.e. Payment Due === 0
> ```

Looks relatable to me, I'll update this once API makes the changes for `credit remaining` and updates the field names.

2022-02-11 14:03 UTC, tanmoyAtb commented
Hey guys, The PR is good to be reviewed IMO. As long as the terminology looks relatable to you.

2022-02-11 14:51 UTC, FSM1 approved these changes

2022-02-11 14:58 UTC, merged