CIDs paging
ChainSafe/files-ui pull request #1889
Opened 2022-01-28 11:31 UTC by tanmoyAtb

closes #1325

---
Submission checklist: 

   

#### Layout
- [ ] Change looks good in the desktop web ui
- [ ] Change looks good in the mobile web ui

#### Theme
- [ ] Components / elements inspected in light mode 
- [ ] Components / elements inspected in dark mode

2022-04-14 15:15 UTC, FSM1 requested changes
The code looks really great. The only comment I have is when switching pages, both the buttons become disabled (which is expected), and a spinner appears in both of the page buttons  (this is less expected). 

Not sure what the solution is here - either show a spinner only on the button that was clicked, or do not have a spinner on the button during the request at all.

https://user-images.githubusercontent.com/12774278/163420485-9a84fe67-bc7c-416b-8c36-90663175e032.mp4

2022-04-15 08:18 UTC, tanmoyAtb commented
> The code looks really great. The only comment I have is when switching pages, both the buttons become disabled (which is expected), and a spinner appears in both of the page buttons (this is less expected).
> 
> Not sure what the solution is here - either show a spinner only on the button that was clicked, or do not have a spinner on the button during the request at all.
> 
>  CIDs.-.Chainsafe.Storage.-.Brave.2022-04-14.17-11-51.mp4

All right, we're handling to show spinner only on the next or previous button now. 👍

2022-04-18 03:23 UTC, asnaith commented
Hey @tanmoyAtb, I found an issue that I've demonstrated in the video below. I had two pages of cids but after sorting one of the columns the paging system broke. 

https://user-images.githubusercontent.com/3982665/163749499-d22c3df9-42ef-404c-87f1-9aa515a1dc26.mov

2022-04-18 04:29 UTC, tanmoyAtb commented
> Hey @tanmoyAtb, I found an issue that I've demonstrated in the video below. I had two pages of cids but after sorting one of the columns the paging system broke.
> 
>  breaking.paging.mov

Ahh yes, that makes sense, That's a great catch @asnaith. I'll be looking into it.

2022-04-18 15:40 UTC, tanmoyAtb commented
> Hey @tanmoyAtb, I found an issue that I've demonstrated in the video below. I had two pages of cids but after sorting one of the columns the paging system broke.
> 
>  breaking.paging.mov

The sort directions should work properly now. @asnaith

2022-04-19 15:07 UTC, Tbaut approved these changes
I've had a hard time concentrate to properly understand the logic happening here, I'm particularly confused by the dates, I bet this is what we base our sorting on, rather than any id, also flags like `isPreviousPin`, were confusing maybe it's a naming thing.
In any case I made a couple suggestions, but playing with it was flawless :rocket:

2022-04-19 15:07 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/CidsPage.tsx
> +      {!!pins.length &&
I feel we should hide it when there's just 1 page.
```suggestion
      {!!pins.length && pins.length > 1 &&
```

2022-04-19 15:07 UTC, Tbaut commented on packages/storage-ui/src/Contexts/StorageContext.tsx
> +      pinsParams.searchedName || undefined,
I guess this should work as well
```suggestion
      pinsParams.searchedName,
```

2022-04-19 15:07 UTC, Tbaut commented on packages/storage-ui/src/Contexts/StorageContext.tsx
> +      }
This is very very verbose and I'm not sure I can follow everything. I tried to sum it up here, but I'm not 100% sure I nailed it.

```js
const showNextOrPrevious = pinsResult.results?.length && pinsResult.count &&  pinsResult.results.length < pinsResult.count

pinsParams.pinsRange.before
  ? setIsNextPins(showNextOrPrevious)
  : setIsPreviousPins(showNextOrPrevious)
```

2022-04-19 15:23 UTC, tanmoyAtb commented on packages/storage-ui/src/Contexts/StorageContext.tsx
> +      }
You're right, Didn't realise I ended up with the same logic for both cases in the end, with the logic changing so many times. Going to work around this part.

2022-04-19 15:29 UTC, tanmoyAtb commented
> I've had a hard time concentrate to properly understand the logic happening here, I'm particularly confused by the dates, I bet this is what we base our sorting on, rather than any id, also flags like `isPreviousPin`, were confusing maybe it's a naming thing. In any case I made a couple suggestions, but playing with it was flawless 🚀

Agreed, Going to improve the variable names here. 

So with the dates. There has been a lot of back and forth with this logic to get here and its a bit tricky.
To fetch next pins -> we pass a `before` date based on the oldest pin date available in view, we fetch them in date `descending` order, so the we get pins closest to the `before` date. 
For previous pins -> We pass an `after` date based on the latest pin in view, and fetch in date `ascending` order, again to get the latest pins closest the the `after` date.

2022-04-25 14:45 UTC, FSM1 approved these changes

2022-04-25 15:00 UTC, merged