initial testing
ChainSafe/files-ui pull request #1900
Opened 2022-02-01 00:22 UTC by FSM1

closes #1884

---
Submission checklist: 

   

#### Layout
- [ ] Change looks good in the desktop web ui
- [ ] Change looks good in the mobile web ui

#### Theme
- [ ] Components / elements inspected in light mode 
- [ ] Components / elements inspected in dark mode

2022-02-07 13:32 UTC, Tbaut commented
lint and lgtm-com are complaining a little :D

2022-02-07 13:50 UTC, FSM1 commented
> lint and lgtm-com are complaining a little :D

not anymore >.<

2022-02-07 14:51 UTC, Tbaut requested changes
Found some conflicts resolution gone bad!

2022-02-07 14:51 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/ConfirmPlan.tsx
> +import { Button, CreditCardIcon, Divider, formatBytes, Typography } from "@chainsafe/common-components"
Same
```suggestion
import { Button, InfoCircleIcon, CreditCardIcon, Divider, formatBytes, Typography } from "@chainsafe/common-components"
```

2022-02-07 14:51 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/ConfirmPlan.tsx
> +      {subscriptionErrorMessage &&
This should stay, that's a merge conflict gone wrong I think
```suggestion
      {paymentMethod === "crypto" && <div className={classes.rowBox}>
        <Typography
          variant="body1"
          component="p"
          className={classes.warningText}
        >
          <InfoCircleIcon className={classes.icon} />
          <Trans>
            Once you proceed, your account is expected to make a payment within 60 minutes. If no payment is received
            , your plan will not change.
          </Trans>
        </Typography>
      </div>
      }
      {subscriptionErrorMessage &&
```

2022-02-07 14:51 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx
> -          <Link to={ROUTE_LINKS.BillingHistory}>
The "all invoice button is gone now?

2022-02-07 21:45 UTC, asnaith commented
Nice. The error message looks good and pay now button on the billing history page now returns the user to the payment flow. 

I noticed an issue with the error message being retained after leaving and returning to the modal but I realized it was a pre-existing issue so I've created a separate issue for that (#1922)

2022-02-07 21:46 UTC, asnaith approved these changes

2022-02-08 11:19 UTC, Tbaut reviewed
Just looked at the code, found a couple nits, I'll play with it now and check for https://github.com/ChainSafe/ui-monorepo/issues/1922

2022-02-08 11:19 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx
> +      {!invoiceToPay
I think an early return such as `if (!invoiceToPay) return null` would be nicer, and than have 1 ternary would work

2022-02-08 11:19 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx
> +      {(isPendingInvoice || invoices?.find(i => i.status === "open")) &&
I've seen this in the billing context too, should we have a boolean in the context `isOpenInvoice` with this?

2022-02-08 11:19 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
> +import { t } from "@lingui/macro"
```suggestion
import { t } from "@lingui/macro"

```

2022-02-08 11:42 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx
> +      {(isPendingInvoice || invoices?.find(i => i.status === "open")) &&
not sure I get what you mean here

2022-02-08 12:28 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx
> +      {(isPendingInvoice || invoices?.find(i => i.status === "open")) &&
sorry, I mean `invoices?.find(i => i.status === "open")`. This is an info that is recalculated elsewhere (I've see the same snippet in the `BillingContext`). So I think we should expose a `isOpenInvoice` flag in the context to reuse it.

2022-02-08 13:18 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx
> +      {(isPendingInvoice || invoices?.find(i => i.status === "open")) &&
updated though I chose not to use a flag, but rather expose the entire object since the invoice details are used in the billing context. I really don't see what this adds in terms of readability.

2022-02-08 13:50 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx
> +      {(isPendingInvoice || invoices?.find(i => i.status === "open")) &&
It's not that much about readability (it's prob. harder to read), I'd say it's more about reusing things. Having a complex expression in a `if`, and the fact that we had this exact expression elsewhere was what made me comment.

2022-02-08 13:50 UTC, Tbaut approved these changes
looks good, I'll push a PR right away for what Andrew found

2022-02-08 13:50 UTC, merged