New sharing design
ChainSafe/files-ui pull request #1927
Opened 2022-02-08 19:46 UTC by tanmoyAtb

closes #1908

---
Submission checklist: 

   

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode 
- [x] Components / elements inspected in dark mode

2022-02-09 13:07 UTC, Tbaut commented
Can you check the tests @tanmoyAtb Link and file sharing are legitimately failing

2022-02-09 14:51 UTC, Tbaut reviewed
This is very nice and working very well. I left a couple comments, the `CreateOrManage...` file is slowly getting out of hands with 650+ lines of codes. I wish we could some code to components (like each user line) to some lower-level component, passing around some props. This could be left for a refactoring later on. I see a lot of reader and writer specific code, although we could have somewhat generic functions handling both. and reducing a little the JSX, as it's barely readable (and don't get me wrong, it was already in a bad shape, this PR is not the 100% guilty one).

In any case, beside my comments below, we can leave that for a later refactoring.

2022-02-09 14:51 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/SharingLink.tsx
> -  if (isDeleting) {
Just curious why this was removed, was it jumping too much or some similar annoyance?

2022-02-09 14:51 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrManageSharedFolder.tsx
> +interface LinkMenuItems {
This is duplicated in `LinkList`. We should export it from there.

2022-02-09 14:51 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrManageSharedFolder.tsx
> +const readRights = t`view-only`
This as well is duplicated in `LinkList`. We should export it from there.

2022-02-09 14:51 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrManageSharedFolder.tsx
> +          Add users to shared folder
Translation is missing
```suggestion
          <Trans>Add users to shared folder</Trans>
```

2022-02-09 14:51 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrManageSharedFolder.tsx
> +          setSharedFolderWriters(sharedFolderWriters.filter((sr) => sr.value !== user.value))
nit: `sr` stands for sharedReader right? For this one we should have `sw` then to avoid any confusion

2022-02-09 14:51 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrManageSharedFolder.tsx
> +  const onUsernameChange = async (v: string) => {
Why is that async?

2022-02-09 14:51 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrManageSharedFolder.tsx
> +            onChange={(v) => onUsernameChange(v as string)}
This is weird, we shouldn't need such casting, a `{onUsernameChange}` should be fine isn't it?

2022-02-09 14:51 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrManageSharedFolder.tsx
> +        {sharedFolderReaders.map((sr) => <div
the list of readers and writers are basically the same, with subtle changes. Can we extract this into something generic, there's a lot of reused boilerplate code here.

2022-02-09 14:51 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrManageSharedFolder.tsx
> +    ) || []
If the writers array is empty, I'm pretty sure a map returns an empty array anyway. I tested it real quick and nothing crashed
```suggestion
    }))
```

2022-02-09 14:51 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrManageSharedFolder.tsx
>      ) || []
same here
```suggestion
    }))
```

2022-02-09 15:01 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/SharingLink.tsx
> -  if (isDeleting) {
Yes, exactly. Too many loaders and jumps appear on deleting. IMO, the current UX feels better.

2022-02-09 15:03 UTC, tanmoyAtb commented
> This is very nice and working very well. I left a couple comments, the `CreateOrManage...` file is slowly getting out of hands with 650+ lines of codes. I wish we could some code to components (like each user line) to some lower-level component, passing around some props. This could be left for a refactoring later on. I see a lot of reader and writer specific code, although we could have somewhat generic functions handling both. and reducing a little the JSX, as it's barely readable (and don't get me wrong, it was already in a bad shape, this PR is not the 100% guilty one).
> 
> In any case, beside my comments below, we can leave that for a later refactoring.

I agree with all of the points, I felt the file getting out of hand as well. I have some refactoring in mind that I'll add in this PR. The readers and writers part is something we had before, I'll see about merging them as well.  Checking on the tests as well.

2022-02-09 15:44 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrManageSharedFolder.tsx
> +            onChange={(v) => onUsernameChange(v as string)}
Yup, Had to fiddle with the types a bit, but this works better.

2022-02-10 20:43 UTC, FSM1 approved these changes
Great stuff @tanmoyAtb 🥇

2022-02-11 00:25 UTC, asnaith requested changes, later dismissed
Looks great @tanmoyAtb! Nice test fixes too @FSM1 👍

I made some minor suggestions but mainly requested a change to put `loginData` back to how it was before.

2022-02-11 00:25 UTC, asnaith commented on packages/files-ui/cypress/fixtures/loginData.ts
> +export const localHost = "https://files-ui-stage-pr-1927.onrender.com"
let's put this back :) 

```suggestion
export const localHost = "http://localhost:3000"
```

2022-02-11 00:25 UTC, asnaith commented on packages/files-ui/cypress/support/page-objects/modals/createSharedFolderModal.ts
> +  linkPermissionDropdown: () => cy.get("[data-testid=dropdown-title-link-permission-dropdown]"),
To remove the dupe "dropdown" in the identifier string

```suggestion
  linkPermissionDropdown: () => cy.get("[data-testid=dropdown-title-link-permission]"),
```

2022-02-11 00:25 UTC, asnaith commented on packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/LinkList.tsx
> +              testId="link-permission-dropdown"
We don't need to use "dropdown" here as it will be constructed with a "dropdown-" prefix when sent as a testId parameter (set up in `MenuDropdown.tsx`). 

The convention for identifiers that I've been following is to put the element type at the beginning. 

```suggestion
              testId="link-permission"
```

2022-02-11 00:25 UTC, asnaith commented on packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/PermissionsDropdown.tsx
> +              data-cy={testId && "menu-read"}
This is not being passed a `testId` from anywhere so can just be like this:

```suggestion
              data-cy="menu-read"
```

2022-02-11 00:25 UTC, asnaith commented on packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/PermissionsDropdown.tsx
> +              data-cy={testId && "menu-write"}
Same here too:

```suggestion
              data-cy="menu-write"
```

2022-02-11 11:17 UTC, Tbaut approved these changes
Great refactor, thanks a lot!
there are just some small nits found by Andrew, and we can merge :tada:

2022-02-11 11:35 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/PermissionsDropdown.tsx
> +              data-cy={testId && "menu-read"}
There is a testId passed in to Permission Dropdown [here](https://github.com/ChainSafe/ui-monorepo/blob/6b5756995235baf4b0dd4efe1ae685afe28e7d6d/packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/LinkList.tsx#L218).

This is done to prevent duplicates when `cy.get` is called. The permission dropdown is reused in CreateOrManageSharedFolder.

2022-02-11 12:44 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/PermissionsDropdown.tsx
> +              data-cy={testId && "menu-read"}
IIUC, the problem is that the same `PermissionDropdown` is used twice on the same modal, is that right? Then I'd build it as if it was an external component. So we use a `testId` prop, like we do here, but I'd change the `data-cy` to something like this:
 ```suggestion
              data-testid={`dropdown-permission-${testId}`}
```

2022-02-11 13:33 UTC, FSM1 commented on packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/PermissionsDropdown.tsx
> +              data-cy={testId && "menu-read"}
Yeah that's exactly the issue. Will implement a fix as described.

2022-02-11 14:51 UTC, Tbaut approved these changes
:rocket: 

Merging this one right away to see if creates conflicts with others

2022-02-11 14:52 UTC, merged