Hash icons in shared user list
ChainSafe/files-ui pull request #1945
Opened 2022-02-14 16:26 UTC by tanmoyAtb

closes #1928

---
Submission checklist: 

   

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode 
- [x] Components / elements inspected in dark mode

2022-02-14 17:45 UTC, Tbaut requested changes
The key for the `hashIcon` need to be the uuid, otherwise the icon don't match, e.g I have different icons in the manage modal, and in the overview

https://user-images.githubusercontent.com/33178835/153918001-94cf1d6f-ea8d-4243-9cb4-735efe470336.mp4

2022-02-14 18:55 UTC, tanmoyAtb commented
> The key for the `hashIcon` need to be the uuid I think, otherwise the icon don't match, e.g I have different icons in the manage modal, and in the overview
> 
>  sharing.mp4

hmm, yes, that would be better. 👍

2022-02-15 10:24 UTC, FSM1 approved these changes
Working really well, and looks great 💯

2022-02-15 15:07 UTC, tanmoyAtb commented
> The key for the `hashIcon` need to be the uuid I think, otherwise the icon don't match, e.g I have different icons in the manage modal, and in the overview
> 
>  sharing.mp4

Thanks for hint. PR is updated. All the hashicons now use `uuid`, user list, user dropdown and shared users in modal. 👍

2022-02-15 17:36 UTC, Tbaut approved these changes
Looking good now, I left a couple comments. Feel free to ignore

2022-02-15 17:36 UTC, Tbaut commented on packages/files-ui/src/Components/Elements/UserBubble.tsx
> +  showHashIcon?: boolean
To me this prop is redundant with the `hashIconValue`. Either both are set, or not isn't it?

2022-02-15 17:36 UTC, Tbaut commented on packages/files-ui/src/Components/Elements/SharedUsers.tsx
> +  const getUserLabels = useCallback((users: RichUserInfo[]) => {
That's somehow of a nit, but this function (and many other "label" variables), aren't only about labels any more. They are more about user display info. But I can close my eyes on this :D although having the return type defined would be nice I think. `interface UserDisplayInfo { displayName: string; uuid: string } `

2022-02-15 18:09 UTC, tanmoyAtb commented
> Looking good now, I left a couple comments. Feel free to ignore

Updates are in. :D

2022-02-15 18:10 UTC, merged