[Storage] Add warning when pinning a cid twice
ChainSafe/files-ui pull request #2027
Opened 2022-03-17 17:00 UTC by Tbaut

closes #1212

2022-03-17 22:28 UTC, asnaith approved these changes
Good solution for the scenario, warning over prevention makes sense :)

2022-03-18 08:11 UTC, tanmoyAtb requested changes
So i tried this approach ->
I copied a CID without the last character,
typed in the last character
but I did not get the warning.

While we are at it, On a UI note, I would prefer the CID modal to be wider than what we have.

2022-03-18 08:11 UTC, tanmoyAtb commented on packages/storage-ui/src/Components/Modules/AddCIDModal.tsx
> +    cid && setCid(cid?.toString())
This is preventing erasing the first character of the input. This should fix it.
```suggestion
    setCid(cid?.toString() || "")
```

2022-03-18 14:07 UTC, FSM1 commented on packages/storage-ui/src/Components/Modules/AddCIDModal.tsx
> +  }, [warnforDuplicatesCid])
```suggestion
  const checkForDuplicatesCid = useCallback(() => {
    searchCid(cid)
      .then((res) => {
        if(res && res.results?.length){
          setShowWarning(true)
        }
      })
  }, [cid, searchCid])

  const onCidChange = useCallback((cid?: string | number) => {
    setCidError("")
    setShowWarning(false)

    setCid(cid?.toString() || "")

    cidValidator
      .validate({ cid })
      .then(() => {
        setCidError("")
        checkForDuplicatesCid()
      })
      .catch((e: Error) => {
        setCidError(e.message)
      })
  }, [checkForDuplicatesCid])
```

2022-03-18 14:08 UTC, FSM1 commented on packages/storage-ui/src/Components/Modules/AddCIDModal.tsx
> +              <Trans>Warning: cid already pinned</Trans>
```suggestion
              <Trans>Warning: CID already pinned</Trans>
```

2022-03-18 14:08 UTC, FSM1 approved these changes
Just a few cosmetic changes, but working great otherwise 👍🏼

2022-03-18 14:32 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/AddCIDModal.tsx
> +              <Trans>Warning: cid already pinned</Trans>
:+1:

2022-03-18 14:32 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/AddCIDModal.tsx
> +  }, [warnforDuplicatesCid])
refactored that part :)

2022-03-18 14:33 UTC, Tbaut commented
Thanks Tanmoy and Mike. My logic was a little meh for the check. I re-implemented that in a nicer way. The problem you mentioned @tanmoyAtb is now fixed, great catch.

2022-03-18 14:50 UTC, Tbaut commented
BTW I agree with the modal style that's a little weird. I'll change that when adding a name together with https://github.com/ChainSafe/ui-monorepo/issues/2022

2022-03-21 14:39 UTC, tanmoyAtb approved these changes
Looking 💯

2022-03-21 14:47 UTC, merged