Header titles added
ChainSafe/files-ui pull request #2042
Opened 2022-03-24 18:49 UTC by tanmoyAtb

closes #1611

---
Submission checklist: 
No UI changes

2022-03-25 18:58 UTC, asnaith commented
There wasn't too much for me to test here but I did run through the screens listed on the issue on both desktop / mobile and everything visually looked as expected :)

2022-03-26 10:51 UTC, FSM1 approved these changes

2022-03-28 10:08 UTC, Tbaut reviewed
We are missing translation for the title, I just commented for some of them, but we'd need them for all.

2022-03-28 10:08 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
> +    return arrayOfPaths[arrayOfPaths.length - 1]
should we go safe here and make sure this never end-up being `arrayOfPaths[-1]`?
```suggestion
    return !!arrayOfPaths.length && arrayOfPaths[arrayOfPaths.length - 1]
```

2022-03-28 10:08 UTC, Tbaut commented on packages/files-ui/src/Components/Pages/BillingHistory.tsx
> +        <title>Billing history - Chainsafe Files</title>
Translation
```suggestion
        <title><Trans>Billing history - Chainsafe Files</Trans></title>
```

2022-03-28 10:08 UTC, Tbaut commented on packages/files-ui/src/Components/Pages/BinPage.tsx
> +      <title>Bin - Chainsafe Files</title>
Trans
```suggestion
      <title><Trans>Bin</Trans> - Chainsafe Files</title>
```

2022-03-28 14:34 UTC, tanmoyAtb commented
> We are missing translation for the title, I just commented for some of them, but we'd need them for all.

Thanks for that, Added the translation tags, I left out "Chainsafe Files" part for translations as we've kept it that way everywhere else

2022-03-31 00:24 UTC, Tbaut requested changes
Code looks good but when I logged into Files, on the render preview, I got an error:
> Helmet expects a string as a child of <title>. Did you forget to wrap your children in braces? ( <title>{``}</title> ) Refer to our API for more information.

I guess the Trans wasn't expected there. so we probably need {`${t`title`} - Chainsafe Files`} or something along this line

2022-03-31 17:02 UTC, tanmoyAtb commented
> Code looks good but when I logged into Files, on the render preview, I got an error:
> 
> > Helmet expects a string as a child of <title>. Did you forget to wrap your children in braces? ( <title>{``}</title> ) Refer to our API for more information.
> 
> I guess the Trans wasn't expected there. so we probably need {`${t`title`} - Chainsafe Files`} or something along this line

Thanks for saving this one, updates are in.

2022-03-31 20:27 UTC, Tbaut approved these changes
I tested Files and it looks good.

2022-04-01 09:39 UTC, merged