shift key functionality for selections
ChainSafe/files-ui pull request #2109
Opened 2022-04-25 19:00 UTC by tanmoyAtb

closes #2094

I've also made small adjustments to click and `ctrl+click`,
Please see if the behaviour feels intuitive.
---
Submission checklist: 

No UI change

2022-04-25 23:32 UTC, asnaith commented
@tanmoyAtb I really like this improvement. Definitely feels nice and intuitive (command + shift on mac). Working the same as macOS Finder now 🚀

2022-04-27 12:22 UTC, juans-chainsafe commented
@tanmoyAtb it works perfect! I tested on storage and files, the issue is fixed.
Also, I rerun the failed tests in cypress because there was an issue with the API when you try to upload a file.

2022-04-27 12:22 UTC, juans-chainsafe approved these changes

2022-04-27 16:40 UTC, juans-chainsafe requested changes
ctrl+click (cmd+shift or cmd+click on mac) is working in Chrome and Safari nicely, but is not working on Firefox

2022-05-03 14:42 UTC, Tbaut commented
indeed, I tried it locally on FF and it didn't work.

2022-05-04 07:03 UTC, tanmoyAtb commented
Hey guys, I tried out both `cmd+click` and `shift+click` with firefox with the render links. Seems to be working my side. Here's a screen recording.

https://user-images.githubusercontent.com/10713353/166635790-6922593e-7c20-4a13-af23-366bb0dd4a46.mov

2022-05-04 08:49 UTC, Tbaut commented
checked the render link, didn't work for me :( I'll check it out a little

2022-05-04 10:04 UTC, FSM1 approved these changes
lgtm 🎉 also tested in FF and it seems to be working just fine there as well 🤷🏼

2022-05-04 12:11 UTC, juans-chainsafe commented
I tried again but it doesn't work for me in Firefox, not sure why

https://user-images.githubusercontent.com/104365141/166678510-a1dff579-85c6-4497-af1d-17bf7aebfd2e.mov

2022-05-04 13:28 UTC, Tbaut commented
I figured what was the problem. Juan and I actually click on the checkboxes, not on the file themselves, in that case we don't use the same handler. This is done in `FileSystemTableItem` (and similar for grid items) and the checkbox only does `handleAddToSelectedItems`.

2022-05-05 11:32 UTC, tanmoyAtb commented
> I figured what was the problem. Juan and I actually click on the checkboxes, not on the file themselves, in that case we don't use the same handler. This is done in `FileSystemTableItem` (and similar for grid items) and the checkbox only does `handleAddToSelectedItems`.

cool, so do you think we should expand the checkbox click behaviour to handle `shift`/`cmd` ?

2022-05-05 12:35 UTC, juans-chainsafe commented
> > I figured what was the problem. Juan and I actually click on the checkboxes, not on the file themselves, in that case we don't use the same handler. This is done in `FileSystemTableItem` (and similar for grid items) and the checkbox only does `handleAddToSelectedItems`.
> 
> cool, so do you think we should expand the checkbox click behaviour to handle `shift`/`cmd` ?

I think that will be a good update, because as a user I was trying to to do it on the checkbox

2022-05-05 14:48 UTC, tanmoyAtb commented
> > > I figured what was the problem. Juan and I actually click on the checkboxes, not on the file themselves, in that case we don't use the same handler. This is done in `FileSystemTableItem` (and similar for grid items) and the checkbox only does `handleAddToSelectedItems`.
> > 
> > 
> > cool, so do you think we should expand the checkbox click behaviour to handle `shift`/`cmd` ?
> 
> I think that will be a good update, because as a user I was trying to to do it on the checkbox

I've made the updates to handle the `shift/cmd/ctrl` behaviour with checkbox clicks 👍

2022-05-05 16:48 UTC, Tbaut commented
did you test it on Firefox? it's not working for me. I wonder if the mouse event is passed correctly. I added some logs in the `handleItemSelectOnCheck` but it looks like it's not called when ctrl or shift are pressed.

2022-05-05 17:24 UTC, Tbaut reviewed
Small comment in the code. the code looks good otherwise.
Re. the checkbox annoyance, I'm with Juan, as a user, I'm used to click on the checkboxes, on gmail for instance. I did look at how they do that, and they actually don't use real checkboxes, they use a trick with `div`, anyway it's a whole other ballpark.

2022-05-05 17:24 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
> +      const isItemAlreadySelected = selectedItems.find((s) => s.cid === item.cid)
You can use `selectedItems.~~contains~~includes(item.cid)` here.

2022-05-09 15:37 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
> +      const isItemAlreadySelected = selectedItems.find((s) => s.cid === item.cid)
This implementation becomes a problem really, as selectedItems is an array of objects. simply checking the cid match works.

2022-05-09 15:39 UTC, tanmoyAtb commented
I found a number of reports of this problem. like this one
https://stackoverflow.com/questions/37803218/javascript-ctrl-click-not-working-in-firefox

FF really becomes an annoyance sometimes. 
For now the implementation we have should be good enough for most cases. We can tackle the FF problem in another issue.

2022-05-09 15:53 UTC, juans-chainsafe approved these changes
I see, then for me seems ok to merge it like this, because the functionality is working, but not in the checkbox like in other browsers, but yes, the problem seems to be only in FF

2022-05-10 13:37 UTC, juans-chainsafe commented
Issue created https://github.com/ChainSafe/ui-monorepo/issues/2123

2022-05-11 13:39 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
> +      const isItemAlreadySelected = selectedItems.find((s) => s.cid === item.cid)
sorry, I should have said `.includes` indead of contains. It's more elegant than `.find` in this case. 
```suggestion
      const isItemAlreadySelected = selectedItems.includes(item.cid)
```

and then you get a boolean, and you can check for `isItemAlreadySelected` instead of `isItemAlreadySelected.length`

2022-05-11 13:40 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
> +      const lastIndex = selectedItems.length
here
```suggestion
      const lastIndex = selectedItems
```

2022-05-11 14:12 UTC, Tbaut commented
Having 2 different browsers having 2 implementations is rare, and I agree we can tackle this in a new issue, but I wouldn't call it a bug right away. This PR made a change from `onChange` to `onClick`, take a look at https://stackoverflow.com/questions/26925469/on-click-event-in-firefox where the `onChange` event seem to yield the right effect.

A personal opinion, Firefox isn't perfect, but it's an open source and much more privacy preserving software than any of its competitors, and as much as I'm sad to see some things don't work as we want, we should try everything we can to provide the best experience for FF Files users.

2022-05-11 16:21 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
> +      const isItemAlreadySelected = selectedItems.find((s) => s.cid === item.cid)
Yup, using the `includes` now.

2022-05-11 16:23 UTC, tanmoyAtb commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
> +      const lastIndex = selectedItems.length
not sure about this one. we need to keep the `length` part to sure selectedItems is not empty as we are trying access elements inside it.

2022-05-11 16:26 UTC, tanmoyAtb commented
All right. I found a solution to our situation with FF. The problem is mainly handling `checkbox` type inputs, but in our checkbox component we already have a `div` component that is actually displayed (this is probably what was the gmail implementation as well). So using the `onClick` with the `div` element does the trick. :)

2022-05-12 12:46 UTC, Tbaut commented on packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
> +      const isItemAlreadySelected = selectedItems.find((s) => s.cid === item.cid && s.name === item.name)
Given the name, I'd consider making this a boolean
```suggestion
      const isItemAlreadySelected = selectedItems
        .find((s) => s.cid === item.cid && s.name === item.name)
        .length > 0
```

2022-05-12 12:46 UTC, Tbaut commented on packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
> +      const lastIndex = selectedItems.length
sorry my mistake, I mixed this one and `isItemAlreadySelected`.

2022-05-12 12:56 UTC, Tbaut approved these changes
This is awesome, thanks a lot for your perseverance, it's working well!

I left another small comment, to make a `is***` variable a boolean.

2022-05-12 13:03 UTC, tanmoyAtb commented
> This is awesome, thanks a lot for your perseverance, it's working well!
> 
> ~I left another small comment, to make a `is***` variable a boolean.~ edit: already accepted :)

Thanks for pushing me into looking for the solution :) feels really good to have the full solution.

2022-05-12 15:08 UTC, FSM1 commented
> > This is awesome, thanks a lot for your perseverance, it's working well!
> > ~I left another small comment, to make a `is***` variable a boolean.~ edit: already accepted :)
> 
> Thanks for pushing me into looking for the solution :) feels really good to have the full solution.

Does this PR also close #2123 ?

2022-05-12 15:26 UTC, merged

2022-05-12 15:26 UTC, Tbaut commented
Yup :)