NFT Metadata form
ChainSafe/files-ui pull request #2125
Opened 2022-05-11 10:16 UTC by FSM1

This is a very basic MVP of the NFT Metadata creation. The main objective here was to ensure that the basic requirements can be met. The UX can still do with a lot of improvement.

2022-05-13 16:54 UTC, Tbaut reviewed
Nice!! I left a couple comments in the code, I'll play with it now :)

2022-05-13 16:54 UTC, Tbaut commented on packages/common-components/src/FileInput/FileInput.tsx
> +                        removeItem(1)
should we make the removeItem param optional and have no param here?? This `1` disturbed me although it's actually ignored for single File items.

2022-05-13 16:54 UTC, Tbaut commented on packages/common-components/src/FileInput/FileInput.tsx
> +                  : <li className={clsx(classes.item, classNames?.item)}>
I'm generally wary of duplicating the code. it'd be great to extract it in a variable if that's not too annoying. I often had endless loops using useCallback though, we can avoid them I guess.

2022-05-13 16:54 UTC, Tbaut commented on packages/common-components/src/FileInput/FileInput.tsx
> +          {value === null || Array.isArray(value) && value?.length === 0
with parenthesis?
```suggestion
          {value === null || (Array.isArray(value) && value?.length === 0)
```

2022-05-13 16:54 UTC, Tbaut commented on packages/storage-ui/src/Components/Elements/FormikImageInput.tsx
> +    const [preview, setPreview] = useState<any>(undefined)
Any way we can define this? Like `Blob | MediaSource | undefined`

2022-05-13 16:54 UTC, Tbaut commented on packages/storage-ui/src/Components/Elements/FormikImageInput.tsx
> +          {value ? <>
can we have the `?` and `:` at the beginning of their line for consistency?

2022-05-13 16:54 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/UploadNFT.tsx
> +      <div style={{ border: "1px #000 solid" }}>
Any reason not to use the usual classes for the style?

2022-05-13 16:54 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/UploadNFT.tsx
> +          label="Property name" />
Trans and new line
```suggestion
          label=t`Property name`
        />
```

2022-05-13 16:54 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/UploadNFT.tsx
> +          onClick={() => formikBag.setFieldValue(`${namespace}.${newFieldName}`, (newFieldType === "array")
can we extract this function for better readability

2022-05-13 16:54 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/UploadNFT.tsx
> +    const [newFieldType, setNewFieldType] = useState<"value" | "array" | "file" | "object">("value")
can we name this type, it's being reused below.

2022-05-13 16:54 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/UploadNFT.tsx
> +const CreateNFTPage: React.FC = () => {
There are many components in this file, would it be a little easier to read if we had them in separate files?

2022-05-13 16:54 UTC, Tbaut commented on packages/common-components/src/FileInput/FileInput.tsx
> +  const [{ value }, meta, helpers] = useField<Array<FileWithPath> | FileWithPath | null>(name)
just for readability using `FileWithPath[]` could be cool
```suggestion
  const [{ value }, meta, helpers] = useField<FileWithPath[] | FileWithPath | null>(name)
```

2022-05-13 16:54 UTC, Tbaut commented on packages/storage-ui/src/Components/Layouts/AppNav.tsx
> +                >
```suggestion
                <Typography variant="h5">
```

2022-05-13 16:54 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/UploadNFT.tsx
> +          label="Property type"/>
```suggestion
          label="Property type"
        />
```

2022-05-13 16:54 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/UploadNFT.tsx
> +      console.log(result)
```suggestion
      const result = await storageApiClient.uploadNFT(val)
```

2022-05-13 16:54 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/UploadNFT.tsx
> +          <Button type="submit">Upload</Button>
```suggestion
          <Button type="submit"><Trans>Upload</Trans></Button>
```

2022-05-17 13:57 UTC, FSM1 commented on packages/storage-ui/src/Components/Pages/UploadNFT.tsx
> +      console.log(result)
leaving these in here for now

2022-05-17 14:28 UTC, FSM1 commented on packages/storage-ui/src/Components/Pages/UploadNFT.tsx
> +      <div style={{ border: "1px #000 solid" }}>
Mostly just convenience factor while deving. Will be removed once proper styling is applied

2022-05-17 17:29 UTC, tanmoyAtb requested changes
Leaving a couple of comments here. 
Looking into the UI.

2022-05-17 17:29 UTC, tanmoyAtb commented on packages/common-components/src/FileInput/FileInput.tsx
> +    onFileNumberChange && Array.isArray(value) && onFileNumberChange(value.length)
when `value` is of type `FileWithPath`, this function won't be triggered, is that a problem ?

2022-05-17 17:29 UTC, tanmoyAtb commented on packages/storage-ui/src/Components/Elements/FormikImageInput.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
We could place the `return` part in another useEffect to avoid this eslint disabled

2022-05-17 17:29 UTC, tanmoyAtb commented on packages/storage-ui/src/Components/Layouts/AppNav.tsx
> +                className={clsx(classes.navItem, appNavTab === "cids" && "selected")}
`appNavTab` should be something like `uploadNFT` here

2022-05-19 12:31 UTC, FSM1 commented on packages/common-components/src/FileInput/FileInput.tsx
> +                  : <li className={clsx(classes.item, classNames?.item)}>
Are you referring to the `<li>...</li>` ?

2022-05-19 12:47 UTC, Tbaut commented on packages/common-components/src/FileInput/FileInput.tsx
> +                  : <li className={clsx(classes.item, classNames?.item)}>
yes, unless I missed something the `<li>` is the same on both branches of the ternary, just the `map` and the click differ.

2022-05-31 11:18 UTC, FSM1 commented on packages/common-components/src/FileInput/FileInput.tsx
> +    onFileNumberChange && Array.isArray(value) && onFileNumberChange(value.length)
I don't think so really. I honestly don't even remember why we added this handler rather than having the parent deal with this by interpreting the `value` that is being propagated through formik.

2022-05-31 15:02 UTC, Tbaut reviewed
Played with it locally and all tests passed but one. (the one that's marked as only right now)

> files must be a `array` type, but the final value was: `null`. If "null" is intended as an empty value be sure to mark the schema as `.nullable()`

So I fixed this. The `yarn` issue was pretty weird, but I'll check it out more in detail if it keeps failing.

2022-05-31 16:05 UTC, Tbaut commented on packages/common-components/src/FileInput/FileInput.tsx
> +  const [{ value }, meta, helpers] = useField<FileWithPath[] | FileWithPath | null>(name)
Is there a good readon to do this? this is messing up with the formik `schema` for file upload that expect an array (and then don't show an error any more because there's now a `null` possibility). Also our `onSubmit` all expect an array. Should we modify them all? I find an array much easier to handle, it'd be nice if we could keep that.

2022-06-06 14:05 UTC, FSM1 commented on packages/common-components/src/FileInput/FileInput.tsx
> +  const [{ value }, meta, helpers] = useField<FileWithPath[] | FileWithPath | null>(name)
I needed to use a different `value` for an empty array property, that would be detectable at runtime. This is where `null` came in.

2022-06-08 12:41 UTC, tanmoyAtb approved these changes
Lets go with it 👍

2022-06-09 14:23 UTC, Tbaut approved these changes
uuuh yes

2022-06-09 14:23 UTC, merged