Navigation position style fixes [storage]
ChainSafe/files-ui pull request #2193
Opened 2022-06-15 17:26 UTC by tanmoyAtb

closes #2087

---
Submission checklist: 

   

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

2022-06-16 12:39 UTC, juans-chainsafe requested changes
Looking good! but I have a problem, only in mobile of course, using Chrome or Metamask app:
In CIDs table I only see the columns "Name", "Cid" and the 3 dots. I can't move left or right to see other columns ("Created", "Size", "Status")
![IMG_BB12982AE042-1](https://user-images.githubusercontent.com/104365141/174071316-669eb635-7f70-473f-aff1-d09a42c464dc.jpeg)

2022-06-16 17:43 UTC, tanmoyAtb commented
> Looking good! but I have a problem, only in mobile of course, using Chrome or Metamask app: In CIDs table I only see the columns "Name", "Cid" and the 3 dots. I can't move left or right to see other columns ("Created", "Size", "Status") ![IMG_BB12982AE042-1](https://user-images.githubusercontent.com/104365141/174071316-669eb635-7f70-473f-aff1-d09a42c464dc.jpeg)

This was very intentional actually. If you have multiple columns in the table, the alignment of the whole page breaks and looks odd. 
I wanted to add a quick fix to keep the navigation usable and I don't think anyone would look for CID information on mobile, therefore omitted the columns.

2022-06-16 18:07 UTC, juans-chainsafe approved these changes
@tanmoyAtb well, yes, make sense to only have those columns in mobile, but just in case I want @asnaith opinion on that to be sure!

👍 I agree with Tanmoy's rationale, it's not worth the time investment in making the view support all columns as are expecting very low usage of Storage UI on mobile devices.

2022-06-16 21:54 UTC, asnaith commented
> @tanmoyAtb well, yes, make sense to only have those columns in mobile, but just in case I want @asnaith opinion on that to be sure!
> 
> 

👍 I agree with Tanmoy's rationale, it's not worth the time investment in making the view support all columns as are expecting very low usage of Storage UI on mobile devices.

2022-06-20 12:07 UTC, Tbaut reviewed
Just a nit, the code is looking good otherwise

2022-06-20 12:07 UTC, Tbaut commented on packages/storage-ui/src/Components/Pages/CidsPage.tsx
> +              }
We can group this all can't we?
```suggestion
              {desktop && <>
                <TableHeadCell
                  data-cy="table-header-created"
                  sortButtons={true}
                  onSortChange={() => handleSortToggle("date_uploaded")}
                  sortDirection={sortColumn === "date_uploaded" ? sortDirection : undefined}
                  sortActive={sortColumn === "date_uploaded"}
                  align="center"
                >
                  <Trans>Created</Trans>
                </TableHeadCell>
                <TableHeadCell
                  data-cy="table-header-size"
                  sortButtons={true}
                  onSortChange={() => handleSortToggle("size")}
                  sortDirection={sortColumn === "size" ? sortDirection : undefined}
                  sortActive={sortColumn === "size"}
                  align="center"
                >
                  <Trans>Size</Trans>
                </TableHeadCell>
                <TableHeadCell
                  data-cy="table-header-status"
                  sortButtons={false}
                  align="center"
                >
                  <Trans>Status</Trans>
                </TableHeadCell>
                <TableHeadCell>{/* IPFS Gateway */}</TableHeadCell>
              </>}
```

2022-06-20 12:07 UTC, Tbaut commented on packages/storage-ui/src/Components/Elements/CidRow.tsx
> +      }
```suggestion
      {desktop && <>
        <TableCell>
          {dayjs(pinStatus.created).format("DD MMM YYYY h:mm a")}
        </TableCell>
        <TableCell>
          {pinStatus.info?.size ? formatBytes(pinStatus.info?.size, 2) : "-"}
        </TableCell>
        <TableCell>
          {pinStatus.status}
        </TableCell>
        <TableCell className={classes.externalIconCell}>
          {pinStatus.status === "pinned" && (
            <ExternalIcon
              className={classes.icon}
              onClick={() => window.open(`${trimChar(IPFS_GATEWAY, "/")}/${pinStatus.pin?.cid}`)}
            />
          )}
        </TableCell>
      </>}
```

2022-06-20 16:04 UTC, tanmoyAtb commented
> Just a nit, the code is looking good otherwise

Updates are in.

2022-06-21 15:56 UTC, Tbaut approved these changes
Code looks good

2022-06-21 15:56 UTC, merged